import { HOST } from "@/common/constants"
import { APP_NAME } from "@repo/constants"
import { Metadata } from "next"
import AuthGuard from "@/common/components/AuthGuard"
import AddOns from "@/module/Admin/Listings/Declined/Rental/AddOns"

export const metadata: Metadata = {
  title: `${HOST} - ${APP_NAME}`,
  description: `Generated by ${APP_NAME}`,
}

const AddOnsPage = () => {
  return (
    <AuthGuard>
      <AddOns pageType="edit" />
    </AuthGuard>
  )
}

export default AddOnsPage
