import { APP_NAME } from "@repo/constants"
import { Metadata } from "next"
import { HOME } from "@/common/constants"
import Locations from "@/module/Locations"

export const metadata: Metadata = {
  title: `${HOME} - ${APP_NAME}`,
  description: `Generated by ${APP_NAME}`,
}

const LocationsPage = () => {
  return <Locations />
}

export default LocationsPage
