import type { Metadata } from "next"

import "@/app/globals.css"
import { Toaster } from "react-hot-toast"
import React from "react"
import { LOGO_SINGLE_IMAGE } from "@/common/constants/index"
import { APP_NAME } from "@repo/constants"
import Header from "@/common/components/Header"
import Footer from "@/common/components/Footer"
import GlobalWrappers from "@/common/components/Wrappers/GlobalWrappers"

export const metadata: Metadata = {
  title: APP_NAME,
  description: `Generated by ${APP_NAME}`,
}

export default async function AccommodationLayout({
  children,
}: {
  readonly children: React.ReactNode
}) {
  return (
    <html lang="en">
      <link rel="icon" type="image/x-icon" href={LOGO_SINGLE_IMAGE} />
      <body>
        <Toaster />

            <GlobalWrappers>
              <Header contentWidth="small" />
              <div className="min-h-screen">{children}</div>
              <Footer contentWidth="small" />
            </GlobalWrappers>

      </body>
    </html>
  )
}
