import { HOST } from "@/common/constants"
import { APP_NAME } from "@repo/constants"
import { Metadata } from "next"
import HostingMessages from "@/module/Hosting/Messages"
import AuthGuard from "@/common/components/AuthGuard"

export const metadata: Metadata = {
  title: `${HOST} - ${APP_NAME}`,
  description: `Generated by ${APP_NAME}`,
}

const HostingMessagesPage = () => {
  return (
    <AuthGuard>
      <HostingMessages />
    </AuthGuard>
  )
}

export default HostingMessagesPage
