import React from "react"
import { APP_NAME } from "@repo/constants"
import { Metadata } from "next"
import { RENTAL } from "@/common/constants"
import Rental from "@/module/Listing/Rental"
import { getRequest } from "@/common/helpers/getRequest"
import { notFound } from "next/navigation"

export const metadata: Metadata = {
  title: `${RENTAL} - ${APP_NAME}`,
  description: `Generated by ${APP_NAME}`,
}

type T_Props = {
  params: {
    rentalId: string
  }
}

const RentalPublicPage = async ({ params: { rentalId } }: T_Props) => {
  const listing = await getRequest(`/rentals/public/${rentalId}`)

  if (listing && listing.status === 404) {
    notFound()
  }

  if ((listing && listing.status === 500) || !listing) {
    throw new Error("Internal Server Error")
  }

  return <Rental rentalData={listing} />
}

export default RentalPublicPage
