import React from "react"
import { APP_NAME } from "@repo/constants"
import { Metadata } from "next"
import { ACCOMODATION } from "@/common/constants"
import Rental from "@/module/Listing/Rental"

export const metadata: Metadata = {
  title: `${ACCOMODATION} - ${APP_NAME}`,
  description: `Generated by ${APP_NAME}`,
}

const AccommodationPage = async () => {
  return <Rental />
}

export default AccommodationPage
