export const ACTIVITIES = [
  "Break time",
  "Photo stop",
  "Visit",
  "Guided tour",
  "Free time",
  "Shopping",
  "Sightseeing",
  "Walk",
  "Safety briefing",
  "Self-guided tour",
  "Overnight stay",
  "Pass by",
  "Sunset",
  "Scenic views",
  "Sunrise",
  "Hop-On Hop-Off stop",
  "Bus tour",
  "Scenic drive",
  "Bike ride",
  "Hiking",
  "Camp activities",
  "Shooting range",
  "Ziplining",
  "Air balloon flight",
  "Helicopter flight",
  "Aerial view",
  "Camel ride",
  "Game drive",
  "Horse ride",
  "Wildlife viewing",
  "Dune bashing",
  "Snowmobile ride",
  "Concert",
  "Dance show",
  "Traditional dance show",
  "Arts & crafts market visit",
  "Workshop",
  "Food market visit",
  "Wine tasting",
  "Cooking class",
  "Tea ceremony",
  "Food tasting",
  "Champagne tasting",
  "Whiskey tasting",
  "Cheese tasting",
  "Coffee tasting",
  "Aperitif",
  "Beer",
  "Cocktail",
  "Coffee",
  "Spirits",
  "Tea",
  "Wine",
  "Picnic",
  "Street food",
  "BBQ",
  "Local snacks",
  "Regional food",
  "Tapas",
  "Breakfast",
  "Brunch",
  "Dessert",
  "Dinner",
  "Lunch",
  "Meal onboard",
  "Welcome refreshments",
  "Swimming",
  "Snorkeling",
  "Marine life viewing",
  "Banana boat",
  "Boat cruise",
  "Kayaking",
  "Sailing",
  "Quad bike ride",
  "Off-road adventure",
]

export const TRANSFERS = [
  "Car",
  "Van",
  "Bus",
  "Motorbike",
  "Tuktuk",
  "Tricycle",
  "Scooter",
  "Motorbike",
  "Party boat",
  "Local pump boat",
  "Kayak",
  "Speedboat",
  "Paddleboat",
  "Paddleboard",
  "Jetski",
  "Glass bottom boat",
]
