import { HOST } from "@/common/constants"
import { APP_NAME } from "@repo/constants"
import { Metadata } from "next"
import HostingReservations from "@/module/Hosting/Reservations/Upcoming"
import AuthGuard from "@/common/components/AuthGuard"
import ReservationCalendar from "@/module/Hosting/Reservations/Calendar"
import RentalsReservationCalendar from "@/module/Hosting/Reservations/Calendar/rentals"

export const metadata: Metadata = {
  title: `${HOST} - ${APP_NAME}`,
  description: `Generated by ${APP_NAME}`,
}

const HostingRentalsReservationCalendarPage = () => {
  return (
    <AuthGuard>
      <RentalsReservationCalendar />
    </AuthGuard>
  )
}

export default HostingRentalsReservationCalendarPage
