export const data = [
  {
    category: "Property",
    name: "Mountain top house",
    month: "All",
    year: "2024",
    views: 2000,
    newBookings: 160,
    bookingRate: 5,
    viewsData: [
      { date: "Jan", count: 20 },
      { date: "Feb", count: 3 },
      { date: "Mar", count: 7 },
      { date: "Apr", count: 12 },
      { date: "May", count: 33 },
      { date: "Jun", count: 66 },
      { date: "July", count: 28 },
      { date: "Aug", count: 41 },
      { date: "Sep", count: 23 },
      { date: "Oct", count: 15 },
      { date: "Nov", count: 75 },
      { date: "Dec", count: 19 },
    ],
    specificMonth: {
      month: "May",
      data: [
        { date: "1", count: 0 },
        { date: "2", count: 0 },
        { date: "3", count: 0 },
        { date: "4", count: 0 },
        { date: "5", count: 0 },
        { date: "6", count: 0 },
        { date: "7", count: 0 },
        { date: "8", count: 0 },
        { date: "9", count: 0 },
        { date: "10", count: 0 },
        { date: "11", count: 0 },
        { date: "12", count: 0 },
        { date: "13", count: 0 }, // Added missing dates
        { date: "14", count: 0 },
        { date: "15", count: 0 },
        { date: "16", count: 0 },
        { date: "17", count: 0 },
        { date: "18", count: 0 },
        // Add more dates as needed
      ],
    },
    listing: "Mountain top house",
    cancelled: 6500000,
    completed: 7500000,
  },
  {
    category: "Property",
    listing: "Word of Life",
    cancelled: 85000,
    completed: 1000000,
  },
  {
    category: "Property",
    listing: "Bianca Hotel",
    cancelled: 20000,
    completed: 225000,
  },
  {
    category: "Rental",
    listing: "Mountain top house",
    cancelled: 400000,
    completed: 800000,
  },
  {
    category: "Rental",
    listing: "Word of Life",
    cancelled: 750000,
    completed: 1000000,
  },
  {
    category: "Rental",
    listing: "Bianca Hotel",
    cancelled: 80000,
    completed: 225000,
  },
]
