import { HOST } from "@/common/constants"
import { APP_NAME } from "@repo/constants"
import { Metadata } from "next"
import AuthGuard from "@/common/components/AuthGuard"
import Inclusions from "@/module/Admin/Listings/Live/Activity/Inclusions"

export const metadata: Metadata = {
  title: `${HOST} - ${APP_NAME}`,
  description: `Generated by ${APP_NAME}`,
}

const RentalBasicInfoPage = () => {
  return (
    <AuthGuard>
      <Inclusions />
    </AuthGuard>
  )
}

export default RentalBasicInfoPage
