import { HOST } from "@/common/constants"
import { APP_NAME } from "@repo/constants"
import { Metadata } from "next"
import AuthGuard from "@/common/components/AuthGuard"
import AdditionalInfo from "@/module/Admin/Listings/Live/Activity/AdditionalInfo"

export const metadata: Metadata = {
  title: `${HOST} - ${APP_NAME}`,
  description: `Generated by ${APP_NAME}`,
}

const ActivityAdditionalInfoPage = () => {
  return (
    <AuthGuard>
      <AdditionalInfo />
    </AuthGuard>
  )
}

export default ActivityAdditionalInfoPage
