import { HOST } from "@/common/constants"
import { APP_NAME } from "@repo/constants"
import { Metadata } from "next"
import HostingTodayArriving from "@/module/Hosting/Today/Arriving"
import AuthGuard from "@/common/components/AuthGuard"

export const metadata: Metadata = {
  title: `${HOST} - ${APP_NAME}`,
  description: `Generated by ${APP_NAME}`,
}

const HostingTodayArrivingPage = () => {
  return (
    <AuthGuard>
      <HostingTodayArriving />
    </AuthGuard>
  )
}

export default HostingTodayArrivingPage
