import { HOST } from "@/common/constants"
import { APP_NAME } from "@repo/constants"
import { Metadata } from "next"
import AuthGuard from "@/common/components/AuthGuard"
import WholePlace from "@/module/Admin/Listings/ForReview/Property/Units/Edit/WholePlace"

export const metadata: Metadata = {
  title: `${HOST} - ${APP_NAME}`,
  description: `Generated by ${APP_NAME}`,
}

const EditWholePlaceUnitPage = () => {
  return (
    <AuthGuard>
      <WholePlace />
    </AuthGuard>
  )
}

export default EditWholePlaceUnitPage
