import React from "react"
import { APP_NAME } from "@repo/constants"
import { Metadata } from "next"
import Activity from "@/module/Listing/activity"
import { notFound } from "next/navigation"
import { getRequest } from "@/common/helpers/getRequest"

export const metadata: Metadata = {
  title: `Activity - ${APP_NAME}`,
  description: `Generated by ${APP_NAME}`,
}

type T_Props = {
  params: {
    activityId: string
  }
}

const ActivityPublicPage = async ({ params: { activityId } }: T_Props) => {
  const listing = await getRequest(`/activities/public/${activityId}`)

  if (listing && listing.status === 404) {
    notFound()
  }

  if ((listing && listing.status === 500) || !listing) {
    throw new Error("Internal Server Error")
  }

  return <Activity activity={listing.item} />
}

export default ActivityPublicPage
