services:
  es-api:
    build:
      context: ../../
      dockerfile: ./docker/api/Dockerfile
      args:
        API_PORT: ${API_PORT}
        PASSWORD_ENCRYPT_KEY: ${PASSWORD_ENCRYPT_KEY}
        CARD_ENCRYPT_KEY: ${CARD_ENCRYPT_KEY}
        CSRF_SIGN_KEY: ${CSRF_SIGN_KEY}
        ALLOWED_CLIENTS: ${ALLOWED_CLIENTS}
        WEB_URL: ${WEB_URL}
        API_URL: ${API_URL}
        API_MOCK_URL: ${API_MOCK_URL}
        RECAPTCHA_KEY_SECRET: ${RECAPTCHA_KEY_SECRET}
        AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
        AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
        AWS_REGION: ${AWS_REGION}
        XENDIT_URL: ${XENDIT_URL}
        XENDIT_SECRET: ${XENDIT_SECRET}
        GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
        GOOGLE_SECRET_ID: ${GOOGLE_SECRET_ID}
        GOOGLE_APIS_URL: ${GOOGLE_APIS_URL}
        REDIS_URL: ${REDIS_URL}
        WINDY_KEY: ${WINDY_KEY}
        MONGO_URL: ${MONGO_URL}
    image: es-api:latest
    container_name: es-api
    restart: unless-stopped
    ports:
      - 9000:9000

