import { HOST } from "@/common/constants"
import { APP_NAME } from "@repo/constants"
import { Metadata } from "next"
import AuthGuard from "@/common/components/AuthGuard"
import Settings from "@/module/Hosting/settings"

export const metadata: Metadata = {
  title: `${HOST} - ${APP_NAME}`,
  description: `Generated by ${APP_NAME}`,
}

const SettingsPage = () => {
  return (
    <AuthGuard>
     <Settings/>
    </AuthGuard>
  )
}

export default SettingsPage
