import { PROPERTY_FACILITIES } from "@/module/Hosting/Listings/constants/amenities"

const MOST_POPULAR = "Most Popular"
const OUTDOORS = "Outdoors"
const ACTIVITIES = "Activities"
const FOOD_DRINK = "Food & Drink"
const INTERNET = "Internet"
const PARKING = "Parking"
const SERVICES = "Services"
const RECEPTION_SERVICES = "Reception Services"
const SAFETY_SECURITY = "Safety & Security"
const GENERAL = "General"
const WELLNESS = "Wellness"
const CLEANING_SERVICES = "Cleaning Services"
const BUSINESS_FACILITIES = "Business Facilities"
const ENTERTAINMENT = "Entertainment and family services"
const ONSITE = "On-site Payment Methods"
const LANGUAGES = "Languages Spoken"

export const getFacilities = () => {
  let count = 0
  const data = PROPERTY_FACILITIES.map((item, index1) => {
    const mapFac = item.facilities.map((fac, index2) => {
      const newData = {
        index: count + index2,
        id: null,
        category: item.category,
        facility: fac,
        propertyId: null,
        isSelected: false,
      }
      return newData
    })
    count = count + item.facilities.length
    return mapFac
  }).flat()
  return data
}

export const NEW_FACILITIES = [
  {
    index: 0,
    id: null,
    category: MOST_POPULAR,
    facility: "Bar",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 1,
    id: null,
    category: MOST_POPULAR,
    facility: "Sauna",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 2,
    id: null,
    category: MOST_POPULAR,
    facility: "Garden",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 3,
    id: null,
    category: MOST_POPULAR,
    facility: "Terrace",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 4,
    id: null,
    category: MOST_POPULAR,
    facility: "Hot tub/Jacuzzi",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 5,
    id: null,
    category: MOST_POPULAR,
    facility: "Heating",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 6,
    id: null,
    category: MOST_POPULAR,
    facility: "Free WiFi",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 7,
    id: null,
    category: MOST_POPULAR,
    facility: "Air conditioning",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 8,
    id: null,
    category: MOST_POPULAR,
    facility: "Swimming pool",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 9,
    id: null,
    category: MOST_POPULAR,
    facility: "Beach",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 10,
    id: null,
    category: OUTDOORS,
    facility: "Beachfront",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 11,
    id: null,
    category: OUTDOORS,
    facility: "Outdoor furniture",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 12,
    id: null,
    category: OUTDOORS,
    facility: "Sun terrace",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 13,
    id: null,
    category: OUTDOORS,
    facility: "Private beach area",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 14,
    id: null,
    category: OUTDOORS,
    facility: "BBQ facilities",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 15,
    id: null,
    category: OUTDOORS,
    facility: "Parking",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 16,
    id: null,
    category: OUTDOORS,
    facility: "Shared kitchen",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 17,
    id: null,
    category: OUTDOORS,
    facility: "Smoking area",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 18,
    id: null,
    category: OUTDOORS,
    facility: "Garden",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 19,
    id: null,
    category: OUTDOORS,
    facility: "Common area",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 20,
    id: null,
    category: ACTIVITIES,
    facility: "Bicycle rental (additional charge)",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 21,
    id: null,
    category: ACTIVITIES,
    facility: "Happy hour",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 22,
    id: null,
    category: ACTIVITIES,
    facility: "Beach",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 23,
    id: null,
    category: ACTIVITIES,
    facility: "Snorkelling (additional charge)",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 24,
    id: null,
    category: ACTIVITIES,
    facility: "Diving (additional charge)",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 25,
    id: null,
    category: ACTIVITIES,
    facility: "Cycling",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 26,
    id: null,
    category: ACTIVITIES,
    facility: "Hiking (additional charge)",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 27,
    id: null,
    category: ACTIVITIES,
    facility: "Billiards",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 28,
    id: null,
    category: ACTIVITIES,
    facility: "Children's playground",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 29,
    id: null,
    category: ACTIVITIES,
    facility: "Nearby golf course (additional charge)",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 30,
    id: null,
    category: ACTIVITIES,
    facility: "Cooking class",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 31,
    id: null,
    category: ACTIVITIES,
    facility: "Tour or class about local culture",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 32,
    id: null,
    category: ACTIVITIES,
    facility: "Themed dinner nights",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 33,
    id: null,
    category: ACTIVITIES,
    facility: "Bike tours",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 34,
    id: null,
    category: ACTIVITIES,
    facility: "Walking tours",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 35,
    id: null,
    category: ACTIVITIES,
    facility: "Movie nights",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 36,
    id: null,
    category: ACTIVITIES,
    facility: "Beach sports",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 37,
    id: null,
    category: ACTIVITIES,
    facility: "Badminton equipment",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 38,
    id: null,
    category: ACTIVITIES,
    facility: "Water sport facilities on site",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 39,
    id: null,
    category: ACTIVITIES,
    facility: "Snorkelling",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 40,
    id: null,
    category: ACTIVITIES,
    facility: "Games room",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 41,
    id: null,
    category: ACTIVITIES,
    facility: "Fishing (additional charge)",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 42,
    id: null,
    category: ACTIVITIES,
    facility: "Table tennis",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 43,
    id: null,
    category: FOOD_DRINK,
    facility: "Snack bar",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 44,
    id: null,
    category: FOOD_DRINK,
    facility: "Bar",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 45,
    id: null,
    category: FOOD_DRINK,
    facility: "Restaurant",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 46,
    id: null,
    category: FOOD_DRINK,
    facility: "Happy hour",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 47,
    id: null,
    category: FOOD_DRINK,
    facility: "Free breakfast included",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 48,
    id: null,
    category: FOOD_DRINK,
    facility: "Breakfast (additional charge)",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 49,
    id: null,
    category: FOOD_DRINK,
    facility: "Special diet menus (on request)",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 50,
    id: null,
    category: FOOD_DRINK,
    facility: "Special diet menus (additional charge)",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 51,
    id: null,
    category: INTERNET,
    facility: "Free WiFi",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 52,
    id: null,
    category: INTERNET,
    facility: "WiFi (additional charge)",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 53,
    id: null,
    category: INTERNET,
    facility: "Starlink",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 54,
    id: null,
    category: INTERNET,
    facility: "Co-working space",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 55,
    id: null,
    category: PARKING,
    facility: "Private parking",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 56,
    id: null,
    category: PARKING,
    facility: "Street parking",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 57,
    id: null,
    category: PARKING,
    facility: "Motorbike parking",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 58,
    id: null,
    category: PARKING,
    facility: "Car park",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 59,
    id: null,
    category: PARKING,
    facility: "Parking garage",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 60,
    id: null,
    category: PARKING,
    facility: "Accessible parking",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 61,
    id: null,
    category: SERVICES,
    facility: "Shuttle service (Additional charge)",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 62,
    id: null,
    category: SERVICES,
    facility: "Luggage storage",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 63,
    id: null,
    category: SERVICES,
    facility: "Tour desk",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 64,
    id: null,
    category: SERVICES,
    facility: "Car hire (additional charge)",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 65,
    id: null,
    category: SERVICES,
    facility: "Packed lunches (additional charge)",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 66,
    id: null,
    category: SERVICES,
    facility: "Babysitting/child services (additional charge)",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 67,
    id: null,
    category: SERVICES,
    facility: "Airport shuttle (additional charge)",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 68,
    id: null,
    category: SERVICES,
    facility: "Free airport shuttle",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 69,
    id: null,
    category: SERVICES,
    facility: "Room service",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 70,
    id: null,
    category: SERVICES,
    facility: "Room service (additional charge)",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 71,
    id: null,
    category: RECEPTION_SERVICES,
    facility: "Invoice provided",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 72,
    id: null,
    category: RECEPTION_SERVICES,
    facility: "Lockers",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 73,
    id: null,
    category: RECEPTION_SERVICES,
    facility: "Private check-in/check-out",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 74,
    id: null,
    category: RECEPTION_SERVICES,
    facility: "Concierge service",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 75,
    id: null,
    category: RECEPTION_SERVICES,
    facility: "Luggage storage",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 76,
    id: null,
    category: RECEPTION_SERVICES,
    facility: "Express check-in/check-out",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 77,
    id: null,
    category: RECEPTION_SERVICES,
    facility: "24/7 check-in",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 78,
    id: null,
    category: SAFETY_SECURITY,
    facility: "24/7 security guard",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 79,
    id: null,
    category: SAFETY_SECURITY,
    facility: "Security guard at night",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 80,
    id: null,
    category: SAFETY_SECURITY,
    facility: "Fire extinguishers",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 81,
    id: null,
    category: SAFETY_SECURITY,
    facility: "CCTV outside property",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 82,
    id: null,
    category: SAFETY_SECURITY,
    facility: "CCTV in common areas",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 83,
    id: null,
    category: SAFETY_SECURITY,
    facility: "Safety deposit box",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 84,
    id: null,
    category: GENERAL,
    facility: "Designated smoking area",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 85,
    id: null,
    category: GENERAL,
    facility: "Air conditioning",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 86,
    id: null,
    category: GENERAL,
    facility: "Soundproof rooms",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 87,
    id: null,
    category: GENERAL,
    facility: "Family rooms",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 88,
    id: null,
    category: GENERAL,
    facility: "Non-smoking rooms",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 89,
    id: null,
    category: GENERAL,
    facility: "Outdoor swimming pool",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 90,
    id: null,
    category: GENERAL,
    facility: "Indoor swimming pool",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 91,
    id: null,
    category: GENERAL,
    facility: "Plunge pool",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 92,
    id: null,
    category: GENERAL,
    facility: "Spa",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 93,
    id: null,
    category: GENERAL,
    facility: "Open all year",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 94,
    id: null,
    category: GENERAL,
    facility: "Free pool/beach towels",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 95,
    id: null,
    category: GENERAL,
    facility: "Pool/beach towels (additional charge)",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 96,
    id: null,
    category: GENERAL,
    facility: "Sun loungers or beach chairs",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 97,
    id: null,
    category: GENERAL,
    facility: "Swim up bar",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 98,
    id: null,
    category: GENERAL,
    facility: "Pool Bar",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 99,
    id: null,
    category: GENERAL,
    facility: "Sun umbrellas",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 100,
    id: null,
    category: GENERAL,
    facility: "Hot tub/Jacuzzi",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 101,
    id: null,
    category: GENERAL,
    facility: "Non-smoking throughout",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 102,
    id: null,
    category: GENERAL,
    facility: "Wake up service",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 103,
    id: null,
    category: GENERAL,
    facility: "All ages welcome",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 104,
    id: null,
    category: GENERAL,
    facility: "Pool with view",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 105,
    id: null,
    category: GENERAL,
    facility: "Swimming pool toys",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 106,
    id: null,
    category: WELLNESS,
    facility: "Fitness area",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 107,
    id: null,
    category: WELLNESS,
    facility: "Yoga shala",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 108,
    id: null,
    category: WELLNESS,
    facility: "Fitness equipment",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 109,
    id: null,
    category: WELLNESS,
    facility: "Massage (additional charge)",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 110,
    id: null,
    category: WELLNESS,
    facility: "Massage",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 111,
    id: null,
    category: WELLNESS,
    facility: "Spa and wellness center (additional charge)",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 112,
    id: null,
    category: WELLNESS,
    facility: "Fitness locker rooms",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 113,
    id: null,
    category: WELLNESS,
    facility: "Yoga classes",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 114,
    id: null,
    category: WELLNESS,
    facility: "Fitness",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 115,
    id: null,
    category: WELLNESS,
    facility: "Couples massage (additional charge)",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 116,
    id: null,
    category: WELLNESS,
    facility: "Couples massage",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 117,
    id: null,
    category: WELLNESS,
    facility: "Spa/wellness packages (additional charge)",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 118,
    id: null,
    category: WELLNESS,
    facility: "Free spa facilities",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 119,
    id: null,
    category: WELLNESS,
    facility: "Free beauty Services",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 120,
    id: null,
    category: WELLNESS,
    facility: "Beauty Services (additional charge)",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 121,
    id: null,
    category: WELLNESS,
    facility: "Public Bath",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 122,
    id: null,
    category: WELLNESS,
    facility: "Public shower",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 123,
    id: null,
    category: WELLNESS,
    facility: "Open-air bath",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 124,
    id: null,
    category: WELLNESS,
    facility: "Massage",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 125,
    id: null,
    category: WELLNESS,
    facility: "Spa and wellness centre",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 126,
    id: null,
    category: WELLNESS,
    facility: "Fitness centre",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 127,
    id: null,
    category: WELLNESS,
    facility: "Gym",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 128,
    id: null,
    category: CLEANING_SERVICES,
    facility: "Daily housekeeping",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 129,
    id: null,
    category: CLEANING_SERVICES,
    facility: "Ironing service",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 130,
    id: null,
    category: CLEANING_SERVICES,
    facility: "Ironing service (additional charge)",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 131,
    id: null,
    category: CLEANING_SERVICES,
    facility: "Laundry",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 132,
    id: null,
    category: CLEANING_SERVICES,
    facility: "Laundry (additional charge)",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 133,
    id: null,
    category: BUSINESS_FACILITIES,
    facility: "Fax/photocopying (additional charge)",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 134,
    id: null,
    category: BUSINESS_FACILITIES,
    facility: "Fax/photocopying",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 135,
    id: null,
    category: BUSINESS_FACILITIES,
    facility: "Meeting/banquet facilities",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 136,
    id: null,
    category: ENTERTAINMENT,
    facility: "Kids' outdoor play equipment",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 137,
    id: null,
    category: ENTERTAINMENT,
    facility: "Indoor play area",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 138,
    id: null,
    category: ENTERTAINMENT,
    facility: "Board games/puzzles",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 139,
    id: null,
    category: ENTERTAINMENT,
    facility: "Board games/puzzles",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 140,
    id: null,
    category: ENTERTAINMENT,
    facility: "Babysitting/child services",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 141,
    id: null,
    category: ENTERTAINMENT,
    facility: "Babysitting/child services (additional charge)",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 142,
    id: null,
    category: ONSITE,
    facility: "Cash",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 143,
    id: null,
    category: ONSITE,
    facility: "Gcash",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 144,
    id: null,
    category: ONSITE,
    facility: "Visa",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 145,
    id: null,
    category: ONSITE,
    facility: "Mastercard",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 146,
    id: null,
    category: ONSITE,
    facility: "American Express",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 147,
    id: null,
    category: ONSITE,
    facility: "UnionPay",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 148,
    id: null,
    category: LANGUAGES,
    facility: "English",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 149,
    id: null,
    category: LANGUAGES,
    facility: "Filipino",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 150,
    id: null,
    category: LANGUAGES,
    facility: "Spanish",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 151,
    id: null,
    category: LANGUAGES,
    facility: "French",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 152,
    id: null,
    category: LANGUAGES,
    facility: "Chinese",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 153,
    id: null,
    category: LANGUAGES,
    facility: "Hebrew",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 154,
    id: null,
    category: LANGUAGES,
    facility: "German",
    propertyId: null,
    isSelected: false,
  },
]
