export const activities = [
  {
    _id: "1",
    host: {
      _id: "host1",
      role: "admin",
      isHost: true,
      guest: {
        _id: "guest1",
        firstName: "John",
        lastName: "Doe",
        language: "English",
        currency: "USD",
        country: "USA",
        address: {
          _id: "address1",
          createdAt: "2024-01-01T12:00:00Z",
          country: "USA",
          city: "New York",
          stateProvince: "NY",
          zipCode: 10001,
          streetAddress: "123 Main St",
          aptSuite: null,
          updatedAt: null,
        },
      },
    },
    title: "Siargao Surfing Adventure",
    activityType: ["Outdoor", "Water Sports"],
    experienceType: "Joiner",
    description:
      "Catch the best waves in Siargao with professional instructors.",
    highLights: ["Top surf spots", "Experienced guides", "All levels welcome"],
    durationHour: 3,
    durationMinute: 0,
    languages: ["English"],
    isFoodIncluded: false,
    includedFoods: [],
    isNonAlcoholicDrinkIncluded: true,
    isAlcoholicDrinkIncluded: false,
    includedAlcoholicDrinks: [],
    otherInclusion: ["Surfboard rental", "Instructor"],
    notIncluded: ["Travel insurance", "Transport to meeting point"],
    whatToBring: ["Swimwear", "Sunscreen"],
    notAllowed: ["Smoking", "Pets"],
    policies: ["Cancellations within 24 hours are non-refundable."],
    isSegmentBuilderEnabled: false,
    segments: [],
    meetingPoint: {
      _id: "location1",
      city: "General Luna",
      streetAddress: "Surf Point Road",
      barangay: "Poblacion",
      longitude: 126.1628,
      latitude: 9.8486,
      howToGetThere: "From the main town, follow signs to Surf Point.",
    },
    photos: [
      {
        _id: "photo1",
        key: "surfing1.jpg",
        thumbKey: "surfing1_thumb.jpg",
        isMain: true,
        description: "Surfing action shot",
        tags: "surfing",
      },
    ],
    slotCapacity: { minimum: 1, maximum: 10 },
    schedule: {
      monday: {
        slots: [
          {
            startTime: "08:00",
            endTime: "11:00",
            note: "Morning surfing session",
            slotIdsId: [],
          },
        ],
      },
      tuesday: null,
      wednesday: null,
      thursday: null,
      friday: null,
      saturday: null,
      sunday: null,
    },
    pricePerPerson: 50,
    pricePerSlot: null,
    daysCanCancel: 1,
    status: "Live", // Ensure this matches the `E_ListingStatus` enum
    finishedSections: ["description", "highLights", "photos"],
    pricePerDates: [
      {
        _id: "price1",
        fromDate: "2024-01-01",
        toDate: "2024-01-31",
        price: 50,
      },
    ],
    activityNote: null,
    average: 4.8,
    reviewsCount: 120,
  },
  {
    _id: "3",
    host: {
      _id: "host3",
      role: "host",
      isHost: true,
      guest: {
        _id: "guest3",
        firstName: "Liam",
        lastName: "Harrison",
        language: "English",
        currency: "AUD",
        country: "Australia",
        address: {
          _id: "address3",
          createdAt: "2024-01-02T08:00:00Z",
          country: "Australia",
          city: "Sydney",
          stateProvince: "NSW",
          zipCode: 2000,
          streetAddress: "789 Ocean View Rd",
          aptSuite: null,
          updatedAt: null,
        },
      },
    },
    title: "Mangrove Paddleboarding",
    activityType: ["Outdoor", "Water Sports"],
    experienceType: "Joiner",
    description:
      "Explore serene mangroves while paddleboarding in crystal-clear waters.",
    highLights: ["Serene mangroves", "Guided tours", "Suitable for beginners"],
    durationHour: 2,
    durationMinute: 30,
    languages: ["English"],
    isFoodIncluded: false,
    includedFoods: [],
    isNonAlcoholicDrinkIncluded: true,
    isAlcoholicDrinkIncluded: false,
    includedAlcoholicDrinks: [],
    otherInclusion: ["Paddleboard rental", "Instructor"],
    notIncluded: ["Transport to meeting point"],
    whatToBring: ["Sunscreen", "Hat"],
    notAllowed: ["Smoking"],
    policies: ["No refunds for cancellations within 12 hours."],
    isSegmentBuilderEnabled: false,
    segments: [],
    meetingPoint: {
      _id: "location3",
      city: "Del Carmen",
      streetAddress: "Mangrove Road",
      barangay: "San Benito",
      longitude: 126.0934,
      latitude: 9.8794,
      howToGetThere: "Meet at the Mangrove Tour Center on Mangrove Road.",
    },
    photos: [
      {
        _id: "photo3",
        key: "paddleboard1.jpg",
        thumbKey: "paddleboard1_thumb.jpg",
        isMain: true,
        description: "Paddleboarding through serene mangroves",
        tags: "paddleboarding",
      },
    ],
    slotCapacity: { minimum: 2, maximum: 12 },
    schedule: {
      friday: {
        slots: [
          {
            startTime: "08:30",
            endTime: "11:00",
            note: "Morning paddleboarding",
            slotIdsId: [],
          },
        ],
      },
    },
    pricePerPerson: 40,
    pricePerSlot: null,
    daysCanCancel: 1,
    status: "Incomplete",
    finishedSections: ["description", "highLights", "photos"],
    pricePerDates: [
      {
        _id: "price3",
        fromDate: "2024-03-01",
        toDate: "2024-03-15",
        price: 40,
      },
    ],
    activityNote: "Wear comfortable clothing and bring water.",
    average: 4.7,
    reviewsCount: 95,
  },
  {
    _id: "4",
    host: {
      _id: "host4",
      role: "host",
      isHost: true,
      guest: {
        _id: "guest4",
        firstName: "Sophia",
        lastName: "Garcia",
        language: "Spanish",
        currency: "EUR",
        country: "Spain",
        address: {
          _id: "address4",
          createdAt: "2024-01-03T10:00:00Z",
          country: "Spain",
          city: "Barcelona",
          stateProvince: "Catalonia",
          zipCode: 8080,
          streetAddress: "123 Sunset Blvd",
          aptSuite: "2B",
          updatedAt: null,
        },
      },
    },
    title: "Sunset Sailing Cruise",
    activityType: ["Outdoor", "Boat Tour"],
    experienceType: "Private",
    description: "Enjoy a relaxing sunset cruise with breathtaking views.",
    highLights: [
      "Romantic sunset",
      "Private sailing experience",
      "Refreshments included",
    ],
    durationHour: 3,
    durationMinute: 0,
    languages: ["English", "Spanish"],
    isFoodIncluded: true,
    includedFoods: ["Light snacks"],
    isNonAlcoholicDrinkIncluded: true,
    isAlcoholicDrinkIncluded: true,
    includedAlcoholicDrinks: ["Wine", "Beer"],
    otherInclusion: ["Private boat", "Captain"],
    notIncluded: [],
    whatToBring: ["Camera", "Jacket"],
    notAllowed: ["Large pets"],
    policies: ["Cancellations must be made at least 48 hours in advance."],
    isSegmentBuilderEnabled: true,
    segments: [],
    meetingPoint: {
      _id: "location4",
      city: "General Luna",
      streetAddress: "Marina Bay",
      barangay: "Catangnan",
      longitude: 126.162,
      latitude: 9.849,
      howToGetThere: "Meet at the main dock in Marina Bay.",
    },
    photos: [
      {
        _id: "photo4",
        key: "sailing1.jpg",
        thumbKey: "sailing1_thumb.jpg",
        isMain: true,
        description: "Boat cruising at sunset",
        tags: "sailing",
      },
    ],
    slotCapacity: { minimum: 1, maximum: 6 },
    schedule: {
      saturday: {
        slots: [
          {
            startTime: "17:00",
            endTime: "20:00",
            note: "Sunset sailing experience",
            slotIdsId: [],
          },
        ],
      },
    },
    pricePerPerson: 150,
    pricePerSlot: null,
    daysCanCancel: 2,
    status: "Live",
    finishedSections: ["description", "highLights", "photos"],
    pricePerDates: [
      {
        _id: "price4",
        fromDate: "2024-03-15",
        toDate: "2024-03-31",
        price: 150,
      },
    ],
    activityNote: "Perfect for couples and families.",
    average: 5.0,
    reviewsCount: 65,
  },
  {
    _id: "5",
    host: {
      _id: "host5",
      role: "guide",
      isHost: true,
      guest: {
        _id: "guest5",
        firstName: "Mia",
        lastName: "Johnson",
        language: "English",
        currency: "USD",
        country: "Canada",
        address: {
          _id: "address5",
          createdAt: "2024-01-04T15:00:00Z",
          country: "Canada",
          city: "Toronto",
          stateProvince: "ON",
          zipCode: 12345,
          streetAddress: "456 Maple Ave",
          aptSuite: "1A",
          updatedAt: null,
        },
      },
    },
    title: "Rainforest Trekking Adventure",
    activityType: ["Outdoor", "Hiking"],
    experienceType: "Joiner",
    description: "Discover the lush rainforest trails of Siargao Island.",
    highLights: [
      "Rainforest exploration",
      "Local wildlife",
      "Breathtaking views",
    ],
    durationHour: 4,
    durationMinute: 0,
    languages: ["English"],
    isFoodIncluded: false,
    includedFoods: [],
    isNonAlcoholicDrinkIncluded: true,
    isAlcoholicDrinkIncluded: false,
    includedAlcoholicDrinks: [],
    otherInclusion: ["Trekking guide", "Trail map"],
    notIncluded: ["Hiking gear"],
    whatToBring: ["Hiking boots", "Water bottle"],
    notAllowed: ["Smoking"],
    policies: ["Rain or shine, the trek proceeds unless severe weather."],
    isSegmentBuilderEnabled: false,
    segments: [],
    meetingPoint: {
      _id: "location5",
      city: "Santa Monica",
      streetAddress: "Trek Start Point",
      barangay: "Alegria",
      longitude: 126.1128,
      latitude: 9.8528,
      howToGetThere: "Start at the Rainforest Entry Point in Alegria.",
    },
    photos: [
      {
        _id: "photo5",
        key: "trekking1.jpg",
        thumbKey: "trekking1_thumb.jpg",
        isMain: true,
        description: "Hikers exploring rainforest trails",
        tags: "hiking",
      },
    ],
    slotCapacity: { minimum: 4, maximum: 20 },
    schedule: {
      sunday: {
        slots: [
          {
            startTime: "09:00",
            endTime: "13:00",
            note: "Morning trek",
            slotIdsId: [],
          },
        ],
      },
    },
    pricePerPerson: 60,
    pricePerSlot: null,
    daysCanCancel: 1,
    status: "Live",
    finishedSections: ["description", "highLights", "photos"],
    pricePerDates: [
      {
        _id: "price5",
        fromDate: "2024-03-01",
        toDate: "2024-03-31",
        price: 60,
      },
    ],
    activityNote: "Prepare for some steep climbs.",
    average: 4.6,
    reviewsCount: 120,
  },
  {
    _id: "6",
    host: {
      _id: "host6",
      role: "guide",
      isHost: true,
      guest: {
        _id: "guest6",
        firstName: "Ethan",
        lastName: "Brown",
        language: "English",
        currency: "USD",
        country: "USA",
        address: {
          _id: "address6",
          createdAt: "2024-01-05T08:00:00Z",
          country: "USA",
          city: "San Francisco",
          stateProvince: "CA",
          zipCode: 94103, // Changed to number
          streetAddress: "789 Bay Area Blvd",
          aptSuite: "10A",
          updatedAt: null,
        },
      },
    },
    title: "Cave Exploration",
    activityType: ["Outdoor", "Adventure"],
    experienceType: "Joiner",
    description: "Discover the hidden caves of Siargao with expert guides.",
    highLights: [
      "Stalactites and stalagmites",
      "Expert commentary",
      "Thrilling experience",
    ],
    durationHour: 3,
    durationMinute: 30,
    languages: ["English"],
    isFoodIncluded: false,
    includedFoods: [],
    isNonAlcoholicDrinkIncluded: true,
    isAlcoholicDrinkIncluded: false,
    includedAlcoholicDrinks: [],
    otherInclusion: ["Helmet", "Flashlight"],
    notIncluded: ["Transport to meeting point"],
    whatToBring: ["Sturdy shoes", "Water bottle"],
    notAllowed: ["Smoking", "Pets"],
    policies: ["Cancellations must be made 24 hours in advance."],
    isSegmentBuilderEnabled: false,
    segments: [],
    meetingPoint: {
      _id: "location6",
      city: "Pilar",
      streetAddress: "Cave Entrance",
      barangay: "San Roque",
      longitude: 126.0789,
      latitude: 9.869,
      howToGetThere: "Meet at the Cave Entrance in San Roque, Pilar.",
    },
    photos: [
      {
        _id: "photo6",
        key: "cave1.jpg",
        thumbKey: "cave1_thumb.jpg",
        isMain: true,
        description: "Explorers entering a cave",
        tags: "cave",
      },
    ],
    slotCapacity: { minimum: 4, maximum: 12 },
    schedule: {
      saturday: {
        slots: [
          {
            startTime: "10:00",
            endTime: "13:30",
            note: "Morning cave exploration",
            slotIdsId: [],
          },
        ],
      },
    },
    pricePerPerson: 75,
    pricePerSlot: null,
    daysCanCancel: 1,
    status: "Live",
    finishedSections: ["description", "highLights", "photos"],
    pricePerDates: [
      {
        _id: "price6",
        fromDate: "2024-04-01",
        toDate: "2024-04-30",
        price: 75,
      },
    ],
    activityNote: "Not recommended for claustrophobic individuals.",
    average: 4.8,
    reviewsCount: 90,
  },
  {
    _id: "7",
    host: {
      _id: "host7",
      role: "host",
      isHost: true,
      guest: {
        _id: "guest7",
        firstName: "Amelia",
        lastName: "Clark",
        language: "English",
        currency: "EUR",
        country: "UK",
        address: {
          _id: "address7",
          createdAt: "2024-01-06T10:00:00Z",
          country: "UK",
          city: "London",
          stateProvince: "Greater London",
          zipCode: 12345, // Changed to number
          streetAddress: "123 Abbey Road",
          aptSuite: "Flat 3",
          updatedAt: null,
        },
      },
    },
    title: "Cycling Through Rice Fields",
    activityType: ["Outdoor", "Cycling"],
    experienceType: "Joiner",
    description: "Enjoy a peaceful cycling tour through scenic rice fields.",
    highLights: ["Scenic views", "Relaxing ride", "Local guide insights"],
    durationHour: 2,
    durationMinute: 0,
    languages: ["English"],
    isFoodIncluded: false,
    includedFoods: [],
    isNonAlcoholicDrinkIncluded: false,
    isAlcoholicDrinkIncluded: false,
    includedAlcoholicDrinks: [],
    otherInclusion: ["Bicycle rental", "Helmet"],
    notIncluded: ["Snacks"],
    whatToBring: ["Comfortable clothes", "Water bottle"],
    notAllowed: ["Smoking"],
    policies: ["Tours proceed rain or shine."],
    isSegmentBuilderEnabled: false,
    segments: [],
    meetingPoint: {
      _id: "location7",
      city: "Santa Monica",
      streetAddress: "Cycling Trail Entrance",
      barangay: "Alegria",
      longitude: 126.1132,
      latitude: 9.8535,
      howToGetThere: "Meet at the cycling trailhead in Alegria.",
    },
    photos: [
      {
        _id: "photo7",
        key: "cycling1.jpg",
        thumbKey: "cycling1_thumb.jpg",
        isMain: true,
        description: "Cyclists enjoying a rice field trail",
        tags: "cycling",
      },
    ],
    slotCapacity: { minimum: 2, maximum: 10 },
    schedule: {
      sunday: {
        slots: [
          {
            startTime: "08:00",
            endTime: "10:00",
            note: "Morning cycling tour",
            slotIdsId: [],
          },
        ],
      },
    },
    pricePerPerson: 30,
    pricePerSlot: null,
    daysCanCancel: 1,
    status: "Live",
    finishedSections: ["description", "highLights", "photos"],
    pricePerDates: [
      {
        _id: "price7",
        fromDate: "2024-04-01",
        toDate: "2024-04-30",
        price: 30,
      },
    ],
    activityNote: "Bring a hat to shield from the sun.",
    average: 4.5,
    reviewsCount: 85,
  },
  {
    _id: "8",
    host: {
      _id: "host8",
      role: "host",
      isHost: true,
      guest: {
        _id: "guest8",
        firstName: "Oliver",
        lastName: "Martinez",
        language: "Spanish",
        currency: "EUR",
        country: "Spain",
        address: {
          _id: "address8",
          createdAt: "2024-01-07T12:00:00Z",
          country: "Spain",
          city: "Madrid",
          stateProvince: "Community of Madrid",
          zipCode: 28001, // Changed to number
          streetAddress: "456 Madrid Way",
          aptSuite: "Suite 12",
          updatedAt: null,
        },
      },
    },
    title: "Snorkeling Adventure",
    activityType: ["Outdoor", "Water Sports"],
    experienceType: "Joiner",
    description:
      "Explore vibrant coral reefs and marine life through snorkeling.",
    highLights: [
      "Vivid coral reefs",
      "Guided snorkeling",
      "All equipment included",
    ],
    durationHour: 2,
    durationMinute: 0,
    languages: ["English", "Spanish"],
    isFoodIncluded: false,
    includedFoods: [],
    isNonAlcoholicDrinkIncluded: true,
    isAlcoholicDrinkIncluded: false,
    includedAlcoholicDrinks: [],
    otherInclusion: ["Snorkeling gear", "Guide"],
    notIncluded: ["Transport to meeting point"],
    whatToBring: ["Swimsuit", "Towel"],
    notAllowed: ["Pets"],
    policies: ["Refunds available for cancellations made 24 hours in advance."],
    isSegmentBuilderEnabled: false,
    segments: [],
    meetingPoint: {
      _id: "location8",
      city: "General Luna",
      streetAddress: "Beach Access",
      barangay: "Poblacion",
      longitude: 126.162,
      latitude: 9.8486,
      howToGetThere: "Meet at the beach access point in General Luna.",
    },
    photos: [
      {
        _id: "photo8",
        key: "snorkeling1.jpg",
        thumbKey: "snorkeling1_thumb.jpg",
        isMain: true,
        description: "Snorkeling in vibrant coral reefs",
        tags: "snorkeling",
      },
    ],
    slotCapacity: { minimum: 3, maximum: 15 },
    schedule: {
      tuesday: {
        slots: [
          {
            startTime: "09:30",
            endTime: "11:30",
            note: "Morning snorkeling session",
            slotIdsId: [],
          },
        ],
      },
    },
    pricePerPerson: 45,
    pricePerSlot: null,
    daysCanCancel: 1,
    status: "Live",
    finishedSections: ["description", "highLights", "photos"],
    pricePerDates: [
      {
        _id: "price8",
        fromDate: "2024-05-01",
        toDate: "2024-05-31",
        price: 45,
      },
    ],
    activityNote: "Ideal for beginners and experienced snorkelers.",
    average: 4.7,
    reviewsCount: 110,
  },
]
