import { HOST } from "@/common/constants"
import { APP_NAME } from "@repo/constants"
import { Metadata } from "next"
import AuthGuard from "@/common/components/AuthGuard"
import ListingReviews from "@/module/Hosting/Listings/Properties/Property/Reviews"

export const metadata: Metadata = {
  title: `${HOST} - ${APP_NAME}`,
  description: `Generated by ${APP_NAME}`,
}

const ListingPhotosPage = () => {
  return (
    <AuthGuard>
      <ListingReviews />
    </AuthGuard>
  )
}

export default ListingPhotosPage
