import LandingPage from "@/module/landing-page"
import { APP_NAME } from "@repo/constants"
import { Metadata } from "next"
import { HOME } from "@/common/constants"

export const metadata: Metadata = {
  title: `${HOME} - ${APP_NAME}`,
  description: `Generated by ${APP_NAME}`,
}

const HomePage = () => {
  return <LandingPage />
}

export default HomePage
