import LandingPage from "@/module/landing-page"
import { APP_NAME } from "@repo/constants"
import { Metadata } from "next"
import { HOME } from "@/common/constants"
import { cookies } from "next/headers"

export const metadata: Metadata = {
  title: `${HOME} - ${APP_NAME}`,
  description: `Generated by ${APP_NAME}`,
}

const HomePage = async () => {
  // const cookieStore = cookies();
  // const clientCookie = cookieStore.get("ess")?.value;
  // const response = await fetch("http://localhost:3000/api/v1/users/test", {
  //   method: "GET",
  //   headers: {
  //     cookie: clientCookie ? `cookieName=${clientCookie}` : "",
  //   },
  //   credentials: "include",
  // });
  // const data = await response.json();
  // console.log("client", data)
  return <LandingPage />
}

export default HomePage
