import { HOST } from "@/common/constants"
import { APP_NAME } from "@repo/constants"
import { Metadata } from "next"
import HostingReservation from "@/module/Hosting/Reservations/Reservation"
import AuthGuard from "@/common/components/AuthGuard"

export const metadata: Metadata = {
  title: `${HOST} - ${APP_NAME}`,
  description: `Generated by ${APP_NAME}`,
}

const HostingReservationPage = () => {
  return (
    <AuthGuard>
      {/* CONNECT RESERVATION TO BACKEND
      CREATE SAMPLE UI FOR PAYMENT HISTORY */}
      <HostingReservation />
    </AuthGuard>
  )
}

export default HostingReservationPage
