export const MUNICIPALITIES = [
  { name: "Burgos" },
  { name: "Dapa" },
  { name: "Del Carmen" },
  { name: "General Luna" },
  { name: "Pilar" },
  { name: "Santa Monica" },
  { name: "San Benito" },
  { name: "San Isidro" },
  { name: "Socorro" },
]

export const BARANGAYS = [
  { name: "Purok 1", municipality: "Dapa" },
  { name: "Purok 1", municipality: "General Luna" },
  { name: "Purok 1", municipality: "Burgos" },
  { name: "Purok 2", municipality: "Dapa" },
  { name: "Purok 2", municipality: "General Luna" },
  { name: "Purok 2", municipality: "Burgos" },
  { name: "Purok 3", municipality: "Dapa" },
  { name: "Purok 3", municipality: "General Luna" },
  { name: "Purok 4", municipality: "Dapa" },
  { name: "Purok 4", municipality: "General Luna" },
  { name: "Purok 5", municipality: "Dapa" },
  { name: "Purok 5", municipality: "General Luna" },
  { name: "Purok 6", municipality: "Dapa" },
  { name: "Purok 7", municipality: "Dapa" },
  { name: "Purok 8", municipality: "Dapa" },
  { name: "Purok 9", municipality: "Dapa" },
  { name: "Purok 9", municipality: "Dapa" },
  { name: "Purok 10", municipality: "Dapa" },
  { name: "Purok 11", municipality: "Dapa" },
  { name: "Purok 12", municipality: "Dapa" },
  { name: "Purok 13", municipality: "Dapa" },
  { name: "Bangkay", municipality: "Dapa" },
  { name: "Buenavista", municipality: "Dapa" },
  { name: "Cabawa", municipality: "Dapa" },
  { name: "Cambas-ac", municipality: "Dapa" },
  { name: "Consolacion", municipality: "Dapa" },
  { name: "Corregidor", municipality: "Dapa" },
  { name: "Dagohoy", municipality: "Dapa" },
  { name: "Don Paulino", municipality: "Dapa" },
  { name: "Jubang", municipality: "Dapa" },
  { name: "Montserrat", municipality: "Dapa" },
  { name: "Osmeña", municipality: "Dapa" },
  { name: "San Carlos", municipality: "Dapa" },
  { name: "San Miguel", municipality: "Dapa" },
  { name: "Santa Fe", municipality: "Dapa" },
  { name: "Santa Filomena", municipality: "Dapa" },
  { name: "Union", municipality: "Dapa" },
  { name: "Baybay", municipality: "Burgos" },
  { name: "Bitaug", municipality: "Burgos" },
  { name: "Matin-ao", municipality: "Burgos" },
  { name: "San Mateo", municipality: "Burgos" },
  { name: "Antipolo", municipality: "Del Carmen" },
  { name: "Alburo", municipality: "Del Carmen" },
  { name: "Bagakay", municipality: "Del Carmen" },
  { name: "Bitoon", municipality: "Del Carmen" },
  { name: "Cabugao", municipality: "Del Carmen" },
  { name: "Cancohoy", municipality: "Del Carmen" },
  { name: "Caub", municipality: "Del Carmen" },
  { name: "Del Carmen", municipality: "Del Carmen" },
  { name: "Poblacion", municipality: "Del Carmen" },
  { name: "Domoyog", municipality: "Del Carmen" },
  { name: "Esperanza", municipality: "Del Carmen" },
  { name: "Halian", municipality: "Del Carmen" },
  { name: "Jamoyaon", municipality: "Del Carmen" },
  { name: "Katipunan", municipality: "Del Carmen" },
  { name: "Lobogon", municipality: "Del Carmen" },
  { name: "Mabuhay", municipality: "Del Carmen" },
  { name: "Mahayahay", municipality: "Del Carmen" },
  { name: "Quezon", municipality: "Del Carmen" },
  { name: "San Fernando", municipality: "Del Carmen" },
  { name: "San Jose", municipality: "Del Carmen" },
  { name: "Sayak", municipality: "Del Carmen" },
  { name: "Tuboran", municipality: "Del Carmen" },
  { name: "Anajawan", municipality: "General Luna" },
  { name: "Cabitoonan", municipality: "General Luna" },
  { name: "Catangnan", municipality: "General Luna" },
  { name: "Consuelo", municipality: "General Luna" },
  { name: "Corazon", municipality: "General Luna" },
  { name: "Daku", municipality: "General Luna" },
  { name: "La Januza", municipality: "General Luna" },
  { name: "Libertad", municipality: "General Luna" },
  { name: "Magsaysay", municipality: "General Luna" },
  { name: "Malinao", municipality: "General Luna" },
  { name: "Santa Cruz", municipality: "General Luna" },
  { name: "Santa Fe", municipality: "General Luna" },
  { name: "Suyangan", municipality: "General Luna" },
  { name: "Tawin-tawin", municipality: "General Luna" },
  { name: "Asinan", municipality: "Pilar" },
  { name: "Caridad", municipality: "Pilar" },
  { name: "Centro", municipality: "Pilar" },
  { name: "Consolacion", municipality: "Pilar" },
  { name: "Datu", municipality: "Pilar" },
  { name: "Dayaohay", municipality: "Pilar" },
  { name: "Jaboy", municipality: "Pilar" },
  { name: "Katipunan", municipality: "Pilar" },
  { name: "Maasin", municipality: "Pilar" },
  { name: "Mabini", municipality: "Pilar" },
  { name: "Mabuhay", municipality: "Pilar" },
  { name: "Pilaring", municipality: "Pilar" },
  { name: "Punta", municipality: "Pilar" },
  { name: "Salvacion", municipality: "Pilar" },
  { name: "San Roque", municipality: "Pilar" },
  { name: "Abad Santos", municipality: "Santa Monica" },
  { name: "Alegria", municipality: "Santa Monica" },
  { name: "Bailan", municipality: "Santa Monica" },
  { name: "Garcia", municipality: "Santa Monica" },
  { name: "Libertad", municipality: "Santa Monica" },
  { name: "Mabini", municipality: "Santa Monica" },
  { name: "Mabuhay", municipality: "Santa Monica" },
  { name: "Poblacion", municipality: "Santa Monica" },
  { name: "Magsaysay", municipality: "Santa Monica" },
  { name: "Rizal", municipality: "Santa Monica" },
  { name: "T. Arlan", municipality: "Santa Monica" },
  { name: "Tangbo", municipality: "Santa Monica" },
  { name: "Bongdo", municipality: "San Benito" },
  { name: "Maribojoc", municipality: "San Benito" },
  { name: "Nuevo Campo", municipality: "San Benito" },
  { name: "San Juan", municipality: "San Benito" },
  { name: "Santa Cruz", municipality: "San Benito" },
  { name: "Talisay", municipality: "San Benito" },
  { name: "Poblacion", municipality: "San Benito" },
  { name: "Buhing Calipay", municipality: "San Isidro" },
  { name: "Del Carmen", municipality: "San Isidro" },
  { name: "Poblacion", municipality: "San Isidro" },
  { name: "Del Pilar", municipality: "San Isidro" },
  { name: "Macapagal", municipality: "San Isidro" },
  { name: "Pacifico", municipality: "San Isidro" },
  { name: "Pelaez", municipality: "San Isidro" },
  { name: "Roxas", municipality: "San Isidro" },
  { name: "San Miguel", municipality: "San Isidro" },
  { name: "Santa Paz", municipality: "San Isidro" },
  { name: "Santo Niño", municipality: "San Isidro" },
  { name: "Tambacan", municipality: "San Isidro" },
  { name: "Tigasao", municipality: "San Isidro" },
  { name: "Albino Taruc", municipality: "Socorro" },
  { name: "Doña Helene", municipality: "Socorro" },
  { name: "Honrado", municipality: "Socorro" },
  { name: "Navarro", municipality: "Socorro" },
  { name: "Nueva Estrella", municipality: "Socorro" },
  { name: "Pamosaingan", municipality: "Socorro" },
  { name: "Rizal", municipality: "Socorro" },
  { name: "Poblacion", municipality: "Socorro" },
  { name: "Salog", municipality: "Socorro" },
  { name: "San Roque", municipality: "Socorro" },
  { name: "Santa Cruz", municipality: "Socorro" },
  { name: "Sering", municipality: "Socorro" },
  { name: "Songkoy", municipality: "Socorro" },
  { name: "Sudlon", municipality: "Socorro" },
]
