import type { Metadata } from "next"

import "@/app/globals.css"
import QueryClientWrapper from "@/common/components/QueryClientWrapper"
import GlobalModalWrapper from "@/common/components/GlobalModalWrapper"
import { Toaster } from "react-hot-toast"
import React from "react"
import { LOGO_SINGLE_IMAGE } from "@/common/constants/index"
import { APP_NAME } from "@repo/constants"
import Header from "@/common/components/HostLayout/ListingActivityHeader"
import ListingSidebar from "@/common/components/HostLayout/ListingSidebar"
import AuthStateProvider from "@/common/components/AuthStateProvider"
import { E_Listing_Category } from "@repo/contract"

export const metadata: Metadata = {
  title: APP_NAME,
  description: `Generated by ${APP_NAME}`,
}

export default async function HostListingActivityLayout({
  children,
}: {
  readonly children: React.ReactNode
}) {
  return (
    <html lang="en">
      <link rel="icon" type="image/x-icon" href={LOGO_SINGLE_IMAGE} />
      <body>
        <Toaster />
        <QueryClientWrapper>
          <AuthStateProvider>
            <GlobalModalWrapper>
              <Header />
              <ListingSidebar category={E_Listing_Category.Activity}>{children}</ListingSidebar>
            </GlobalModalWrapper>
          </AuthStateProvider>
        </QueryClientWrapper>
      </body>
    </html>
  )
}
