import { HOST } from "@/common/constants"
import { APP_NAME } from "@repo/constants"
import { Metadata } from "next"
import AuthGuard from "@/common/components/AuthGuard"
import ActivitySingleView from "@/module/Listing/Activity"

export const metadata: Metadata = {
  title: `${HOST} - ${APP_NAME}`,
  description: `Generated by ${APP_NAME}`,
}

const ListingPage = () => {
  return (
    <AuthGuard>
      <ActivitySingleView />
    </AuthGuard>
  ) 
}

export default ListingPage
