import AuthGuard from "@/common/components/AuthGuard"
import { PAYMENT_HISTORY } from "@/common/constants"
import TableTab from "@/module/Hosting/PaymentHistory/TableTab"

import { APP_NAME } from "@repo/constants"
import { Metadata } from "next"

export const metadata: Metadata = {
  title: `${PAYMENT_HISTORY} - ${APP_NAME}`,
  description: `Generated by ${APP_NAME}`,
}

const TablePage = () => {
  return (
    <AuthGuard>
      <TableTab />
    </AuthGuard>
  )
}

export default TablePage
