import type { Metadata } from "next"

import QueryClientWrapper from "@/common/components/QueryClientWrapper"
import { Toaster } from "react-hot-toast"
import React from "react"
import { LOGO_SINGLE_IMAGE } from "@/common/constants/index"
import { APP_NAME } from "@repo/constants"
import GlobalModalWrapper from "@/common/components/GlobalModalWrapper"
import "@/app/globals.css"

export const metadata: Metadata = {
  title: APP_NAME,
  description: `Generated by ${APP_NAME}`,
}

export default async function LayoutWrapper({
  children,
}: {
  readonly children: React.ReactNode
}) {
  return (
    <html lang="en">
      <link rel="icon" type="image/x-icon" href={LOGO_SINGLE_IMAGE} />
      <body>
        <Toaster />
        <QueryClientWrapper>
          <GlobalModalWrapper>{children}</GlobalModalWrapper>
        </QueryClientWrapper>
      </body>
    </html>
  )
}
