import { HOST } from "@/common/constants"
import { APP_NAME } from "@repo/constants"
import { Metadata } from "next"
import HostingTodayPending from "@/module/Hosting/Today/Pending"
import AuthGuard from "@/common/components/AuthGuard"

export const metadata: Metadata = {
  title: `${HOST} - ${APP_NAME}`,
  description: `Generated by ${APP_NAME}`,
}

const HostingTodayPendingPage = () => {
  return (
    <AuthGuard>
      <HostingTodayPending />
    </AuthGuard>
  )
}

export default HostingTodayPendingPage
