const MOST_POPULAR = "Most Popular"
const OUTDOORS = "Outdoors"
const GENERAL = "General"
const BATHROOM = "Bathroom"
const KITCHEN = "Kitchen"
const LIVING_AREA = "Living Area"

export const AMENITIES = [
  {
    index: 0,
    category: MOST_POPULAR,
    amenity: "Bar",
    isSelected: false,
  },
  {
    index: 1,
    category: MOST_POPULAR,
    amenity: "Sauna",
    isSelected: false,
  },
  {
    index: 2,
    category: MOST_POPULAR,
    amenity: "Garden",
    isSelected: false,
  },
  {
    index: 3,
    category: MOST_POPULAR,
    amenity: "Terrace",
    isSelected: false,
  },
  {
    index: 4,
    category: MOST_POPULAR,
    amenity: "Hot tub/Jacuzzi",
    isSelected: false,
  },
  {
    index: 5,
    category: MOST_POPULAR,
    amenity: "Heating",
    isSelected: false,
  },
  {
    index: 6,
    category: MOST_POPULAR,
    amenity: "Free WiFi",
    isSelected: false,
  },
  {
    index: 7,
    category: MOST_POPULAR,
    amenity: "Air conditioning",
    isSelected: false,
  },
  {
    index: 8,
    category: MOST_POPULAR,
    amenity: "Swimming pool",
    isSelected: false,
  },
  {
    index: 9,
    category: MOST_POPULAR,
    amenity: "Beach",
    isSelected: false,
  },
  {
    index: 10,
    category: BATHROOM,
    amenity: "Free toiletries",
    isSelected: false,
  },
  {
    index: 11,
    category: BATHROOM,
    amenity: "Bidet",
    isSelected: false,
  },
  {
    index: 12,
    category: BATHROOM,
    amenity: "Toilet",
    isSelected: false,
  },
  {
    index: 13,
    category: BATHROOM,
    amenity: "Bath or shower",
    isSelected: false,
  },
  {
    index: 14,
    category: BATHROOM,
    amenity: "Towels",
    isSelected: false,
  },
  {
    index: 15,
    category: BATHROOM,
    amenity: "Linen",
    isSelected: false,
  },
  {
    index: 16,
    category: BATHROOM,
    amenity: "Tile/marble floor",
    isSelected: false,
  },
  {
    index: 17,
    category: BATHROOM,
    amenity: "Bathrobe",
    isSelected: false,
  },
  {
    index: 18,
    category: BATHROOM,
    amenity: "Toilet paper",
    isSelected: false,
  },
  {
    index: 19,
    category: BATHROOM,
    amenity: "Hairdryer",
    isSelected: false,
  },
  {
    index: 20,
    category: BATHROOM,
    amenity: "Hand sanitiser",
    isSelected: false,
  },
  {
    index: 21,
    category: BATHROOM,
    amenity: "Spa bath",
    isSelected: false,
  },
  {
    index: 22,
    category: OUTDOORS,
    amenity: "Beachfront",
    isSelected: false,
  },
  {
    index: 23,
    category: KITCHEN,
    amenity: "Tea/Coffee maker",
    isSelected: false,
  },
  {
    index: 24,
    category: KITCHEN,
    amenity: "Microwave",
    isSelected: false,
  },
  {
    index: 25,
    category: KITCHEN,
    amenity: "Kitchenware",
    isSelected: false,
  },
  {
    index: 26,
    category: KITCHEN,
    amenity: "Hot/cold water dispenser",
    isSelected: false,
  },
  {
    index: 27,
    category: KITCHEN,
    amenity: "Electric kettle",
    isSelected: false,
  },
  {
    index: 28,
    category: KITCHEN,
    amenity: "Stovetop",
    isSelected: false,
  },
  {
    index: 29,
    category: KITCHEN,
    amenity: "Dining area",
    isSelected: false,
  },
  {
    index: 30,
    category: KITCHEN,
    amenity: "Dining table",
    isSelected: false,
  },
  {
    index: 31,
    category: KITCHEN,
    amenity: "Coffee machine",
    isSelected: false,
  },
  {
    index: 32,
    category: KITCHEN,
    amenity: "Minibar",
    isSelected: false,
  },
  {
    index: 33,
    category: KITCHEN,
    amenity: "Kitchenette",
    isSelected: false,
  },
  {
    index: 34,
    category: LIVING_AREA,
    amenity: "Seating Area",
    isSelected: false,
  },
  {
    index: 35,
    category: LIVING_AREA,
    amenity: "Sofa bed",
    isSelected: false,
  },
  {
    index: 36,
    category: LIVING_AREA,
    amenity: "Hardwood or parquet floors",
    isSelected: false,
  },
  {
    index: 37,
    category: LIVING_AREA,
    amenity: "Wardrobe or closet",
    isSelected: false,
  },
  {
    index: 38,
    category: LIVING_AREA,
    amenity: "Clothes rack",
    isSelected: false,
  },
  {
    index: 39,
    category: LIVING_AREA,
    amenity: "iPod dock",
    isSelected: false,
  },
  {
    index: 40,
    category: LIVING_AREA,
    amenity: "Dressing room",
    isSelected: false,
  },
  {
    index: 41,
    category: LIVING_AREA,
    amenity: "Board games/puzzles",
    isSelected: false,
  },
  {
    index: 42,
    category: LIVING_AREA,
    amenity: "Books, DVDs, or music for children",
    isSelected: false,
  },
  {
    index: 43,
    category: LIVING_AREA,
    amenity: "Balcony",
    isSelected: false,
  },
  {
    index: 44,
    category: LIVING_AREA,
    amenity: "Terrace",
    isSelected: false,
  },
  {
    index: 45,
    category: LIVING_AREA,
    amenity: "View",
    isSelected: false,
  },
  {
    index: 46,
    category: LIVING_AREA,
    amenity: "Garden view",
    isSelected: false,
  },
  {
    index: 47,
    category: LIVING_AREA,
    amenity: "Pool view",
    isSelected: false,
  },
  {
    index: 48,
    category: GENERAL,
    amenity: "Designated smoking area",
    isSelected: false,
  },
  {
    index: 49,
    category: GENERAL,
    amenity: "Air conditioning",
    isSelected: false,
  },
  {
    index: 50,
    category: GENERAL,
    amenity: "Soundproof rooms",
    isSelected: false,
  },
  {
    index: 51,
    category: GENERAL,
    amenity: "Family rooms",
    isSelected: false,
  },
  {
    index: 52,
    category: GENERAL,
    amenity: "Non-smoking rooms",
    isSelected: false,
  },
  {
    index: 53,
    category: GENERAL,
    amenity: "Outdoor swimming pool",
    isSelected: false,
  },
  {
    index: 54,
    category: GENERAL,
    amenity: "Indoor swimming pool",
    isSelected: false,
  },
  {
    index: 55,
    category: GENERAL,
    amenity: "Plunge pool",
    isSelected: false,
  },
  {
    index: 56,
    category: GENERAL,
    amenity: "Spa",
    isSelected: false,
  },
  {
    index: 57,
    category: GENERAL,
    amenity: "Open all year",
    isSelected: false,
  },
  {
    index: 58,
    category: GENERAL,
    amenity: "Free pool/beach towels",
    isSelected: false,
  },
  {
    index: 59,
    category: GENERAL,
    amenity: "Pool/beach towels (additional charge)",
    isSelected: false,
  },
  {
    index: 60,
    category: GENERAL,
    amenity: "Sun loungers or beach chairs",
    isSelected: false,
  },
  {
    index: 61,
    category: GENERAL,
    amenity: "Swim up bar",
    isSelected: false,
  },
  {
    index: 62,
    category: GENERAL,
    amenity: "Pool Bar",
    isSelected: false,
  },
  {
    index: 63,
    category: GENERAL,
    amenity: "Sun umbrellas",
    isSelected: false,
  },
  {
    index: 64,
    category: GENERAL,
    amenity: "Hot tub/Jacuzzi",
    isSelected: false,
  },
  {
    index: 65,
    category: GENERAL,
    amenity: "Non-smoking throughout",
    isSelected: false,
  },
  {
    index: 66,
    category: GENERAL,
    amenity: "Wake up service",
    isSelected: false,
  },
  {
    index: 67,
    category: GENERAL,
    amenity: "All ages welcome",
    isSelected: false,
  },
  {
    index: 68,
    category: GENERAL,
    amenity: "Pool with view",
    isSelected: false,
  },
  {
    index: 69,
    category: OUTDOORS,
    amenity: "Outdoor furniture",
    isSelected: false,
  },
  {
    index: 70,
    category: OUTDOORS,
    amenity: "Sun terrace",
    isSelected: false,
  },
  {
    index: 71,
    category: OUTDOORS,
    amenity: "Private beach area",
    isSelected: false,
  },
  {
    index: 72,
    category: OUTDOORS,
    amenity: "BBQ facilities",
    isSelected: false,
  },
  {
    index: 73,
    category: OUTDOORS,
    amenity: "Parking",
    isSelected: false,
  },
  {
    index: 74,
    category: OUTDOORS,
    amenity: "Shared kitchen",
    isSelected: false,
  },
  {
    index: 75,
    category: OUTDOORS,
    amenity: "Smoking area",
    isSelected: false,
  },
  {
    index: 76,
    category: OUTDOORS,
    amenity: "Garden",
    isSelected: false,
  },
  {
    index: 77,
    category: OUTDOORS,
    amenity: "Common area",
    isSelected: false,
  },
]
