import { HOST } from "@/common/constants"
import { APP_NAME } from "@repo/constants"
import { Metadata } from "next"
import AuthGuard from "@/common/components/AuthGuard"
import ReservationCalendar from "@/module/Hosting/Reservations/Calendar"
import ActivitiesReservationCalendar from "@/module/Hosting/Reservations/Calendar/activities"

export const metadata: Metadata = {
  title: `${HOST} - ${APP_NAME}`,
  description: `Generated by ${APP_NAME}`,
}

const HostingActivitesReservationCalendarPage = () => {
  return (
    <AuthGuard>
      <ActivitiesReservationCalendar />
    </AuthGuard>
  )
}

export default HostingActivitesReservationCalendarPage
