import { HOST } from "@/common/constants"
import { APP_NAME } from "@repo/constants"
import { Metadata } from "next"
import AuthGuard from "@/common/components/AuthGuard"
import ListingLocation from "@/module/Hosting/Listings/Properties/Property/Location"

export const metadata: Metadata = {
  title: `${HOST} - ${APP_NAME}`,
  description: `Generated by ${APP_NAME}`,
}

const ListingBasicInfoPage = () => {
  return (
    <AuthGuard>
      <ListingLocation pageType="edit" />
    </AuthGuard>
  )
}

export default ListingBasicInfoPage
