import { HOST } from "@/common/constants"
import { APP_NAME } from "@repo/constants"
import { Metadata } from "next"
import AuthGuard from "@/common/components/AuthGuard"
import Summary from "@/module/Hosting/Listings/Properties/Property/Summary"

export const metadata: Metadata = {
  title: `${HOST} - ${APP_NAME}`,
  description: `Generated by ${APP_NAME}`,
}

const SummaryPage = () => {
  return (
    <AuthGuard>
      <Summary />
    </AuthGuard>
  )
}

export default SummaryPage
