import { HOST } from "@/common/constants"
import { APP_NAME } from "@repo/constants"
import { Metadata } from "next"
import AuthGuard from "@/common/components/AuthGuard"
import RentalSummary from "@/module/Admin/Listings/Declined/Rental/Summary"

export const metadata: Metadata = {
  title: `${HOST} - ${APP_NAME}`,
  description: `Generated by ${APP_NAME}`,
}

const SummaryPage = () => {
  return (
    <AuthGuard>
      <RentalSummary />
    </AuthGuard>
  )
}

export default SummaryPage
