import { HOST } from "@/common/constants"
import { APP_NAME } from "@repo/constants"
import { Metadata } from "next"
import HostingReservationsCanceled from "@/module/Hosting/Reservations/Canceled"
import AuthGuard from "@/common/components/AuthGuard"

export const metadata: Metadata = {
  title: `${HOST} - ${APP_NAME}`,
  description: `Generated by ${APP_NAME}`,
}

const HostingReservationsCanceledPage = () => {
  return (
    <AuthGuard>
      <HostingReservationsCanceled />
    </AuthGuard>
  )
}

export default HostingReservationsCanceledPage
