import { HOST } from "@/common/constants"
import { APP_NAME } from "@repo/constants"
import { Metadata } from "next"
import AuthGuard from "@/common/components/AuthGuard"
import Bed from "@/module/Hosting/Listings/Properties/Property/Units/Add/Bed"

export const metadata: Metadata = {
  title: `${HOST} - ${APP_NAME}`,
  description: `Generated by ${APP_NAME}`,
}

const AddBedUnitPage = () => {
  return (
    <AuthGuard>
      <Bed />
    </AuthGuard>
  )
}

export default AddBedUnitPage
