import {
  E_Property_Type,
  E_Whole_Place_Property_Type,
} from "@repo/contract-2/property"

export const placesToStay = [
  {
    listingId: "1",
    type: E_Property_Type.WHOLE_PLACE,
    wholeplaceType: E_Whole_Place_Property_Type.COTTAGE, // Valid value from the enum
    location: {
      _id: "loc1",
      city: "Burgos",
      streetAddress: "Tourism Road",
      barangay: "Poblacion",
      longitude: 126.1628,
      latitude: 9.8486,
      howToGetThere:
        "From Siargao Airport, take a tricycle or van to General Luna. The cottage is located along Tourism Road.",
      createdAt: "2024-01-01T08:00:00Z",
      updatedAt: null,
      deletedAt: null,
    },
    title: "Andal Resort",
    subtitle: "Relax and enjoy the tropical vibes of Siargao",
    photos: [
      {
        _id: "photo1",
        bookableUnitId: null,
        propertyId: "1",
        rentalId: null,
        activityId: null,
        key: "3b5b949c-9e49-435e-90d8-e4d44c382762",
        thumbKey: "3b5b949c-9e49-435e-90d8-e4d44c382762",
        isMain: true,
        description: "Exterior view of the cozy beach cottage",
        tags: "beach",
        createdAt: "2024-01-10T10:00:00Z",
        updatedAt: null,
        deletedAt: null,
      },
    ],
    average: 3.7,
    reviewsCount: 2,
    price: 5,
  },
  {
    listingId: "2",
    type: E_Property_Type.WHOLE_PLACE,
    wholeplaceType: E_Whole_Place_Property_Type.HOUSE, // Valid value from the enum
    location: {
      _id: "loc2",
      city: "Burgos",
      streetAddress: "Cloud 9 Road",
      barangay: "Sugba",
      longitude: 126.0758,
      latitude: 9.8721,
      howToGetThere:
        "From Siargao Airport, head towards Del Carmen and follow signs to Sugba Lagoon.",
      createdAt: "2024-01-05T08:00:00Z",
      updatedAt: null,
      deletedAt: null,
    },
    title: "Andal Resort",
    subtitle: "Bed in 2 person dorm",
    photos: [
      {
        _id: "photo3",
        bookableUnitId: null,
        propertyId: "2",
        rentalId: null,
        activityId: null,
        key: "f78619c8-c2ec-40e6-aee8-c1ab79ace165",
        thumbKey: "f78619c8-c2ec-40e6-aee8-c1ab79ace165",
        isMain: true,
        description: "Modern house with a spacious garden",
        tags: "house",
        createdAt: "2024-01-12T10:00:00Z",
        updatedAt: null,
        deletedAt: null,
      },
    ],
    price: 3000,
    average: 0,
    reviewsCount: 0,
  },
  {
    listingId: "3",
    type: E_Property_Type.WHOLE_PLACE,
    wholeplaceType: E_Whole_Place_Property_Type.VILLA, // Valid value from the enum
    location: {
      _id: "loc3",
      city: "Pilar",
      streetAddress: "Pilar Coastal Road",
      barangay: "San Roque",
      longitude: 126.0822,
      latitude: 9.8718,
      howToGetThere:
        "Take the main road to Pilar and follow the signs to San Roque beach.",
      createdAt: "2024-01-07T08:00:00Z",
      updatedAt: null,
      deletedAt: null,
    },
    title: "torpfjgafb",
    subtitle: "torpfjgafb",
    photos: [
      {
        _id: "photo5",
        bookableUnitId: null,
        propertyId: "3",
        rentalId: null,
        activityId: null,
        key: "e1e96bed-047c-401e-8ab7-13f043f18445",
        thumbKey: "e1e96bed-047c-401e-8ab7-13f043f18445",
        isMain: true,
        description: "Villa exterior with an infinity pool",
        tags: "luxury",
        createdAt: "2024-01-14T10:00:00Z",
        updatedAt: null,
        deletedAt: null,
      },
    ],
    price: 1000,
    average: 0,
    reviewsCount: 0,
  },
  {
    listingId: "4",
    type: E_Property_Type.WHOLE_PLACE,
    wholeplaceType: undefined, // Explicitly undefined if not applicable
    location: {
      _id: "loc4",
      city: "Dapa",
      streetAddress: "Dapa Main Road",
      barangay: "Dapa",
      longitude: 126.1154,
      latitude: 9.8042,
      howToGetThere:
        "Drive to Dapa and find the bungalow near the market area.",
      createdAt: "2024-01-09T08:00:00Z",
      updatedAt: null,
      deletedAt: null,
    },
    title: "Tropical Villa",
    subtitle: "",
    photos: [
      {
        _id: "photo7",
        bookableUnitId: null,
        propertyId: "4",
        rentalId: null,
        activityId: null,
        key: "c7306dd2-5f7a-40c1-bee1-d79bd47e7016",
        thumbKey: "c7306dd2-5f7a-40c1-bee1-d79bd47e7016",
        isMain: true,
        description: "Charming bungalow exterior",
        tags: "bungalow",
        createdAt: "2024-01-16T10:00:00Z",
        updatedAt: null,
        deletedAt: null,
      },
    ],
    price: 7400,
    average: 0,
    reviewsCount: 0,
  },
  {
    listingId: "66ecd0484bc5c0eeea2e78a3",
    type: E_Property_Type.WHOLE_PLACE,
    wholeplaceType: null, // Valid enum value
    location: {
      _id: "loc5",
      city: "San Isidro",
      streetAddress: "Resort Drive",
      barangay: "Catangnan",
      longitude: 126.1528,
      latitude: 9.8456,
      howToGetThere:
        "Take a van from Siargao Airport to General Luna. Follow signs to Catangnan Resort Drive.",
      createdAt: "2024-01-11T08:00:00Z",
      updatedAt: null,
      deletedAt: null,
    },
    title: "test",
    subtitle: "Villa",
    photos: [
      {
        _id: "photo11",
        bookableUnitId: null,
        propertyId: "5",
        rentalId: null,
        activityId: null,
        key: "967ea7d7-1aac-460c-b71b-044c1fa84fcd",
        thumbKey: "967ea7d7-1aac-460c-b71b-044c1fa84fcd",
        isMain: true,
        description: "Oceanfront villa with stunning views",
        tags: "oceanfront",
        createdAt: "2024-01-20T10:00:00Z",
        updatedAt: null,
        deletedAt: null,
      },
    ],
    average: 4.9,
    reviewsCount: 90,
    price: 1000,
  },
  {
    listingId: "6",
    type: E_Property_Type.WHOLE_PLACE,
    wholeplaceType: E_Whole_Place_Property_Type.BUNGALOW, // Valid enum value
    location: {
      _id: "loc6",
      city: "Del Carmen",
      streetAddress: "Santa Monica Coastal Road",
      barangay: "Alegria",
      longitude: 126.1128,
      latitude: 9.8528,
      howToGetThere:
        "From General Luna, head north to Santa Monica. Follow signs to Alegria Coastal Road.",
      createdAt: "2024-01-12T08:00:00Z",
      updatedAt: null,
      deletedAt: null,
    },
    title: "House sample 1",
    subtitle: "",
    photos: [
      {
        _id: "photo12",
        bookableUnitId: null,
        propertyId: "6",
        rentalId: null,
        activityId: null,
        key: "2ad88334-a8ab-400b-8b6f-b51456347a43",
        thumbKey: "2ad88334-a8ab-400b-8b6f-b51456347a43",
        isMain: true,
        description: "Bungalow exterior with beach access",
        tags: "beach",
        createdAt: "2024-01-21T10:00:00Z",
        updatedAt: null,
        deletedAt: null,
      },
    ],
    price: 4000,
    average: 0,
    reviewsCount: 0,
  },
  {
    listingId: "66ed2f44fe4ab5ae5cf9940f",
    type: E_Property_Type.RESORT,
    wholeplaceType: undefined, // Explicitly undefined
    location: {
      _id: "loc7",
      city: "Del Carmen",
      streetAddress: "Mangrove Road",
      barangay: "San Benito",
      longitude: 126.0934,
      latitude: 9.8794,
      howToGetThere:
        "From Del Carmen Port, take a tricycle to San Benito Mangrove Road.",
      createdAt: "2024-01-13T08:00:00Z",
      updatedAt: null,
      deletedAt: null,
    },
    title: "Coast Malaya Tides",
    subtitle: "",
    photos: [
      {
        _id: "photo13",
        bookableUnitId: null,
        propertyId: "7",
        rentalId: null,
        activityId: null,
        key: "e1783d0c-7c67-462b-be5f-6a3b643074f4",
        thumbKey: "e1783d0c-7c67-462b-be5f-6a3b643074f4",
        isMain: true,
        description: "Rustic hostel surrounded by mangroves",
        tags: "eco-friendly",
        createdAt: "2024-01-22T10:00:00Z",
        updatedAt: null,
        deletedAt: null,
      },
    ],
    price: 2000,
    average: 0,
    reviewsCount: 0,
  },
  {
    listingId: "66ed2f44fe4ab5ae5cf9940f",
    type: E_Property_Type.HOTEL,
    wholeplaceType: undefined, // Explicitly undefined
    location: {
      _id: "loc8",
      city: "Santa Monica",
      streetAddress: "Surf Spot Avenue",
      barangay: "San Isidro",
      longitude: 126.1098,
      latitude: 9.8652,
      howToGetThere: "Drive to Pilar and head to San Isidro Surf Spot Avenue.",
      createdAt: "2024-01-14T08:00:00Z",
      updatedAt: null,
      deletedAt: null,
    },
    title: "Coast Malaya Tides",
    subtitle: "",
    photos: [
      {
        _id: "photo14",
        bookableUnitId: null,
        propertyId: "8",
        rentalId: null,
        activityId: null,
        key: "18da0194-0c36-42e0-9dbc-fafb5b5cf83d",
        thumbKey: "18da0194-0c36-42e0-9dbc-fafb5b5cf83d",
        isMain: true,
        description: "Hotel near the famous surf spots",
        tags: "surfing",
        createdAt: "2024-01-23T10:00:00Z",
        updatedAt: null,
        deletedAt: null,
      },
    ],
    price: 3000,
    average: 0,
    reviewsCount: 0,
  },
  {
    listingId: "66f65304ba6c843cc97bf25b",
    type: E_Property_Type.RESORT,
    wholeplaceType: undefined, // Explicitly undefined
    location: {
      _id: "loc9",
      city: "Burgos",
      streetAddress: "Mountain View Road",
      barangay: "Taytay",
      longitude: 126.1245,
      latitude: 9.8702,
      howToGetThere:
        "Take the Burgos Main Road to Taytay and follow Mountain View signs.",
      createdAt: "2024-01-15T08:00:00Z",
      updatedAt: null,
      deletedAt: null,
    },
    title: "Isla tropical",
    subtitle: "",
    photos: [
      {
        _id: "photo15",
        bookableUnitId: null,
        propertyId: "9",
        rentalId: null,
        activityId: null,
        key: "ff0a936d-1ebb-40c8-9656-7944ccf73578",
        thumbKey: "ff0a936d-1ebb-40c8-9656-7944ccf73578",
        isMain: true,
        description: "Traditional homestay with mountain views",
        tags: "mountain",
        createdAt: "2024-01-24T10:00:00Z",
        updatedAt: null,
        deletedAt: null,
      },
    ],
    price: 4000,
    average: 0,
    reviewsCount: 0,
  },
]
