import { E_Property_Type, E_Whole_Place_Property_Type } from "@repo/contract-2/property";

export const placesToStay = [
  {
    listingId: "1",
    type: E_Property_Type.COTTAGE,
    wholeplaceType: E_Whole_Place_Property_Type.COTTAGE, // Valid value from the enum
    location: {
      _id: "loc1",
      city: "General Luna",
      streetAddress: "Tourism Road",
      barangay: "Poblacion",
      longitude: 126.1628,
      latitude: 9.8486,
      howToGetThere: "From Siargao Airport, take a tricycle or van to General Luna. The cottage is located along Tourism Road.",
      createdAt: "2024-01-01T08:00:00Z",
      updatedAt: null,
      deletedAt: null,
    },
    title: "Cozy Cottage by the Beach",
    subtitle: "Relax and enjoy the tropical vibes of Siargao",
    photos: [
      {
        _id: "photo1",
        bookableUnitId: null,
        propertyId: "1",
        rentalId: null,
        activityId: null,
        key: "beachcottage1.jpg",
        thumbKey: "beachcottage1_thumb.jpg",
        isMain: true,
        description: "Exterior view of the cozy beach cottage",
        tags: "beach",
        createdAt: "2024-01-10T10:00:00Z",
        updatedAt: null,
        deletedAt: null,
      },
    ],
    average: 4.9,
    reviewsCount: 45,
    price: 250,
  },
  {
    listingId: "2",
    type: E_Property_Type.HOUSE,
    wholeplaceType: E_Whole_Place_Property_Type.HOUSE, // Valid value from the enum
    location: {
      _id: "loc2",
      city: "Del Carmen",
      streetAddress: "Cloud 9 Road",
      barangay: "Sugba",
      longitude: 126.0758,
      latitude: 9.8721,
      howToGetThere: "From Siargao Airport, head towards Del Carmen and follow signs to Sugba Lagoon.",
      createdAt: "2024-01-05T08:00:00Z",
      updatedAt: null,
      deletedAt: null,
    },
    title: "Modern House near Sugba Lagoon",
    subtitle: "Perfect for family getaways",
    photos: [
      {
        _id: "photo3",
        bookableUnitId: null,
        propertyId: "2",
        rentalId: null,
        activityId: null,
        key: "modernhouse1.jpg",
        thumbKey: "modernhouse1_thumb.jpg",
        isMain: true,
        description: "Modern house with a spacious garden",
        tags: "house",
        createdAt: "2024-01-12T10:00:00Z",
        updatedAt: null,
        deletedAt: null,
      },
    ],
    average: 4.8,
    reviewsCount: 65,
    price: 450,
  },
  {
    listingId: "3",
    type: E_Property_Type.VILLA,
    wholeplaceType: E_Whole_Place_Property_Type.VILLA, // Valid value from the enum
    location: {
      _id: "loc3",
      city: "Pilar",
      streetAddress: "Pilar Coastal Road",
      barangay: "San Roque",
      longitude: 126.0822,
      latitude: 9.8718,
      howToGetThere: "Take the main road to Pilar and follow the signs to San Roque beach.",
      createdAt: "2024-01-07T08:00:00Z",
      updatedAt: null,
      deletedAt: null,
    },
    title: "Luxury Villa with Infinity Pool",
    subtitle: "Experience Siargao in ultimate luxury",
    photos: [
      {
        _id: "photo5",
        bookableUnitId: null,
        propertyId: "3",
        rentalId: null,
        activityId: null,
        key: "luxuryvilla1.jpg",
        thumbKey: "luxuryvilla1_thumb.jpg",
        isMain: true,
        description: "Villa exterior with an infinity pool",
        tags: "luxury",
        createdAt: "2024-01-14T10:00:00Z",
        updatedAt: null,
        deletedAt: null,
      },
    ],
    average: 5.0,
    reviewsCount: 30,
    price: 900,
  },
  {
    listingId: "4",
    type: E_Property_Type.BUNGALOW,
    wholeplaceType: undefined, // Explicitly undefined if not applicable
    location: {
      _id: "loc4",
      city: "Dapa",
      streetAddress: "Dapa Main Road",
      barangay: "Dapa",
      longitude: 126.1154,
      latitude: 9.8042,
      howToGetThere: "Drive to Dapa and find the bungalow near the market area.",
      createdAt: "2024-01-09T08:00:00Z",
      updatedAt: null,
      deletedAt: null,
    },
    title: "Charming Bungalow in Dapa",
    subtitle: "Perfect for a quiet getaway",
    photos: [
      {
        _id: "photo7",
        bookableUnitId: null,
        propertyId: "4",
        rentalId: null,
        activityId: null,
        key: "bungalow1.jpg",
        thumbKey: "bungalow1_thumb.jpg",
        isMain: true,
        description: "Charming bungalow exterior",
        tags: "bungalow",
        createdAt: "2024-01-16T10:00:00Z",
        updatedAt: null,
        deletedAt: null,
      },
    ],
    average: 4.7,
    reviewsCount: 55,
    price: 200,
  },
  {
    listingId: "5",
    type: E_Property_Type.RESORT,
    wholeplaceType: E_Whole_Place_Property_Type.VILLA, // Valid enum value
    location: {
      _id: "loc5",
      city: "General Luna",
      streetAddress: "Resort Drive",
      barangay: "Catangnan",
      longitude: 126.1528,
      latitude: 9.8456,
      howToGetThere: "Take a van from Siargao Airport to General Luna. Follow signs to Catangnan Resort Drive.",
      createdAt: "2024-01-11T08:00:00Z",
      updatedAt: null,
      deletedAt: null,
    },
    title: "Seaside Luxury Resort",
    subtitle: "Relax in luxury with oceanfront views",
    photos: [
      {
        _id: "photo11",
        bookableUnitId: null,
        propertyId: "5",
        rentalId: null,
        activityId: null,
        key: "resort1.jpg",
        thumbKey: "resort1_thumb.jpg",
        isMain: true,
        description: "Oceanfront villa with stunning views",
        tags: "oceanfront",
        createdAt: "2024-01-20T10:00:00Z",
        updatedAt: null,
        deletedAt: null,
      },
    ],
    average: 4.9,
    reviewsCount: 90,
    price: 1000,
  },
  {
    listingId: "6",
    type: E_Property_Type.BUNGALOW,
    wholeplaceType: E_Whole_Place_Property_Type.BUNGALOW, // Valid enum value
    location: {
      _id: "loc6",
      city: "Santa Monica",
      streetAddress: "Santa Monica Coastal Road",
      barangay: "Alegria",
      longitude: 126.1128,
      latitude: 9.8528,
      howToGetThere: "From General Luna, head north to Santa Monica. Follow signs to Alegria Coastal Road.",
      createdAt: "2024-01-12T08:00:00Z",
      updatedAt: null,
      deletedAt: null,
    },
    title: "Beachside Bungalow Retreat",
    subtitle: "Enjoy tranquility by the sea",
    photos: [
      {
        _id: "photo12",
        bookableUnitId: null,
        propertyId: "6",
        rentalId: null,
        activityId: null,
        key: "bungalow3.jpg",
        thumbKey: "bungalow3_thumb.jpg",
        isMain: true,
        description: "Bungalow exterior with beach access",
        tags: "beach",
        createdAt: "2024-01-21T10:00:00Z",
        updatedAt: null,
        deletedAt: null,
      },
    ],
    average: 4.8,
    reviewsCount: 60,
    price: 300,
  },
  {
    listingId: "7",
    type: E_Property_Type.HOSTEL,
    wholeplaceType: undefined, // Explicitly undefined
    location: {
      _id: "loc7",
      city: "Del Carmen",
      streetAddress: "Mangrove Road",
      barangay: "San Benito",
      longitude: 126.0934,
      latitude: 9.8794,
      howToGetThere: "From Del Carmen Port, take a tricycle to San Benito Mangrove Road.",
      createdAt: "2024-01-13T08:00:00Z",
      updatedAt: null,
      deletedAt: null,
    },
    title: "Eco-Friendly Mangrove Hostel",
    subtitle: "Affordable stay near the mangroves",
    photos: [
      {
        _id: "photo13",
        bookableUnitId: null,
        propertyId: "7",
        rentalId: null,
        activityId: null,
        key: "hostel1.jpg",
        thumbKey: "hostel1_thumb.jpg",
        isMain: true,
        description: "Rustic hostel surrounded by mangroves",
        tags: "eco-friendly",
        createdAt: "2024-01-22T10:00:00Z",
        updatedAt: null,
        deletedAt: null,
      },
    ],
    average: 4.5,
    reviewsCount: 40,
    price: 150,
  },
  {
    listingId: "8",
    type: E_Property_Type.HOTEL,
    wholeplaceType: undefined, // Explicitly undefined
    location: {
      _id: "loc8",
      city: "Pilar",
      streetAddress: "Surf Spot Avenue",
      barangay: "San Isidro",
      longitude: 126.1098,
      latitude: 9.8652,
      howToGetThere: "Drive to Pilar and head to San Isidro Surf Spot Avenue.",
      createdAt: "2024-01-14T08:00:00Z",
      updatedAt: null,
      deletedAt: null,
    },
    title: "Wave Rider Hotel",
    subtitle: "Perfect for surfers and adventurers",
    photos: [
      {
        _id: "photo14",
        bookableUnitId: null,
        propertyId: "8",
        rentalId: null,
        activityId: null,
        key: "hotel3.jpg",
        thumbKey: "hotel3_thumb.jpg",
        isMain: true,
        description: "Hotel near the famous surf spots",
        tags: "surfing",
        createdAt: "2024-01-23T10:00:00Z",
        updatedAt: null,
        deletedAt: null,
      },
    ],
    average: 4.7,
    reviewsCount: 75,
    price: 400,
  },
  {
    listingId: "9",
    type: E_Property_Type.HOMESTAY,
    wholeplaceType: undefined, // Explicitly undefined
    location: {
      _id: "loc9",
      city: "Burgos",
      streetAddress: "Mountain View Road",
      barangay: "Taytay",
      longitude: 126.1245,
      latitude: 9.8702,
      howToGetThere: "Take the Burgos Main Road to Taytay and follow Mountain View signs.",
      createdAt: "2024-01-15T08:00:00Z",
      updatedAt: null,
      deletedAt: null,
    },
    title: "Homestay with Mountain Views",
    subtitle: "Stay with locals and enjoy scenic views",
    photos: [
      {
        _id: "photo15",
        bookableUnitId: null,
        propertyId: "9",
        rentalId: null,
        activityId: null,
        key: "homestay1.jpg",
        thumbKey: "homestay1_thumb.jpg",
        isMain: true,
        description: "Traditional homestay with mountain views",
        tags: "mountain",
        createdAt: "2024-01-24T10:00:00Z",
        updatedAt: null,
        deletedAt: null,
      },
    ],
    average: 4.6,
    reviewsCount: 50,
    price: 200,
  },
];