import { HOST } from "@/common/constants"
import { APP_NAME } from "@repo/constants"
import { Metadata } from "next"
import AuthGuard from "@/common/components/AuthGuard"
import RentalPricing from "@/module/Admin/Listings/Declined/Rental/Pricing"

export const metadata: Metadata = {
  title: `${HOST} - ${APP_NAME}`,
  description: `Generated by ${APP_NAME}`,
}

const ListingPricingPage = () => {
  return (
    <AuthGuard>
      <RentalPricing pageType="setup" />
    </AuthGuard>
  )
}

export default ListingPricingPage
