import { HOST } from "@/common/constants"
import { APP_NAME } from "@repo/constants"
import { Metadata } from "next"
import AuthGuard from "@/common/components/AuthGuard"
import PropertyCalendar from "@/module/Hosting/Reservations/calendar-2/property"

export const metadata: Metadata = {
  title: `${HOST} - ${APP_NAME}`,
  description: `Generated by ${APP_NAME}`,
}

const ReservationCalendarPage = () => {
  return (
    <AuthGuard>
      <PropertyCalendar />
    </AuthGuard>
  )
}

export default ReservationCalendarPage
