import { HOST } from "@/common/constants"
import { APP_NAME } from "@repo/constants"
import { Metadata } from "next"
import AuthGuard from "@/common/components/AuthGuard"
import PropertyType from "@/module/Hosting/Listings/Properties/Property/PropertyType"

export const metadata: Metadata = {
  title: `${HOST} - ${APP_NAME}`,
  description: `Generated by ${APP_NAME}`,
}

const PropertyTypePage = () => {
  return (
    <AuthGuard>
      <PropertyType pageType="edit" />
    </AuthGuard>
  )
}

export default PropertyTypePage
