import type { Metadata } from "next"

import "@/app/globals.css"
import QueryClientWrapper from "@/common/components/QueryClientWrapper"
import GlobalModalWrapper from "@/common/components/GlobalModalWrapper"
import { Toaster } from "react-hot-toast"
import React from "react"
import { LOGO_SINGLE_IMAGE } from "@/common/constants/index"
import { APP_NAME } from "@repo/constants"
import AuthStateProvider from "@/common/components/AuthStateProvider"
import Footer from "@/common/components/Footer"
import GuideHeader from "@/common/components/Header"
import GuideBlogHeader from "@/common/components/Header"
import SearchBar from "@/common/components/SearchBar/SearchBarByState"

export const metadata: Metadata = {
  title: APP_NAME,
  description: `Generated by ${APP_NAME}`,
}

export default async function RootLayout({
  children,
}: {
  readonly children: React.ReactNode
}) {
  return (
    <html lang="en">
      <link rel="icon" type="image/x-icon" href={LOGO_SINGLE_IMAGE} />
      <body>
        <Toaster />
        <QueryClientWrapper>
          <AuthStateProvider>
            <GlobalModalWrapper>
              <GuideHeader contentWidth="medium" isFixed={false} />
              <SearchBar
                contentWidth="small"
                customClass="bg-primary-50 items-center"
                searchBarWidth="w-[900px]"
              />
              <GuideBlogHeader contentWidth="medium" />
              {children}
              <Footer contentWidth="medium" />
            </GlobalModalWrapper>
          </AuthStateProvider>
        </QueryClientWrapper>
      </body>
    </html>
  )
}
