import {
  E_Rental_Category,
  E_Rental_Vehicle_Fuel,
  E_Rental_Vehicle_Transmission,
} from "@repo/contract"

export const rentals = [
  {
    _id: "1",
    details: null,
    pricing: {
      _id: "pricing1",
      dayRate: 50,
      requiredDeposit: 100,
      adminBookingCharge: 10,
      createdAt: "2024-01-10T10:00:00Z",
      updatedAt: null,
      deletedAt: null,
    },
    host: {
      _id: "host1",
      role: "admin",
      isHost: true,
      guest: {
        _id: "guest1",
        firstName: "John",
        lastName: "Doe",
        language: "English",
        currency: "USD",
        country: "USA",
        address: {
          _id: "address1",
          createdAt: "2024-01-01T12:00:00Z",
          country: "USA",
          city: "New York",
          stateProvince: "NY",
          zipCode: 10001,
          streetAddress: "123 Main St",
          aptSuite: null,
          updatedAt: null,
        },
      },
    },
    category: E_Rental_Category.Car,
    make: "Toyota",
    modelBadge: "Corolla",
    bodyType: "Sedan",
    fuel: E_Rental_Vehicle_Fuel.Petrol,
    transmission: E_Rental_Vehicle_Transmission.Manual,
    year: "2023",
    qty: 5,
    addOns: null,
    photos: [
      {
        _id: "photo1",
        key: "toyota_corolla.jpg",
        thumbKey: "toyota_corolla_thumb.jpg",
        isMain: true,
        description: "Toyota Corolla rental",
        tags: "car",
        createdAt: "2024-01-10T10:00:00Z",
        updatedAt: null,
        deletedAt: null,
      },
    ],
    location: {
      _id: "location1",
      city: "General Luna",
      streetAddress: "Tourist Road",
      barangay: "Poblacion",
      longitude: 126.162,
      latitude: 9.8486,
      howToGetThere: "Meet at the General Luna Tourism Office.",
    },
    status: "Live",
    finishedSections: ["photos", "details", "pricing"],
    qtyIds: [
      {
        _id: "qty1",
        name: "Vehicle 1",
      },
      {
        _id: "qty2",
        name: "Vehicle 2",
      },
    ],
    pricePerDates: [],
    rentalNote: "Perfect for exploring the island.",
    average: 4.8,
    reviewsCount: 120,
  },
  {
    _id: "2",
    details: null,
    pricing: {
      _id: "pricing2",
      dayRate: 60,
      requiredDeposit: 150,
      adminBookingCharge: 15,
      createdAt: "2024-01-12T10:00:00Z",
      updatedAt: null,
      deletedAt: null,
    },
    host: {
      _id: "host2",
      role: "host",
      isHost: true,
      guest: {
        _id: "guest2",
        firstName: "Alice",
        lastName: "Smith",
        language: "English",
        currency: "PHP",
        country: "Philippines",
        address: {
          _id: "address2",
          createdAt: "2024-01-02T12:00:00Z",
          country: "Philippines",
          city: "Cebu",
          stateProvince: "Cebu",
          zipCode: 6000,
          streetAddress: "456 Island Ave",
          aptSuite: null,
          updatedAt: null,
        },
      },
    },
    category: E_Rental_Category.Car,
    make: "Honda",
    modelBadge: "Civic",
    bodyType: "Sedan",
    fuel: E_Rental_Vehicle_Fuel.Diesel,
    transmission: E_Rental_Vehicle_Transmission.Manual,
    year: "2022",
    qty: 4,
    addOns: null,
    photos: [
      {
        _id: "photo2",
        key: "honda_civic.jpg",
        thumbKey: "honda_civic_thumb.jpg",
        isMain: true,
        description: "Honda Civic rental",
        tags: "car",
        createdAt: "2024-01-12T10:00:00Z",
        updatedAt: null,
        deletedAt: null,
      },
    ],
    location: {
      _id: "location2",
      city: "Dapa",
      streetAddress: "Dapa Port Terminal",
      barangay: "Union",
      longitude: 126.0711,
      latitude: 9.7542,
      howToGetThere: "Meet at Dapa Port.",
    },
    status: "Pending",
    finishedSections: ["details", "pricing", "photos"],
    qtyIds: null,
    pricePerDates: [],
    rentalNote: "Great for trips to local attractions.",
    average: 4.7,
    reviewsCount: 85,
  },
  {
    _id: "3",
    details: null,
    pricing: {
      _id: "pricing3",
      dayRate: 55,
      requiredDeposit: 120,
      adminBookingCharge: 12,
      createdAt: "2024-01-15T10:00:00Z",
      updatedAt: null,
      deletedAt: null,
    },
    host: {
      _id: "host3",
      role: "guide",
      isHost: true,
      guest: {
        _id: "guest3",
        firstName: "Carlos",
        lastName: "Garcia",
        language: "Spanish",
        currency: "EUR",
        country: "Spain",
        address: {
          _id: "address3",
          createdAt: "2024-01-03T12:00:00Z",
          country: "Spain",
          city: "Madrid",
          stateProvince: "Community of Madrid",
          zipCode: 28001,
          streetAddress: "123 Madrid Way",
          aptSuite: "Suite 12",
          updatedAt: null,
        },
      },
    },
    category: E_Rental_Category.Car,
    make: "Ford",
    modelBadge: "Focus",
    bodyType: "Hatchback",
    fuel: E_Rental_Vehicle_Fuel.Diesel,
    transmission: E_Rental_Vehicle_Transmission.Manual,
    year: "2021",
    qty: 2,
    addOns: null,
    photos: [
      {
        _id: "photo3",
        key: "ford_focus.jpg",
        thumbKey: "ford_focus_thumb.jpg",
        isMain: true,
        description: "Ford Focus rental",
        tags: "car",
        createdAt: "2024-01-20T10:00:00Z",
        updatedAt: null,
        deletedAt: null,
      },
    ],
    location: {
      _id: "location3",
      city: "Del Carmen",
      streetAddress: "Mangrove Forest Park",
      barangay: "Tuburan",
      longitude: 126.0567,
      latitude: 9.8765,
      howToGetThere: "Meet near the Mangrove Forest entrance.",
    },
    status: "Incomplete",
    finishedSections: ["photos", "details", "pricing"],
    qtyIds: [
      {
        _id: "qty3",
        name: "Focus 1",
      },
    ],
    pricePerDates: [],
    rentalNote: "Suitable for family trips.",
    average: 4.6,
    reviewsCount: 60,
  },
  {
    _id: "4",
    details: null,
    pricing: {
      _id: "pricing4",
      dayRate: 65,
      requiredDeposit: 180,
      adminBookingCharge: 20,
      createdAt: "2024-01-18T10:00:00Z",
      updatedAt: null,
      deletedAt: null,
    },
    host: {
      _id: "host4",
      role: "host",
      isHost: true,
      guest: {
        _id: "guest4",
        firstName: "Emma",
        lastName: "Martinez",
        language: "Spanish",
        currency: "EUR",
        country: "Spain",
        address: {
          _id: "address4",
          createdAt: "2024-01-04T12:00:00Z",
          country: "Spain",
          city: "Barcelona",
          stateProvince: "Catalonia",
          zipCode: 6566,
          streetAddress: "456 Sunset Blvd",
          aptSuite: null,
          updatedAt: null,
        },
      },
    },
    category: E_Rental_Category.Car,
    make: "Nissan",
    modelBadge: "Altima",
    bodyType: "Sedan",
    fuel: E_Rental_Vehicle_Fuel.Petrol,
    transmission: E_Rental_Vehicle_Transmission.Manual,
    year: "2020",
    qty: 3,
    addOns: null,
    photos: [
      {
        _id: "photo4",
        key: "nissan_altima.jpg",
        thumbKey: "nissan_altima_thumb.jpg",
        isMain: true,
        description: "Nissan Altima rental",
        tags: "car",
        createdAt: "2024-01-22T10:00:00Z",
        updatedAt: null,
        deletedAt: null,
      },
    ],
    location: {
      _id: "location4",
      city: "Pilar",
      streetAddress: "Magpupungko Rock Pools",
      barangay: "San Roque",
      longitude: 126.1374,
      latitude: 9.8674,
      howToGetThere: "Meet at the Magpupungko entrance.",
    },
    status: "Live",
    finishedSections: ["photos", "details", "pricing"],
    qtyIds: [
      {
        _id: "qty4",
        name: "Altima 1",
      },
    ],
    pricePerDates: [],
    rentalNote: "Perfect for island-wide exploration.",
    average: 4.5,
    reviewsCount: 75,
  },
  {
    _id: "5",
    details: null,
    pricing: {
      _id: "pricing5",
      dayRate: 40,
      requiredDeposit: 90,
      adminBookingCharge: 8,
      createdAt: "2024-01-20T10:00:00Z",
      updatedAt: null,
      deletedAt: null,
    },
    host: {
      _id: "host5",
      role: "guide",
      isHost: true,
      guest: {
        _id: "guest5",
        firstName: "Liam",
        lastName: "Clark",
        language: "English",
        currency: "USD",
        country: "Canada",
        address: {
          _id: "address5",
          createdAt: "2024-01-05T12:00:00Z",
          country: "Canada",
          city: "Toronto",
          stateProvince: "ON",
          zipCode: 12345,
          streetAddress: "789 Maple St",
          aptSuite: null,
          updatedAt: null,
        },
      },
    },
    category: E_Rental_Category.Car,
    make: "Chevrolet",
    modelBadge: "Malibu",
    bodyType: "Sedan",
    fuel: E_Rental_Vehicle_Fuel.Diesel,
    transmission: E_Rental_Vehicle_Transmission.Manual,
    year: "2020",
    qty: 2,
    addOns: null,
    photos: [
      {
        _id: "photo5",
        key: "chevrolet_malibu.jpg",
        thumbKey: "chevrolet_malibu_thumb.jpg",
        isMain: true,
        description: "Chevrolet Malibu rental",
        tags: "car",
        createdAt: "2024-01-25T10:00:00Z",
        updatedAt: null,
        deletedAt: null,
      },
    ],
    location: {
      _id: "location5",
      city: "San Isidro",
      streetAddress: "Pacifico Beach",
      barangay: "Pacifico",
      longitude: 126.1523,
      latitude: 9.8987,
      howToGetThere: "Meet near the Pacifico Surf Spot.",
    },
    status: "Pending",
    finishedSections: ["photos", "details", "pricing"],
    qtyIds: null,
    pricePerDates: [],
    rentalNote: "Perfect for beach hopping.",
    average: 4.9,
    reviewsCount: 90,
  },
  {
    _id: "6",
    details: null,
    pricing: {
      _id: "pricing6",
      dayRate: 75,
      requiredDeposit: 200,
      adminBookingCharge: 20,
      createdAt: "2024-01-28T10:00:00Z",
      updatedAt: null,
      deletedAt: null,
    },
    host: {
      _id: "host6",
      role: "admin",
      isHost: true,
      guest: {
        _id: "guest6",
        firstName: "Noah",
        lastName: "Jones",
        language: "English",
        currency: "AUD",
        country: "Australia",
        address: {
          _id: "address6",
          createdAt: "2024-01-06T12:00:00Z",
          country: "Australia",
          city: "Sydney",
          stateProvince: "NSW",
          zipCode: 2000, // Fixed to a number
          streetAddress: "123 Ocean View Blvd",
          aptSuite: null,
          updatedAt: null,
        },
      },
    },
    category: E_Rental_Category.Car,
    make: "Mazda",
    modelBadge: "CX-5",
    bodyType: "SUV",
    fuel: E_Rental_Vehicle_Fuel.Diesel,
    transmission: E_Rental_Vehicle_Transmission.Manual,
    year: "2021",
    qty: 3,
    addOns: null,
    photos: [
      {
        _id: "photo6",
        key: "mazda_cx5.jpg",
        thumbKey: "mazda_cx5_thumb.jpg",
        isMain: true,
        description: "Mazda CX-5 rental",
        tags: "car, SUV",
        createdAt: "2024-01-30T10:00:00Z",
        updatedAt: null,
        deletedAt: null,
      },
    ],
    location: {
      _id: "location6",
      city: "Santa Monica",
      streetAddress: "Taktak Falls Road",
      barangay: "Taktak",
      longitude: 126.1553,
      latitude: 9.9832,
      howToGetThere: "Meet near the entrance of Taktak Falls.",
    },
    status: "Live",
    finishedSections: ["photos", "details", "pricing"],
    qtyIds: [
      {
        _id: "qty6",
        name: "Mazda CX-5",
      },
    ],
    pricePerDates: [],
    rentalNote: "Great for rugged adventures.",
    average: 4.6,
    reviewsCount: 85,
  },
  {
    _id: "7",
    details: null,
    pricing: {
      _id: "pricing7",
      dayRate: 50,
      requiredDeposit: 110,
      adminBookingCharge: 12,
      createdAt: "2024-02-02T10:00:00Z",
      updatedAt: null,
      deletedAt: null,
    },
    host: {
      _id: "host7",
      role: "host",
      isHost: true,
      guest: {
        _id: "guest7",
        firstName: "Sophia",
        lastName: "Miller",
        language: "English",
        currency: "GBP",
        country: "UK",
        address: {
          _id: "address7",
          createdAt: "2024-01-07T12:00:00Z",
          country: "UK",
          city: "London",
          stateProvince: "Greater London",
          zipCode: 12345, // Fixed to a number
          streetAddress: "456 Abbey Road",
          aptSuite: null,
          updatedAt: null,
        },
      },
    },
    category: E_Rental_Category.Car,
    make: "Hyundai",
    modelBadge: "Tucson",
    bodyType: "SUV",
    fuel: E_Rental_Vehicle_Fuel.Diesel,
    transmission: E_Rental_Vehicle_Transmission.Manual,
    year: "2020",
    qty: 4,
    addOns: null,
    photos: [
      {
        _id: "photo7",
        key: "hyundai_tucson.jpg",
        thumbKey: "hyundai_tucson_thumb.jpg",
        isMain: true,
        description: "Hyundai Tucson rental",
        tags: "car, SUV",
        createdAt: "2024-02-01T10:00:00Z",
        updatedAt: null,
        deletedAt: null,
      },
    ],
    location: {
      _id: "location7",
      city: "Burgos",
      streetAddress: "Alegria Beachfront",
      barangay: "Alegria",
      longitude: 126.1235,
      latitude: 9.9178,
      howToGetThere: "Meet at the Alegria Beachfront parking area.",
    },
    status: "Live",
    finishedSections: ["photos", "details", "pricing"],
    qtyIds: null,
    pricePerDates: [],
    rentalNote: "Reliable and comfortable for beach trips.",
    average: 4.8,
    reviewsCount: 90,
  },
  {
    _id: "8",
    details: null,
    pricing: {
      _id: "pricing8",
      dayRate: 45,
      requiredDeposit: 95,
      adminBookingCharge: 9,
      createdAt: "2024-02-05T10:00:00Z",
      updatedAt: null,
      deletedAt: null,
    },
    host: {
      _id: "host8",
      role: "host",
      isHost: true,
      guest: {
        _id: "guest8",
        firstName: "Ella",
        lastName: "Brown",
        language: "English",
        currency: "AUD",
        country: "Australia",
        address: {
          _id: "address8",
          createdAt: "2024-01-08T12:00:00Z",
          country: "Australia",
          city: "Melbourne",
          stateProvince: "VIC",
          zipCode: 3000, // Fixed to a number
          streetAddress: "123 Federation Square",
          aptSuite: null,
          updatedAt: null,
        },
      },
    },
    category: E_Rental_Category.Car,
    make: "Suzuki",
    modelBadge: "Jimny",
    bodyType: "Compact",
    fuel: E_Rental_Vehicle_Fuel.Diesel,
    transmission: E_Rental_Vehicle_Transmission.Manual,
    year: "2021",
    qty: 3,
    addOns: null,
    photos: [
      {
        _id: "photo8",
        key: "suzuki_jimny.jpg",
        thumbKey: "suzuki_jimny_thumb.jpg",
        isMain: true,
        description: "Suzuki Jimny rental",
        tags: "car, compact",
        createdAt: "2024-02-04T10:00:00Z",
        updatedAt: null,
        deletedAt: null,
      },
    ],
    location: {
      _id: "location8",
      city: "San Benito",
      streetAddress: "Hidden Beach Trail",
      barangay: "Tawin-Tawin",
      longitude: 126.1047,
      latitude: 9.8782,
      howToGetThere: "Meet near the trailhead of Hidden Beach.",
    },
    status: "Live",
    finishedSections: ["photos", "details", "pricing"],
    qtyIds: null,
    pricePerDates: [],
    rentalNote: "Perfect for narrow trails and hidden spots.",
    average: 4.7,
    reviewsCount: 78,
  },
]
