import { T_Policy } from "@repo/contract-2/property";

export const policiesItem: T_Policy[] = [
  {
    index: 0,
    category: "Things To Know",
    policy: "No pets allowed",
    reason: null,
    isSelected: true,
  },
  {
    index: 1,
    category: "Things To Know",
    policy: "Pets allowed",
    reason: null,
    isSelected: true,
  },
  {
    index: 2,
    category: "Things To Know",
    policy: "No parties or events",
    reason: null,
    isSelected: true,
  },
  {
    index: 3,
    category: "Things To Know",
    policy: "Parties or events allowed",
    reason: "Only at designated areas of facility",
    isSelected: false,
  },
  {
    index: 4,
    category: "Things To Know",
    policy: "No commercial photography",
    reason: "To maintain area privacy",
    isSelected: false,
  },
  {
    index: 5,
    category: "Things To Know",
    policy: "Commercial photography allowed",
    reason: "For promotions",
    isSelected: false,
  },
  {
    index: 6,
    category: "Things To Know",
    policy: "No smoking",
    reason: "There are guests with health concerns",
    isSelected: false,
  },
  {
    index: 7,
    category: "Things To Know",
    policy: "Smoking in designated areas only",
    reason: "Also e-cigarettes and vapes are prohibited in some areas",
    isSelected: false,
  },
  {
    index: 8,
    category: "Things To Know",
    policy: "Smoking allowed",
    reason: "This is a smoking area",
    isSelected: false,
  },
  {
    index: 9,
    category: "Safety Considerations",
    policy: "Not suitable for children and infants",
    reason: null,
    isSelected: false,
  },
  {
    index: 10,
    category: "Safety Considerations",
    policy: "Near by ocean, river, other body of water",
    reason: null,
    isSelected: false,
  },
  {
    index: 11,
    category: "Safety Devices",
    policy: "Carbon Monoxide installed",
    reason: null,
    isSelected: false,
  },
  {
    index: 12,
    category: "Safety Devices",
    policy: "No carbon monoxide alarm",
    reason: null,
    isSelected: false,
  },
  {
    index: 13,
    category: "Safety Devices",
    policy: "Smoke alarm installed",
    reason: null,
    isSelected: false,
  },
  {
    index: 14,
    category: "Safety Devices",
    policy: "No smoke alarm installed",
    reason: null,
    isSelected: false,
  },
  {
    index: 15,
    category: "Safety Devices",
    policy: "No smoke alarm",
    reason: null,
    isSelected: false,
  },
  {
    index: 16,
    category: "Safety Devices",
    policy: "Security cameras/recording devices",
    reason: null,
    isSelected: false,
  },
  {
    index: 17,
    category: "Property Info",
    policy: "Pet(s) live on property",
    reason: null,
    isSelected: false,
  },
  {
    index: 18,
    category: "Property Info",
    policy: "Potential for noise",
    reason: null,
    isSelected: false,
  },
  {
    index: 19,
    category: "Property Info",
    policy: "Must climbed stairs",
    reason: null,
    isSelected: false,
  },
  {
    index: 20,
    category: "Property Info",
    policy: "No parking on property",
    reason: "Only at designated areas of facility",
    isSelected: false,
  },
  {
    index: 21,
    category: "Property Info",
    policy: "No wheelchair access",
    reason: "To maintain area privacy",
    isSelected: false,
  },
  {
    index: 22,
    category: "Property Info",
    policy: "No cellphone signal",
    reason: "For promotions",
    isSelected: false,
  },
  {
    index: 23,
    category: "Additional Rules",
    policy: "",
    reason: null,
    isSelected: true,
  },
]