import {
  E_Property_Status,
  E_Property_Type,
  E_Whole_Place_Property_Type,
  T_Add_Property,
  T_Amenity,
  T_Bookable_Units,
  T_Facility,
  T_Policy,
  T_Unit_Price,
} from "@repo/contract-2/property"
import {
  dbAmenities,
  dbBookableUnitTypes,
  dbFacilities,
  dbLocations,
  dbPhotos,
  dbPolicies,
  dbProperties,
  dbUnitPrices,
  dbUsers,
} from "@repo/database"
const MOST_POPULAR = "Most Popular"
const OUTDOORS = "Outdoors"
const ACTIVITIES = "Activities"
const FOOD_DRINK = "Food & Drink"
const INTERNET = "Internet"
const PARKING = "Parking"
const SERVICES = "Services"
const RECEPTION_SERVICES = "Reception Services"
const SAFETY_SECURITY = "Safety & Security"
const GENERAL = "General"
const WELLNESS = "Wellness"
const CLEANING_SERVICES = "Cleaning Services"
const BUSINESS_FACILITIES = "Business Facilities"
const ENTERTAINMENT = "Entertainment and family services"
const ONSITE = "On-site Payment Methods"
const LANGUAGES = "Languages Spoken"
const BATHROOM = "Bathroom"
const KITCHEN = "Kitchen"
const LIVING_AREA = "Living Area"

const policiesItem: T_Policy[] = [
  {
    index: 0,
    category: "Things To Know",
    policy: "No pets allowed",
    reason: null,
    isSelected: true,
  },
  {
    index: 1,
    category: "Things To Know",
    policy: "Pets allowed",
    reason: null,
    isSelected: true,
  },
  {
    index: 2,
    category: "Things To Know",
    policy: "No parties or events",
    reason: null,
    isSelected: true,
  },
  {
    index: 3,
    category: "Things To Know",
    policy: "Parties or events allowed",
    reason: "Only at designated areas of facility",
    isSelected: false,
  },
  {
    index: 4,
    category: "Things To Know",
    policy: "No commercial photography",
    reason: "To maintain area privacy",
    isSelected: false,
  },
  {
    index: 5,
    category: "Things To Know",
    policy: "Commercial photography allowed",
    reason: "For promotions",
    isSelected: false,
  },
  {
    index: 6,
    category: "Things To Know",
    policy: "No smoking",
    reason: "There are guests with health concerns",
    isSelected: false,
  },
  {
    index: 7,
    category: "Things To Know",
    policy: "Smoking in designated areas only",
    reason: "Also e-cigarettes and vapes are prohibited in some areas",
    isSelected: false,
  },
  {
    index: 8,
    category: "Things To Know",
    policy: "Smoking allowed",
    reason: "This is a smoking area",
    isSelected: false,
  },
  {
    index: 9,
    category: "Safety Considerations",
    policy: "Not suitable for children and infants",
    reason: null,
    isSelected: false,
  },
  {
    index: 10,
    category: "Safety Considerations",
    policy: "Near by ocean, river, other body of water",
    reason: null,
    isSelected: false,
  },
  {
    index: 11,
    category: "Safety Devices",
    policy: "Carbon Monoxide installed",
    reason: null,
    isSelected: false,
  },
  {
    index: 12,
    category: "Safety Devices",
    policy: "No carbon monoxide alarm",
    reason: null,
    isSelected: false,
  },
  {
    index: 13,
    category: "Safety Devices",
    policy: "Smoke alarm installed",
    reason: null,
    isSelected: false,
  },
  {
    index: 14,
    category: "Safety Devices",
    policy: "No smoke alarm installed",
    reason: null,
    isSelected: false,
  },
  {
    index: 15,
    category: "Safety Devices",
    policy: "No smoke alarm",
    reason: null,
    isSelected: false,
  },
  {
    index: 16,
    category: "Safety Devices",
    policy: "Security cameras/recording devices",
    reason: null,
    isSelected: false,
  },
  {
    index: 17,
    category: "Property Info",
    policy: "Pet(s) live on property",
    reason: null,
    isSelected: false,
  },
  {
    index: 18,
    category: "Property Info",
    policy: "Potential for noise",
    reason: null,
    isSelected: false,
  },
  {
    index: 19,
    category: "Property Info",
    policy: "Must climbed stairs",
    reason: null,
    isSelected: false,
  },
  {
    index: 20,
    category: "Property Info",
    policy: "No parking on property",
    reason: "Only at designated areas of facility",
    isSelected: false,
  },
  {
    index: 21,
    category: "Property Info",
    policy: "No wheelchair access",
    reason: "To maintain area privacy",
    isSelected: false,
  },
  {
    index: 22,
    category: "Property Info",
    policy: "No cellphone signal",
    reason: "For promotions",
    isSelected: false,
  },
  {
    index: 23,
    category: "Additional Rules",
    policy: "",
    reason: null,
    isSelected: true,
  },
]

const amenitiesItem: T_Amenity[] = [
  {
    index: 0,
    category: MOST_POPULAR,
    amenity: "Bar",
    isSelected: true,
  },
  {
    index: 1,
    category: MOST_POPULAR,
    amenity: "Sauna",
    isSelected: true,
  },
  {
    index: 2,
    category: MOST_POPULAR,
    amenity: "Garden",
    isSelected: false,
  },
  {
    index: 3,
    category: MOST_POPULAR,
    amenity: "Terrace",
    isSelected: true,
  },
  {
    index: 4,
    category: MOST_POPULAR,
    amenity: "Hot tub/Jacuzzi",
    isSelected: false,
  },
  {
    index: 5,
    category: MOST_POPULAR,
    amenity: "Heating",
    isSelected: false,
  },
  {
    index: 6,
    category: MOST_POPULAR,
    amenity: "Free WiFi",
    isSelected: false,
  },
  {
    index: 7,
    category: MOST_POPULAR,
    amenity: "Air conditioning",
    isSelected: false,
  },
  {
    index: 8,
    category: MOST_POPULAR,
    amenity: "Swimming pool",
    isSelected: false,
  },
  {
    index: 9,
    category: MOST_POPULAR,
    amenity: "Beach",
    isSelected: false,
  },
  {
    index: 10,
    category: BATHROOM,
    amenity: "Free toiletries",
    isSelected: false,
  },
  {
    index: 11,
    category: BATHROOM,
    amenity: "Bidet",
    isSelected: false,
  },
  {
    index: 12,
    category: BATHROOM,
    amenity: "Toilet",
    isSelected: false,
  },
  {
    index: 13,
    category: BATHROOM,
    amenity: "Bath or shower",
    isSelected: false,
  },
  {
    index: 14,
    category: BATHROOM,
    amenity: "Towels",
    isSelected: false,
  },
  {
    index: 15,
    category: BATHROOM,
    amenity: "Linen",
    isSelected: false,
  },
  {
    index: 16,
    category: BATHROOM,
    amenity: "Tile/marble floor",
    isSelected: false,
  },
  {
    index: 17,
    category: BATHROOM,
    amenity: "Bathrobe",
    isSelected: false,
  },
  {
    index: 18,
    category: BATHROOM,
    amenity: "Toilet paper",
    isSelected: false,
  },
  {
    index: 19,
    category: BATHROOM,
    amenity: "Hairdryer",
    isSelected: false,
  },
  {
    index: 20,
    category: BATHROOM,
    amenity: "Hand sanitiser",
    isSelected: false,
  },
  {
    index: 21,
    category: BATHROOM,
    amenity: "Spa bath",
    isSelected: false,
  },
  {
    index: 22,
    category: OUTDOORS,
    amenity: "Beachfront",
    isSelected: false,
  },
  {
    index: 23,
    category: KITCHEN,
    amenity: "Tea/Coffee maker",
    isSelected: false,
  },
  {
    index: 24,
    category: KITCHEN,
    amenity: "Microwave",
    isSelected: false,
  },
  {
    index: 25,
    category: KITCHEN,
    amenity: "Kitchenware",
    isSelected: false,
  },
  {
    index: 26,
    category: KITCHEN,
    amenity: "Hot/cold water dispenser",
    isSelected: false,
  },
  {
    index: 27,
    category: KITCHEN,
    amenity: "Electric kettle",
    isSelected: false,
  },
  {
    index: 28,
    category: KITCHEN,
    amenity: "Stovetop",
    isSelected: false,
  },
  {
    index: 29,
    category: KITCHEN,
    amenity: "Dining area",
    isSelected: false,
  },
  {
    index: 30,
    category: KITCHEN,
    amenity: "Dining table",
    isSelected: false,
  },
  {
    index: 31,
    category: KITCHEN,
    amenity: "Coffee machine",
    isSelected: false,
  },
  {
    index: 32,
    category: KITCHEN,
    amenity: "Minibar",
    isSelected: false,
  },
  {
    index: 33,
    category: KITCHEN,
    amenity: "Kitchenette",
    isSelected: false,
  },
  {
    index: 34,
    category: LIVING_AREA,
    amenity: "Seating Area",
    isSelected: false,
  },
  {
    index: 35,
    category: LIVING_AREA,
    amenity: "Sofa bed",
    isSelected: false,
  },
  {
    index: 36,
    category: LIVING_AREA,
    amenity: "Hardwood or parquet floors",
    isSelected: false,
  },
  {
    index: 37,
    category: LIVING_AREA,
    amenity: "Wardrobe or closet",
    isSelected: false,
  },
  {
    index: 38,
    category: LIVING_AREA,
    amenity: "Clothes rack",
    isSelected: false,
  },
  {
    index: 39,
    category: LIVING_AREA,
    amenity: "iPod dock",
    isSelected: false,
  },
  {
    index: 40,
    category: LIVING_AREA,
    amenity: "Dressing room",
    isSelected: false,
  },
  {
    index: 41,
    category: LIVING_AREA,
    amenity: "Board games/puzzles",
    isSelected: false,
  },
  {
    index: 42,
    category: LIVING_AREA,
    amenity: "Books, DVDs, or music for children",
    isSelected: false,
  },
  {
    index: 43,
    category: LIVING_AREA,
    amenity: "Balcony",
    isSelected: false,
  },
  {
    index: 44,
    category: LIVING_AREA,
    amenity: "Terrace",
    isSelected: false,
  },
  {
    index: 45,
    category: LIVING_AREA,
    amenity: "View",
    isSelected: false,
  },
  {
    index: 46,
    category: LIVING_AREA,
    amenity: "Garden view",
    isSelected: false,
  },
  {
    index: 47,
    category: LIVING_AREA,
    amenity: "Pool view",
    isSelected: false,
  },
  {
    index: 48,
    category: GENERAL,
    amenity: "Designated smoking area",
    isSelected: false,
  },
  {
    index: 49,
    category: GENERAL,
    amenity: "Air conditioning",
    isSelected: false,
  },
  {
    index: 50,
    category: GENERAL,
    amenity: "Soundproof rooms",
    isSelected: false,
  },
  {
    index: 51,
    category: GENERAL,
    amenity: "Family rooms",
    isSelected: false,
  },
  {
    index: 52,
    category: GENERAL,
    amenity: "Non-smoking rooms",
    isSelected: false,
  },
  {
    index: 53,
    category: GENERAL,
    amenity: "Outdoor swimming pool",
    isSelected: false,
  },
  {
    index: 54,
    category: GENERAL,
    amenity: "Indoor swimming pool",
    isSelected: false,
  },
  {
    index: 55,
    category: GENERAL,
    amenity: "Plunge pool",
    isSelected: false,
  },
  {
    index: 56,
    category: GENERAL,
    amenity: "Spa",
    isSelected: false,
  },
  {
    index: 57,
    category: GENERAL,
    amenity: "Open all year",
    isSelected: false,
  },
  {
    index: 58,
    category: GENERAL,
    amenity: "Free pool/beach towels",
    isSelected: false,
  },
  {
    index: 59,
    category: GENERAL,
    amenity: "Pool/beach towels (additional charge)",
    isSelected: false,
  },
  {
    index: 60,
    category: GENERAL,
    amenity: "Sun loungers or beach chairs",
    isSelected: false,
  },
  {
    index: 61,
    category: GENERAL,
    amenity: "Swim up bar",
    isSelected: false,
  },
  {
    index: 62,
    category: GENERAL,
    amenity: "Pool Bar",
    isSelected: false,
  },
  {
    index: 63,
    category: GENERAL,
    amenity: "Sun umbrellas",
    isSelected: false,
  },
  {
    index: 64,
    category: GENERAL,
    amenity: "Hot tub/Jacuzzi",
    isSelected: false,
  },
  {
    index: 65,
    category: GENERAL,
    amenity: "Non-smoking throughout",
    isSelected: false,
  },
  {
    index: 66,
    category: GENERAL,
    amenity: "Wake up service",
    isSelected: false,
  },
  {
    index: 67,
    category: GENERAL,
    amenity: "All ages welcome",
    isSelected: false,
  },
  {
    index: 68,
    category: GENERAL,
    amenity: "Pool with view",
    isSelected: false,
  },
  {
    index: 69,
    category: OUTDOORS,
    amenity: "Outdoor furniture",
    isSelected: false,
  },
  {
    index: 70,
    category: OUTDOORS,
    amenity: "Sun terrace",
    isSelected: false,
  },
  {
    index: 71,
    category: OUTDOORS,
    amenity: "Private beach area",
    isSelected: false,
  },
  {
    index: 72,
    category: OUTDOORS,
    amenity: "BBQ facilities",
    isSelected: false,
  },
  {
    index: 73,
    category: OUTDOORS,
    amenity: "Parking",
    isSelected: false,
  },
  {
    index: 74,
    category: OUTDOORS,
    amenity: "Shared kitchen",
    isSelected: false,
  },
  {
    index: 75,
    category: OUTDOORS,
    amenity: "Smoking area",
    isSelected: false,
  },
  {
    index: 76,
    category: OUTDOORS,
    amenity: "Garden",
    isSelected: false,
  },
  {
    index: 77,
    category: OUTDOORS,
    amenity: "Common area",
    isSelected: false,
  },
]
const facilitiesItem: T_Facility[] = [
  {
    index: 0,
    category: MOST_POPULAR,
    facility: "Bar",
    propertyId: null,
    isSelected: true,
  },
  {
    index: 1,
    category: MOST_POPULAR,
    facility: "Sauna",
    propertyId: null,
    isSelected: true,
  },
  {
    index: 2,
    category: MOST_POPULAR,
    facility: "Garden",
    propertyId: null,
    isSelected: true,
  },
  {
    index: 3,
    category: MOST_POPULAR,
    facility: "Terrace",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 4,
    category: MOST_POPULAR,
    facility: "Hot tub/Jacuzzi",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 5,
    category: MOST_POPULAR,
    facility: "Heating",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 6,
    category: MOST_POPULAR,
    facility: "Free WiFi",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 7,
    category: MOST_POPULAR,
    facility: "Air conditioning",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 8,
    category: MOST_POPULAR,
    facility: "Swimming pool",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 9,
    category: MOST_POPULAR,
    facility: "Beach",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 10,
    category: OUTDOORS,
    facility: "Beachfront",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 11,
    category: OUTDOORS,
    facility: "Outdoor furniture",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 12,
    category: OUTDOORS,
    facility: "Sun terrace",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 13,
    category: OUTDOORS,
    facility: "Private beach area",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 14,
    category: OUTDOORS,
    facility: "BBQ facilities",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 15,
    category: OUTDOORS,
    facility: "Parking",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 16,
    category: OUTDOORS,
    facility: "Shared kitchen",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 17,
    category: OUTDOORS,
    facility: "Smoking area",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 18,
    category: OUTDOORS,
    facility: "Garden",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 19,
    category: OUTDOORS,
    facility: "Common area",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 20,
    category: ACTIVITIES,
    facility: "Bicycle rental (additional charge)",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 21,
    category: ACTIVITIES,
    facility: "Happy hour",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 22,
    category: ACTIVITIES,
    facility: "Beach",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 23,
    category: ACTIVITIES,
    facility: "Snorkelling (additional charge)",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 24,
    category: ACTIVITIES,
    facility: "Diving (additional charge)",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 25,
    category: ACTIVITIES,
    facility: "Cycling",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 26,
    category: ACTIVITIES,
    facility: "Hiking (additional charge)",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 27,
    category: ACTIVITIES,
    facility: "Billiards",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 28,
    category: ACTIVITIES,
    facility: "Children's playground",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 29,
    category: ACTIVITIES,
    facility: "Nearby golf course (additional charge)",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 30,
    category: ACTIVITIES,
    facility: "Cooking class",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 31,
    category: ACTIVITIES,
    facility: "Tour or class about local culture",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 32,
    category: ACTIVITIES,
    facility: "Themed dinner nights",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 33,
    category: ACTIVITIES,
    facility: "Bike tours",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 34,
    category: ACTIVITIES,
    facility: "Walking tours",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 35,
    category: ACTIVITIES,
    facility: "Movie nights",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 36,
    category: ACTIVITIES,
    facility: "Beach sports",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 37,
    category: ACTIVITIES,
    facility: "Badminton equipment",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 38,
    category: ACTIVITIES,
    facility: "Water sport facilities on site",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 39,
    category: ACTIVITIES,
    facility: "Snorkelling",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 40,
    category: ACTIVITIES,
    facility: "Games room",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 41,
    category: ACTIVITIES,
    facility: "Fishing (additional charge)",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 42,
    category: ACTIVITIES,
    facility: "Table tennis",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 43,
    category: FOOD_DRINK,
    facility: "Snack bar",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 44,
    category: FOOD_DRINK,
    facility: "Bar",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 45,
    category: FOOD_DRINK,
    facility: "Restaurant",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 46,
    category: FOOD_DRINK,
    facility: "Happy hour",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 47,
    category: FOOD_DRINK,
    facility: "Free breakfast included",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 48,
    category: FOOD_DRINK,
    facility: "Breakfast (additional charge)",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 49,
    category: FOOD_DRINK,
    facility: "Special diet menus (on request)",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 50,
    category: FOOD_DRINK,
    facility: "Special diet menus (additional charge)",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 51,
    category: INTERNET,
    facility: "Free WiFi",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 52,
    category: INTERNET,
    facility: "WiFi (additional charge)",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 53,
    category: INTERNET,
    facility: "Starlink",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 54,
    category: INTERNET,
    facility: "Co-working space",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 55,
    category: PARKING,
    facility: "Private parking",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 56,
    category: PARKING,
    facility: "Street parking",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 57,
    category: PARKING,
    facility: "Motorbike parking",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 58,
    category: PARKING,
    facility: "Car park",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 59,
    category: PARKING,
    facility: "Parking garage",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 60,
    category: PARKING,
    facility: "Accessible parking",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 61,
    category: SERVICES,
    facility: "Shuttle service (Additional charge)",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 62,
    category: SERVICES,
    facility: "Luggage storage",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 63,
    category: SERVICES,
    facility: "Tour desk",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 64,
    category: SERVICES,
    facility: "Car hire (additional charge)",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 65,
    category: SERVICES,
    facility: "Packed lunches (additional charge)",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 66,
    category: SERVICES,
    facility: "Babysitting/child services (additional charge)",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 67,
    category: SERVICES,
    facility: "Airport shuttle (additional charge)",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 68,
    category: SERVICES,
    facility: "Free airport shuttle",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 69,
    category: SERVICES,
    facility: "Room service",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 70,
    category: SERVICES,
    facility: "Room service (additional charge)",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 71,
    category: RECEPTION_SERVICES,
    facility: "Invoice provided",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 72,
    category: RECEPTION_SERVICES,
    facility: "Lockers",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 73,
    category: RECEPTION_SERVICES,
    facility: "Private check-in/check-out",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 74,
    category: RECEPTION_SERVICES,
    facility: "Concierge service",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 75,
    category: RECEPTION_SERVICES,
    facility: "Luggage storage",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 76,
    category: RECEPTION_SERVICES,
    facility: "Express check-in/check-out",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 77,
    category: RECEPTION_SERVICES,
    facility: "24/7 check-in",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 78,
    category: SAFETY_SECURITY,
    facility: "24/7 security guard",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 79,
    category: SAFETY_SECURITY,
    facility: "Security guard at night",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 80,
    category: SAFETY_SECURITY,
    facility: "Fire extinguishers",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 81,
    category: SAFETY_SECURITY,
    facility: "CCTV outside property",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 82,
    category: SAFETY_SECURITY,
    facility: "CCTV in common areas",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 83,
    category: SAFETY_SECURITY,
    facility: "Safety deposit box",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 84,
    category: GENERAL,
    facility: "Designated smoking area",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 85,
    category: GENERAL,
    facility: "Air conditioning",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 86,
    category: GENERAL,
    facility: "Soundproof rooms",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 87,
    category: GENERAL,
    facility: "Family rooms",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 88,
    category: GENERAL,
    facility: "Non-smoking rooms",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 89,
    category: GENERAL,
    facility: "Outdoor swimming pool",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 90,
    category: GENERAL,
    facility: "Indoor swimming pool",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 91,
    category: GENERAL,
    facility: "Plunge pool",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 92,
    category: GENERAL,
    facility: "Spa",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 93,
    category: GENERAL,
    facility: "Open all year",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 94,
    category: GENERAL,
    facility: "Free pool/beach towels",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 95,
    category: GENERAL,
    facility: "Pool/beach towels (additional charge)",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 96,
    category: GENERAL,
    facility: "Sun loungers or beach chairs",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 97,
    category: GENERAL,
    facility: "Swim up bar",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 98,
    category: GENERAL,
    facility: "Pool Bar",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 99,
    category: GENERAL,
    facility: "Sun umbrellas",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 100,
    category: GENERAL,
    facility: "Hot tub/Jacuzzi",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 101,
    category: GENERAL,
    facility: "Non-smoking throughout",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 102,
    category: GENERAL,
    facility: "Wake up service",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 103,
    category: GENERAL,
    facility: "All ages welcome",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 104,
    category: GENERAL,
    facility: "Pool with view",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 105,
    category: GENERAL,
    facility: "Swimming pool toys",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 106,
    category: WELLNESS,
    facility: "Fitness area",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 107,
    category: WELLNESS,
    facility: "Yoga shala",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 108,
    category: WELLNESS,
    facility: "Fitness equipment",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 109,
    category: WELLNESS,
    facility: "Massage (additional charge)",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 110,
    category: WELLNESS,
    facility: "Massage",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 111,
    category: WELLNESS,
    facility: "Spa and wellness center (additional charge)",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 112,
    category: WELLNESS,
    facility: "Fitness locker rooms",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 113,
    category: WELLNESS,
    facility: "Yoga classes",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 114,
    category: WELLNESS,
    facility: "Fitness",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 115,
    category: WELLNESS,
    facility: "Couples massage (additional charge)",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 116,
    category: WELLNESS,
    facility: "Couples massage",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 117,
    category: WELLNESS,
    facility: "Spa/wellness packages (additional charge)",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 118,
    category: WELLNESS,
    facility: "Free spa facilities",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 119,
    category: WELLNESS,
    facility: "Free beauty Services",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 120,
    category: WELLNESS,
    facility: "Beauty Services (additional charge)",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 121,
    category: WELLNESS,
    facility: "Public Bath",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 122,
    category: WELLNESS,
    facility: "Public shower",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 123,
    category: WELLNESS,
    facility: "Open-air bath",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 124,
    category: WELLNESS,
    facility: "Massage",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 125,
    category: WELLNESS,
    facility: "Spa and wellness centre",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 126,
    category: WELLNESS,
    facility: "Fitness centre",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 127,
    category: WELLNESS,
    facility: "Gym",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 128,
    category: CLEANING_SERVICES,
    facility: "Daily housekeeping",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 129,
    category: CLEANING_SERVICES,
    facility: "Ironing service",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 130,
    category: CLEANING_SERVICES,
    facility: "Ironing service (additional charge)",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 131,
    category: CLEANING_SERVICES,
    facility: "Laundry",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 132,
    category: CLEANING_SERVICES,
    facility: "Laundry (additional charge)",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 133,
    category: BUSINESS_FACILITIES,
    facility: "Fax/photocopying (additional charge)",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 134,
    category: BUSINESS_FACILITIES,
    facility: "Fax/photocopying",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 135,
    category: BUSINESS_FACILITIES,
    facility: "Meeting/banquet facilities",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 136,
    category: ENTERTAINMENT,
    facility: "Kids' outdoor play equipment",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 137,
    category: ENTERTAINMENT,
    facility: "Indoor play area",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 138,
    category: ENTERTAINMENT,
    facility: "Board games/puzzles",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 139,
    category: ENTERTAINMENT,
    facility: "Board games/puzzles",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 140,
    category: ENTERTAINMENT,
    facility: "Babysitting/child services",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 141,
    category: ENTERTAINMENT,
    facility: "Babysitting/child services (additional charge)",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 142,
    category: ONSITE,
    facility: "Cash",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 143,
    category: ONSITE,
    facility: "Gcash",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 144,
    category: ONSITE,
    facility: "Visa",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 145,
    category: ONSITE,
    facility: "Mastercard",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 146,
    category: ONSITE,
    facility: "American Express",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 147,
    category: ONSITE,
    facility: "UnionPay",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 148,
    category: LANGUAGES,
    facility: "English",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 149,
    category: LANGUAGES,
    facility: "Filipino",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 150,
    category: LANGUAGES,
    facility: "Spanish",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 151,
    category: LANGUAGES,
    facility: "French",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 152,
    category: LANGUAGES,
    facility: "Chinese",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 153,
    category: LANGUAGES,
    facility: "Hebrew",
    propertyId: null,
    isSelected: false,
  },
  {
    index: 154,
    category: LANGUAGES,
    facility: "German",
    propertyId: null,
    isSelected: false,
  },
]

const seedProperties = async () => {
  try {
    console.log("Seeding properties...")
    const locations = await dbLocations.find({})
    const properties: T_Add_Property[] = [
      {
        status: E_Property_Status.LIVE,
        finishedSections: [
          "type",
          "wholePlaceType",
          "basicInfo",
          "location",
          "facilities",
          "units",
          "photos",
          "pricing",
          "policies",
        ],
        title: "Cozy Beachfront Villa",
        description:
          "Experience luxury and relaxation in our beautiful beachfront villa with stunning ocean views.",
        currency: "PHP",
        primaryLanguage: "English",
        photos: [],
        phone: "+1 (555) 123-4567",
        email: "bookings@cozybeachvilla.com",
        location: String(locations[0]?._id),
        checkInTime: "2023-07-15T15:00:00Z",
        checkOutTime: "2023-07-16T11:00:00Z",
        isLateCheckOutAllowed: true,
        lateCheckOutType: "Hourly",
        lateCheckOutValue: 20,
        termsAndConditions:
          "No pets allowed. No smoking inside the property. Quiet hours from 10 PM to 7 AM.",
        taxId: "123456789",
        taxId2: "987654321",
        companyLegalName: "Cozy Beach Rentals LLC",
        type: E_Property_Type.WHOLE_PLACE,
        wholeplaceType: E_Whole_Place_Property_Type.VILLA,
        facilities: [],
        policies: [],
        bookableUnits: [],
        reservations: [],
        createdAt: "2023-06-01T10:00:00Z",
        updatedAt: "2023-06-15T14:30:00Z",
      },
      {
        status: E_Property_Status.LIVE,
        finishedSections: [
          "type",
          "wholePlaceType",
          "basicInfo",
          "location",
          "facilities",
          "units",
          "photos",
          "pricing",
          "policies",
        ],
        title: "Mountain View Chalet",
        description:
          "Escape to our cozy chalet nestled in the mountains, offering breathtaking views and a serene environment.",
        currency: "PHP",
        primaryLanguage: "English",
        photos: [],
        phone: "+33 1 23 45 67 89",
        email: "reservations@mountainchalet.com",
        location: String(locations[1]?._id),
        checkInTime: "2023-07-20T16:00:00Z",
        checkOutTime: "2023-07-21T10:00:00Z",
        isLateCheckOutAllowed: false,
        lateCheckOutType: null,
        lateCheckOutValue: null,
        termsAndConditions:
          "No skiing inside. Fireplace usage instructions must be followed. Quiet hours from 11 PM to 7 AM.",
        taxId: "987654321",
        taxId2: "123456789",
        companyLegalName: "Alpine Retreats SARL",
        type: E_Property_Type.RESORT,
        wholeplaceType: null,
        facilities: [],
        policies: [],
        bookableUnits: [],
        reservations: [],
        createdAt: "2023-05-15T09:30:00Z",
        updatedAt: "2023-06-20T11:45:00Z",
      },
      {
        status: E_Property_Status.PENDING,
        finishedSections: [
          "Basic Info",
          "Photos",
          "Pricing",
          "Policies",
          "Amenities",
        ],
        title: "Urban Loft Apartment",
        description:
          "Experience city living at its finest in our modern loft apartment, located in the heart of the bustling downtown area.",
        currency: "PHP",
        primaryLanguage: "English",
        photos: [],
        phone: "+44 20 1234 5678",
        email: "bookings@urbanloft.co.uk",
        location: String(locations[2]?._id),
        checkInTime: "2023-08-01T14:00:00Z",
        checkOutTime: "2023-08-02T11:00:00Z",
        isLateCheckOutAllowed: true,
        lateCheckOutType: "Fixed",
        lateCheckOutValue: 30,
        termsAndConditions:
          "No parties or events. Respect neighbors' peace. Recycling is mandatory.",
        taxId: "555666777",
        taxId2: "888999000",
        companyLegalName: "City Stays Ltd",
        type: E_Property_Type.RESORT,
        wholeplaceType: null,
        facilities: [],
        policies: [],
        bookableUnits: [],
        reservations: [],
        createdAt: "2023-06-10T13:15:00Z",
        updatedAt: "2023-07-05T16:20:00Z",
      },
      {
        status: E_Property_Status.INCOMPLETE,
        finishedSections: [
          "Basic Info",
          "Photos",
          "Pricing",
          "Policies",
          "Amenities",
          "Location",
        ],
        title: "Seaside Bungalow Retreat",
        description:
          "Unwind in our charming seaside bungalow, offering direct beach access and stunning sunset views over the ocean.",
        currency: "PHP",
        primaryLanguage: "English",
        photos: [],
        phone: "+61 2 9876 5432",
        email: "stay@seasidebungalow.com.au",
        location: String(locations[3]?._id),
        checkInTime: "2023-09-01T14:00:00Z",
        checkOutTime: "2023-09-02T10:00:00Z",
        isLateCheckOutAllowed: true,
        lateCheckOutType: "Percentage",
        lateCheckOutValue: 50,
        termsAndConditions:
          "No loud music after 9 PM. Beach equipment provided must be returned clean. Respect marine life and local environment.",
        taxId: "123987456",
        taxId2: "789654123",
        companyLegalName: "Coastal Getaways Pty Ltd",
        type: E_Property_Type.HOMESTAY,
        wholeplaceType: null,
        facilities: [],
        policies: [],
        bookableUnits: [],
        reservations: [],
        createdAt: "2023-05-20T08:45:00Z",
        updatedAt: "2023-07-15T16:30:00Z",
      },
      {
        status: E_Property_Status.LIVE,
        finishedSections: [
          "type",
          "wholePlaceType",
          "basicInfo",
          "location",
          "facilities",
          "units",
          "photos",
          "pricing",
          "policies",
        ],
        title: "Rustic Farmhouse Getaway",
        description:
          "Experience authentic country living in our lovingly restored farmhouse, surrounded by rolling hills and organic gardens.",
        currency: "PHP",
        primaryLanguage: "English",
        photos: [],
        phone: "+1 (705) 123-4567",
        email: "bookings@rusticfarmstay.ca",
        location: String(locations[4]?._id),
        checkInTime: "2023-08-15T15:00:00Z",
        checkOutTime: "2023-08-16T11:00:00Z",
        isLateCheckOutAllowed: false,
        lateCheckOutType: null,
        lateCheckOutValue: null,
        termsAndConditions:
          "Guests are welcome to participate in farm activities. No outside food allowed due to organic farm policies. Quiet hours from 10 PM to 6 AM.",
        taxId: "456789123",
        taxId2: null,
        companyLegalName: "Green Acres Farm Stay Inc.",
        type: E_Property_Type.HOSTEL,
        wholeplaceType: null,
        facilities: [],
        policies: [],
        bookableUnits: [],
        reservations: [],
        createdAt: "2023-07-01T11:20:00Z",
        updatedAt: "2023-07-05T09:15:00Z",
      },
      {
        status: E_Property_Status.INCOMPLETE,
        finishedSections: [
          "Basic Info",
          "Photos",
          "Pricing",
          "Policies",
          "Amenities",
          "Location",
          "Calendar",
        ],
        title: "Luxury Treehouse Escape",
        description:
          "Indulge in a unique stay at our eco-friendly luxury treehouse, offering a perfect blend of nature and modern comforts.",
        currency: "PHP",
        primaryLanguage: "English",
        photos: [],
        phone: "+81 3-1234-5678",
        email: "info@luxurytreehouse.jp",
        location: String(locations[5]?._id),
        checkInTime: "2023-10-01T15:00:00Z",
        checkOutTime: "2023-10-02T11:00:00Z",
        isLateCheckOutAllowed: true,
        lateCheckOutType: "Hourly",
        lateCheckOutValue: 5000,
        termsAndConditions:
          "Minimum age requirement of 12 years. No smoking anywhere on the property. Respect wildlife and follow all safety guidelines provided.",
        taxId: "987654321",
        taxId2: "123456789",
        companyLegalName: "Eco Luxe Stays K.K.",
        type: E_Property_Type.RESORT,
        wholeplaceType: null,
        facilities: [],
        policies: [],
        bookableUnits: [],
        reservations: [],
        createdAt: "2023-06-15T10:30:00Z",
        updatedAt: "2023-07-20T14:45:00Z",
      },
      {
        status: E_Property_Status.PENDING,
        finishedSections: [
          "Basic Info",
          "Photos",
          "Pricing",
          "Policies",
          "Amenities",
          "Location",
          "Calendar",
          "Booking Settings",
        ],
        title: "Historic City Center Apartment",
        description:
          "Step back in time in our beautifully restored 19th-century apartment, located in the heart of the old town, walking distance to major attractions.",
        currency: "PHP",
        primaryLanguage: "English",
        photos: [],
        phone: "+39 06 1234 5678",
        email: "booking@historiccenterapt.it",
        location: String(locations[6]?._id),
        checkInTime: "2023-09-15T14:00:00Z",
        checkOutTime: "2023-09-16T11:00:00Z",
        isLateCheckOutAllowed: true,
        lateCheckOutType: "Fixed",
        lateCheckOutValue: 40,
        termsAndConditions:
          "Respect quiet hours from 10 PM to 8 AM. No parties or events. Please be mindful of the historical features of the apartment.",
        taxId: "123456789",
        taxId2: "987654321",
        companyLegalName: "Centro Storico Soggiorni S.r.l.",
        type: E_Property_Type.HOMESTAY,
        wholeplaceType: null,
        facilities: [],
        policies: [],
        bookableUnits: [],
        reservations: [],
        createdAt: "2023-05-10T09:30:00Z",
        updatedAt: "2023-07-25T16:45:00Z",
      },
      {
        status: E_Property_Status.LIVE,
        finishedSections: [
          "type",
          "wholePlaceType",
          "basicInfo",
          "location",
          "facilities",
          "units",
          "photos",
          "pricing",
          "policies",
        ],
        title: "Modern City View Penthouse",
        description:
          "Experience luxury living in this top-floor penthouse with stunning city views, high-end amenities, and spacious rooms.",
        currency: "PHP",
        primaryLanguage: "English",
        photos: [],
        phone: "+1 212 555 1234",
        email: "contact@cityviewpenthouse.com",
        location: String(locations[7]?._id),
        checkInTime: "2024-01-01T15:00:00Z",
        checkOutTime: "2024-01-02T11:00:00Z",
        isLateCheckOutAllowed: false,
        lateCheckOutType: "None",
        lateCheckOutValue: 0,
        termsAndConditions:
          "No pets allowed. Maximum occupancy is 4 people. No smoking inside the apartment.",
        taxId: "987654321",
        taxId2: "123456789",
        companyLegalName: "Skyline Living LLC",
        type: E_Property_Type.HOSTEL,
        wholeplaceType: null,
        facilities: [],
        policies: [],
        bookableUnits: [],
        reservations: [],
        createdAt: "2023-12-01T10:00:00Z",
        updatedAt: "2023-12-05T14:30:00Z",
      },
      {
        status: E_Property_Status.PENDING,
        finishedSections: [
          "Basic Info",
          "Photos",
          "Pricing",
          "Policies",
          "Amenities",
          "Location",
          "Calendar",
        ],
        title: "Cozy Beachfront Cottage",
        description:
          "Wake up to the sound of the waves in this charming beachfront cottage with private access to the beach.",
        currency: "PHP",
        primaryLanguage: "English",
        photos: [],
        phone: "+34 654 321 987",
        email: "info@beachfrontcottage.es",
        location: String(locations[8]?._id),
        checkInTime: "2024-05-01T16:00:00Z",
        checkOutTime: "2024-05-02T10:00:00Z",
        isLateCheckOutAllowed: true,
        lateCheckOutType: "Fixed",
        lateCheckOutValue: 30,
        termsAndConditions:
          "No loud noise after 10 PM. Only small pets allowed.",
        taxId: "567890123",
        taxId2: "234567890",
        companyLegalName: "Costa Azul S.A.",
        type: E_Property_Type.HOTEL,
        wholeplaceType: null,
        facilities: [],
        policies: [],
        bookableUnits: [],
        reservations: [],
        createdAt: "2023-09-20T12:00:00Z",
        updatedAt: "2023-09-20T12:00:00Z",
      },
      {
        status: E_Property_Status.INCOMPLETE,
        finishedSections: [
          "Basic Info",
          "Photos",
          "Pricing",
          "Policies",
          "Amenities",
          "Location",
          "Calendar",
          "Booking Settings",
        ],
        title: "Mountain View Chalet",
        description:
          "This luxurious chalet offers breathtaking mountain views, a private hot tub, and a cozy fireplace for ultimate relaxation.",
        currency: "PHP",
        primaryLanguage: "English",
        photos: [],
        phone: "+41 79 123 45 67",
        email: "info@mountainviewchalet.ch",
        location: String(locations[9]?._id),
        checkInTime: "2024-02-01T14:00:00Z",
        checkOutTime: "2024-02-02T11:00:00Z",
        isLateCheckOutAllowed: false,
        lateCheckOutType: "None",
        lateCheckOutValue: 0,
        termsAndConditions: "No smoking inside. Pets allowed on request.",
        taxId: "112233445",
        taxId2: "998877665",
        companyLegalName: "Alpenblick GmbH",
        type: E_Property_Type.HOMESTAY,
        wholeplaceType: null,
        facilities: [],
        policies: [],
        bookableUnits: [],
        reservations: ["507f1f77bcf86cd799439131"],
        createdAt: "2023-11-01T08:30:00Z",
        updatedAt: "2023-11-01T08:30:00Z",
      },
      {
        status: E_Property_Status.LIVE,
        finishedSections: [
          "type",
          "wholePlaceType",
          "basicInfo",
          "location",
          "facilities",
          "units",
          "photos",
          "pricing",
          "policies",
        ],
        title: "Secluded Forest Retreat",
        description:
          "Escape the hustle and bustle with a stay in this peaceful, secluded forest retreat, complete with a private sauna and hiking trails.",
        currency: "PHP",
        primaryLanguage: "English",
        photos: [],
        phone: "+44 20 7946 0958",
        email: "contact@forestretreat.co.uk",
        location: String(locations[10]?._id),
        checkInTime: "2024-03-10T16:00:00Z",
        checkOutTime: "2024-03-11T10:00:00Z",
        isLateCheckOutAllowed: true,
        lateCheckOutType: "Flexible",
        lateCheckOutValue: 50,
        termsAndConditions:
          "Respect wildlife. Leave the sauna clean. No outdoor fires allowed.",
        taxId: "765432109",
        taxId2: "456789012",
        companyLegalName: "Wilderness Escapes Ltd.",
        type: E_Property_Type.RESORT,
        wholeplaceType: null,
        facilities: [],
        policies: [],
        bookableUnits: [],
        reservations: ["507f1f77bcf86cd799439132"],
        createdAt: "2023-07-12T15:20:00Z",
        updatedAt: "2023-07-12T15:20:00Z",
      },
      {
        status: E_Property_Status.LIVE,
        finishedSections: [
          "type",
          "wholePlaceType",
          "basicInfo",
          "location",
          "facilities",
          "units",
          "photos",
          "pricing",
          "policies",
        ],
        title: "Urban Loft in Downtown",
        description:
          "Stylish urban loft located in the heart of downtown, close to shopping, restaurants, and entertainment venues.",
        currency: "PHP",
        primaryLanguage: "English",
        photos: [],
        phone: "+1 514 555 6789",
        email: "info@urbanloftmontreal.com",
        location: String(locations[11]?._id),
        checkInTime: "2024-04-10T15:00:00Z",
        checkOutTime: "2024-04-11T11:00:00Z",
        isLateCheckOutAllowed: false,
        lateCheckOutType: "None",
        lateCheckOutValue: 0,
        termsAndConditions:
          "No parties allowed. No smoking inside. Please be respectful of neighbors.",
        taxId: "321654987",
        taxId2: "654987321",
        companyLegalName: "Loft Urbain Inc.",
        type: E_Property_Type.HOTEL,
        wholeplaceType: null,
        facilities: [],
        policies: [],
        bookableUnits: [],
        reservations: [],
        createdAt: "2023-06-25T09:00:00Z",
        updatedAt: "2023-06-25T09:00:00Z",
      },
      {
        status: E_Property_Status.LIVE,
        finishedSections: [
          "type",
          "wholePlaceType",
          "basicInfo",
          "location",
          "facilities",
          "units",
          "photos",
          "pricing",
          "policies",
        ],
        title: "Luxury Villa with Ocean View",
        description:
          "This stunning luxury villa offers panoramic ocean views, infinity pool, and an outdoor entertainment area, perfect for a family getaway.",
        currency: "PHP",
        primaryLanguage: "English",
        photos: [],
        phone: "+61 2 1234 5678",
        email: "info@oceanviewvilla.com.au",
        location: String(locations[12]?._id),
        checkInTime: "2024-06-01T15:00:00Z",
        checkOutTime: "2024-06-02T11:00:00Z",
        isLateCheckOutAllowed: true,
        lateCheckOutType: "Flexible",
        lateCheckOutValue: 60,
        termsAndConditions:
          "No pets allowed. Smoking is prohibited inside. Please use pool responsibly.",
        taxId: "876543210",
        taxId2: "123987456",
        companyLegalName: "Seaside Villas Pty Ltd.",
        type: E_Property_Type.HOMESTAY,
        wholeplaceType: null,
        facilities: [],
        policies: [],
        bookableUnits: [],
        reservations: [],
        createdAt: "2023-10-15T14:00:00Z",
        updatedAt: "2023-10-20T10:00:00Z",
      },
      {
        status: E_Property_Status.LIVE,
        finishedSections: [
          "type",
          "wholePlaceType",
          "basicInfo",
          "location",
          "facilities",
          "units",
          "photos",
          "pricing",
          "policies",
        ],
        title: "Stylish Urban Studio",
        description:
          "Modern and cozy urban studio apartment located near trendy shops, cafes, and public transport for easy city exploration.",
        currency: "PHP",
        primaryLanguage: "English",
        photos: [],
        phone: "+49 30 1234 5678",
        email: "hello@urbanstudio.de",
        location: String(locations[13]?._id),
        checkInTime: "2024-07-15T15:00:00Z",
        checkOutTime: "2024-07-16T11:00:00Z",
        isLateCheckOutAllowed: false,
        lateCheckOutType: "None",
        lateCheckOutValue: 0,
        termsAndConditions:
          "No smoking allowed. Maximum of 2 people. Quiet hours from 10 PM.",
        taxId: "554433221",
        taxId2: "667788990",
        companyLegalName: "City Studios GmbH",
        type: E_Property_Type.HOSTEL,
        wholeplaceType: null,
        facilities: [],
        policies: [],
        bookableUnits: [],
        reservations: [],
        createdAt: "2023-11-01T10:30:00Z",
        updatedAt: "2023-11-01T10:30:00Z",
      },
      {
        status: E_Property_Status.INCOMPLETE,
        finishedSections: [
          "Basic Info",
          "Photos",
          "Pricing",
          "Policies",
          "Amenities",
          "Location",
          "Calendar",
          "Booking Settings",
        ],
        title: "Charming Country Cottage",
        description:
          "This cozy cottage offers a peaceful retreat in the countryside, featuring a lovely garden and a charming wood-burning stove.",
        currency: "PHP",
        primaryLanguage: "English",
        photos: [],
        phone: "+1 415 555 9876",
        email: "reservations@countrycottage.com",
        location: String(locations[14]?._id),
        checkInTime: "2024-08-05T16:00:00Z",
        checkOutTime: "2024-08-06T10:00:00Z",
        isLateCheckOutAllowed: true,
        lateCheckOutType: "Fixed",
        lateCheckOutValue: 25,
        termsAndConditions:
          "Pets allowed for an additional fee. Quiet hours from 9 PM to 7 AM.",
        taxId: "112233444",
        taxId2: "556677889",
        companyLegalName: "Countryside Getaways Inc.",
        type: E_Property_Type.HOTEL,
        wholeplaceType: null,
        facilities: [],
        policies: [],
        bookableUnits: [],
        reservations: [],
        createdAt: "2023-09-10T14:45:00Z",
        updatedAt: "2023-09-10T14:45:00Z",
      },
    ]

    const bookableUnits: T_Bookable_Units[] = [
      {
        category: "Whole-Place",
        title: "Deluxe King Suite",
        subtitle: "Studio",
        unitNote: null,
        description:
          "The Deluxe King Suite offers comfort with a king-sized bed, premium linens, a spacious bathroom, and a sitting area with a beautiful view.",
        totalSize: 45,
        isHaveSharedBathRoom: "No",
        isHaveSharedAmenities: "Yes",
        isSmokingAllowed: "No",
        bed: "King-sized bed",
        unitPrice: null,
        pricePerDates: [],
        amenities: [],
        photos: [],
        isPrivate: true,
        maxGuests: 2,
        adultsIncluded: 2,
        childrenIncluded: 0,
        bedRooms: [],
        livingRooms: [],
        bedroomStudio: [],
        singleLivingRoom: null,
        singleBedRoom: null,
        isMultiRoomUnit: false,
        numBedRooms: "1",
        numBathRooms: "1",
        bedConfigs: [],
        qty: 5,
        qtyIds: [],
        daysCanCancel: 7,
        reviews: [],
        createdAt: "2024-11-01T10:00:00Z",
        updatedAt: "2024-11-19T16:00:00Z",
        deletedAt: null,
      },
      {
        category: "Bed",
        title: "Executive Suite",
        subtitle: "A modern suite with a king-sized bed and office space.",
        unitNote: null,
        description:
          "The Executive Suite features a luxurious king-sized bed, a spacious work desk, high-speed internet, and a modern bathroom. Ideal for business travelers looking for comfort and productivity.",
        totalSize: 50,
        isHaveSharedBathRoom: "No",
        isHaveSharedAmenities: "Yes",
        isSmokingAllowed: "No",
        bed: "King-sized bed",
        unitPrice: null,
        pricePerDates: [],
        amenities: [],
        photos: [],
        isPrivate: true,
        maxGuests: 2,
        adultsIncluded: 2,
        childrenIncluded: 0,
        bedRooms: [],
        livingRooms: [],
        bedroomStudio: [],
        singleLivingRoom: null,
        singleBedRoom: null,
        isMultiRoomUnit: false,
        numBedRooms: "1",
        numBathRooms: "1",
        bedConfigs: [],
        qty: 3,
        qtyIds: [],
        daysCanCancel: 7,
        reviews: [],
        createdAt: "2024-11-05T09:00:00Z",
        updatedAt: "2024-11-19T15:00:00Z",
        deletedAt: null,
      },
      {
        category: "Room",
        title: "Premium Ocean View Suite",
        subtitle:
          "A suite with breathtaking ocean views and luxurious amenities.",
        unitNote: null,
        description:
          "The Premium Ocean View Suite offers stunning views of the ocean, a king-sized bed, a spacious living area, and modern amenities for an unforgettable stay.",
        totalSize: 60,
        isHaveSharedBathRoom: "No",
        isHaveSharedAmenities: "Yes",
        isSmokingAllowed: "No",
        bed: "King-sized bed",
        unitPrice: null,
        pricePerDates: [],
        amenities: [],
        photos: [],
        isPrivate: true,
        maxGuests: 2,
        adultsIncluded: 2,
        childrenIncluded: 0,
        bedRooms: [],
        livingRooms: [],
        bedroomStudio: [],
        singleLivingRoom: null,
        singleBedRoom: null,
        isMultiRoomUnit: false,
        numBedRooms: "1",
        numBathRooms: "1",
        bedConfigs: [],
        qty: 4,
        qtyIds: [],
        daysCanCancel: 7,
        reviews: [],
        createdAt: "2024-11-10T08:30:00Z",
        updatedAt: "2024-11-19T16:30:00Z",
        deletedAt: null,
      },
      {
        category: "Room",
        title: "Mountain Retreat Suite",
        subtitle: "A cozy suite with a fireplace and views of the mountains.",
        unitNote: null,
        description:
          "The Mountain Retreat Suite offers a peaceful escape with stunning mountain views, a cozy fireplace, and a comfortable king-sized bed for a relaxing stay.",
        totalSize: 55,
        isHaveSharedBathRoom: "No",
        isHaveSharedAmenities: "Yes",
        isSmokingAllowed: "No",
        bed: "King-sized bed",
        unitPrice: null,
        pricePerDates: [],
        amenities: [],
        photos: [],
        isPrivate: true,
        maxGuests: 2,
        adultsIncluded: 2,
        childrenIncluded: 0,
        bedRooms: [],
        livingRooms: [],
        bedroomStudio: [],
        singleLivingRoom: null,
        singleBedRoom: null,
        isMultiRoomUnit: false,
        numBedRooms: "1",
        numBathRooms: "1",
        bedConfigs: [],
        qty: 6,
        qtyIds: [],
        daysCanCancel: 7,
        reviews: [],
        createdAt: "2024-11-12T11:00:00Z",
        updatedAt: "2024-11-19T17:00:00Z",
        deletedAt: null,
      },
      {
        category: "Room",
        title: "Royal Garden Suite",
        subtitle:
          "An elegant suite with private garden access and a luxurious king-sized bed.",
        unitNote: null,
        description:
          "The Royal Garden Suite offers a serene retreat with a private garden terrace, a king-sized bed, a luxurious bathroom, and top-tier amenities for relaxation.",
        totalSize: 70,
        isHaveSharedBathRoom: "No",
        isHaveSharedAmenities: "No",
        isSmokingAllowed: "No",
        bed: "King-sized bed",
        unitPrice: null,
        pricePerDates: [],
        amenities: [],
        photos: [],
        isPrivate: true,
        maxGuests: 2,
        adultsIncluded: 2,
        childrenIncluded: 0,
        bedRooms: [],
        livingRooms: [],
        bedroomStudio: [],
        singleLivingRoom: null,
        singleBedRoom: null,
        isMultiRoomUnit: false,
        numBedRooms: "1",
        numBathRooms: "1",
        bedConfigs: [],
        qty: 2,
        qtyIds: [],
        daysCanCancel: 7,
        reviews: [],
        createdAt: "2024-11-15T10:00:00Z",
        updatedAt: "2024-11-19T18:00:00Z",
        deletedAt: null,
      },
      {
        category: "Room",
        title: "Skyline Loft Suite",
        subtitle:
          "A stylish suite with panoramic city views and modern amenities.",
        unitNote: null,
        description:
          "The Skyline Loft Suite features breathtaking city views, a comfortable king-sized bed, a spacious layout, and all the amenities needed for a luxurious stay in the heart of the city.",
        totalSize: 65,
        isHaveSharedBathRoom: "No",
        isHaveSharedAmenities: "Yes",
        isSmokingAllowed: "No",
        bed: "King-sized bed",
        unitPrice: null,
        pricePerDates: [],
        amenities: [],
        photos: [],
        isPrivate: true,
        maxGuests: 2,
        adultsIncluded: 2,
        childrenIncluded: 0,
        bedRooms: [],
        livingRooms: [],
        bedroomStudio: [],
        singleLivingRoom: null,
        singleBedRoom: null,
        isMultiRoomUnit: false,
        numBedRooms: "1",
        numBathRooms: "1",
        bedConfigs: [],
        qty: 3,
        qtyIds: [],
        daysCanCancel: 7,
        reviews: [],
        createdAt: "2024-11-16T11:30:00Z",
        updatedAt: "2024-11-19T19:00:00Z",
        deletedAt: null,
      },
      {
        category: "Room",
        title: "Luxury Penthouse Suite",
        subtitle:
          "An extravagant penthouse with floor-to-ceiling windows and panoramic views.",
        unitNote: null,
        description:
          "The Luxury Penthouse Suite offers unparalleled views, a king-sized bed, a spacious living area, and luxury amenities including a Jacuzzi and a private elevator for exclusive access.",
        totalSize: 120,
        isHaveSharedBathRoom: "No",
        isHaveSharedAmenities: "No",
        isSmokingAllowed: "No",
        bed: "King-sized bed",
        unitPrice: null,
        pricePerDates: [],
        amenities: [],
        photos: [],
        isPrivate: true,
        maxGuests: 4,
        adultsIncluded: 2,
        childrenIncluded: 2,
        bedRooms: [],
        livingRooms: [],
        bedroomStudio: [],
        singleLivingRoom: null,
        singleBedRoom: null,
        isMultiRoomUnit: false,
        numBedRooms: "2",
        numBathRooms: "2",
        bedConfigs: [],
        qty: 1,
        qtyIds: [],
        daysCanCancel: 14,
        reviews: [],
        createdAt: "2024-11-18T09:00:00Z",
        updatedAt: "2024-11-19T20:00:00Z",
        deletedAt: null,
      },
      {
        category: "Room",
        title: "Forest View Chalet",
        subtitle:
          "A rustic chalet with a stunning view of the forest and a cozy atmosphere.",
        unitNote: null,
        description:
          "The Forest View Chalet offers a charming wooden interior, a king-sized bed, a private balcony overlooking the forest, and all the necessary amenities for a peaceful getaway.",
        totalSize: 50,
        isHaveSharedBathRoom: "No",
        isHaveSharedAmenities: "Yes",
        isSmokingAllowed: "Yes",
        bed: "King-sized bed",
        unitPrice: null,
        pricePerDates: [],
        amenities: [],
        photos: [],
        isPrivate: true,
        maxGuests: 2,
        adultsIncluded: 2,
        childrenIncluded: 0,
        bedRooms: [],
        livingRooms: [],
        bedroomStudio: [],
        singleLivingRoom: null,
        singleBedRoom: null,
        isMultiRoomUnit: false,
        numBedRooms: "1",
        numBathRooms: "1",
        bedConfigs: [],
        qty: 4,
        qtyIds: [],
        daysCanCancel: 7,
        reviews: [],
        createdAt: "2024-11-19T10:30:00Z",
        updatedAt: "2024-11-19T20:30:00Z",
        deletedAt: null,
      },
      {
        category: "Room",
        title: "Sunset Lagoon Suite",
        subtitle:
          "A serene suite with breathtaking sunset views and a private hot tub.",
        unitNote: null,
        description:
          "The Sunset Lagoon Suite offers unparalleled views of the lagoon, a king-sized bed, a private hot tub, and modern amenities for a relaxing and romantic escape.",
        totalSize: 80,
        isHaveSharedBathRoom: "No",
        isHaveSharedAmenities: "Yes",
        isSmokingAllowed: "No",
        bed: "King-sized bed",
        unitPrice: null,
        pricePerDates: [],
        amenities: [],
        photos: [],
        isPrivate: true,
        maxGuests: 2,
        adultsIncluded: 2,
        childrenIncluded: 0,
        bedRooms: [],
        livingRooms: [],
        bedroomStudio: [],
        singleLivingRoom: null,
        singleBedRoom: null,
        isMultiRoomUnit: false,
        numBedRooms: "1",
        numBathRooms: "1",
        bedConfigs: [],
        qty: 3,
        qtyIds: [],
        daysCanCancel: 7,
        reviews: [],
        createdAt: "2024-11-20T08:00:00Z",
        updatedAt: "2024-11-20T18:00:00Z",
        deletedAt: null,
      },
      {
        category: "Room",
        title: "Countryside Retreat Suite",
        subtitle:
          "A tranquil suite surrounded by nature with a comfortable king-sized bed.",
        unitNote: null,
        description:
          "The Countryside Retreat Suite is perfect for nature lovers, with panoramic views of the countryside, a king-sized bed, and a peaceful ambiance ideal for unwinding.",
        totalSize: 55,
        isHaveSharedBathRoom: "No",
        isHaveSharedAmenities: "No",
        isSmokingAllowed: "No",
        bed: "King-sized bed",
        unitPrice: null,
        pricePerDates: [],
        amenities: [],
        photos: [],
        isPrivate: true,
        maxGuests: 2,
        adultsIncluded: 2,
        childrenIncluded: 0,
        bedRooms: [],
        livingRooms: [],
        bedroomStudio: [],
        singleLivingRoom: null,
        singleBedRoom: null,
        isMultiRoomUnit: false,
        numBedRooms: "1",
        numBathRooms: "1",
        bedConfigs: [],
        qty: 4,
        qtyIds: [],
        daysCanCancel: 7,
        reviews: [],
        createdAt: "2024-11-19T09:30:00Z",
        updatedAt: "2024-11-20T19:00:00Z",
        deletedAt: null,
      },
      {
        category: "Room",
        title: "Ocean Breeze Suite",
        subtitle:
          "A tranquil suite with sweeping ocean views and a spacious balcony.",
        unitNote: null,
        description:
          "The Ocean Breeze Suite offers breathtaking views of the ocean, a king-sized bed, a private balcony, and luxury amenities for a relaxing beachfront retreat.",
        totalSize: 85,
        isHaveSharedBathRoom: "No",
        isHaveSharedAmenities: "Yes",
        isSmokingAllowed: "No",
        bed: "King-sized bed",
        unitPrice: null,
        pricePerDates: [],
        amenities: [],
        photos: [],
        isPrivate: true,
        maxGuests: 2,
        adultsIncluded: 2,
        childrenIncluded: 0,
        bedRooms: [],
        livingRooms: [],
        bedroomStudio: [],
        singleLivingRoom: null,
        singleBedRoom: null,
        isMultiRoomUnit: false,
        numBedRooms: "1",
        numBathRooms: "1",
        bedConfigs: [],
        qty: 2,
        qtyIds: [],
        daysCanCancel: 7,
        reviews: [],
        createdAt: "2024-11-20T11:00:00Z",
        updatedAt: "2024-11-20T19:30:00Z",
        deletedAt: null,
      },
      {
        category: "Room",
        title: "Mountain View Chalet",
        subtitle:
          "A cozy chalet with panoramic views of the surrounding mountains.",
        unitNote: null,
        description:
          "The Mountain View Chalet provides a rustic escape with breathtaking views of the mountains, a king-sized bed, and a welcoming atmosphere for a peaceful getaway.",
        totalSize: 60,
        isHaveSharedBathRoom: "No",
        isHaveSharedAmenities: "No",
        isSmokingAllowed: "No",
        bed: "King-sized bed",
        unitPrice: null,
        pricePerDates: [],
        amenities: [],
        photos: [],
        isPrivate: true,
        maxGuests: 2,
        adultsIncluded: 2,
        childrenIncluded: 0,
        bedRooms: [],
        livingRooms: [],
        bedroomStudio: [],
        singleLivingRoom: null,
        singleBedRoom: null,
        isMultiRoomUnit: false,
        numBedRooms: "1",
        numBathRooms: "1",
        bedConfigs: [],
        qty: 5,
        qtyIds: [],
        daysCanCancel: 7,
        reviews: [],
        createdAt: "2024-11-19T14:00:00Z",
        updatedAt: "2024-11-20T21:00:00Z",
        deletedAt: null,
      },
      {
        category: "Room",
        title: "Skyline Loft Suite",
        subtitle: "A chic, modern loft with stunning city skyline views.",
        unitNote: null,
        description:
          "The Skyline Loft Suite offers a luxurious loft space with floor-to-ceiling windows providing breathtaking views of the city skyline, a king-sized bed, and sleek, modern decor for a sophisticated stay.",
        totalSize: 95,
        isHaveSharedBathRoom: "No",
        isHaveSharedAmenities: "Yes",
        isSmokingAllowed: "No",
        bed: "King-sized bed",
        unitPrice: null,
        pricePerDates: [],
        amenities: [],
        photos: [],
        isPrivate: true,
        maxGuests: 2,
        adultsIncluded: 2,
        childrenIncluded: 0,
        bedRooms: [],
        livingRooms: [],
        bedroomStudio: [],
        singleLivingRoom: null,
        singleBedRoom: null,
        isMultiRoomUnit: false,
        numBedRooms: "1",
        numBathRooms: "1",
        bedConfigs: [],
        qty: 3,
        qtyIds: [],
        daysCanCancel: 7,
        reviews: [],
        createdAt: "2024-11-20T12:30:00Z",
        updatedAt: "2024-11-20T20:00:00Z",
        deletedAt: null,
      },
      {
        category: "Room",
        title: "Serenity Garden Suite",
        subtitle:
          "A peaceful retreat surrounded by lush gardens and water features.",
        unitNote: null,
        description:
          "The Serenity Garden Suite is a peaceful haven with tranquil garden views, a king-sized bed, and calming natural decor, perfect for a relaxing and rejuvenating experience.",
        totalSize: 70,
        isHaveSharedBathRoom: "No",
        isHaveSharedAmenities: "No",
        isSmokingAllowed: "No",
        bed: "King-sized bed",
        unitPrice: null,
        pricePerDates: [],
        amenities: [],
        photos: [],
        isPrivate: true,
        maxGuests: 2,
        adultsIncluded: 2,
        childrenIncluded: 0,
        bedRooms: [],
        livingRooms: [],
        bedroomStudio: [],
        singleLivingRoom: null,
        singleBedRoom: null,
        isMultiRoomUnit: false,
        numBedRooms: "1",
        numBathRooms: "1",
        bedConfigs: [],
        qty: 4,
        qtyIds: [],
        daysCanCancel: 7,
        reviews: [],
        createdAt: "2024-11-20T13:00:00Z",
        updatedAt: "2024-11-20T20:30:00Z",
        deletedAt: null,
      },
      {
        category: "Room",
        title: "Royal Forest Lodge",
        subtitle: "Studio",
        unitNote: null,
        description:
          "The Royal Forest Lodge is nestled in a serene forest setting, offering privacy, a king-sized bed, and a peaceful retreat with beautiful nature views and exclusive amenities.",
        totalSize: 100,
        isHaveSharedBathRoom: "No",
        isHaveSharedAmenities: "No",
        isSmokingAllowed: "No",
        bed: "King-sized bed",
        unitPrice: null,
        pricePerDates: [],
        amenities: [],
        photos: [],
        isPrivate: true,
        maxGuests: 2,
        adultsIncluded: 2,
        childrenIncluded: 0,
        bedRooms: [],
        livingRooms: [],
        bedroomStudio: [],
        singleLivingRoom: null,
        singleBedRoom: null,
        isMultiRoomUnit: false,
        numBedRooms: "1",
        numBathRooms: "1",
        bedConfigs: [],
        qty: 2,
        qtyIds: [],
        daysCanCancel: 7,
        reviews: [],
        createdAt: "2024-11-20T14:00:00Z",
        updatedAt: "2024-11-20T21:00:00Z",
        deletedAt: null,
      },
    ]

    const bedRooms = [
      {
        roomName: "Bed Room 1",
        beds: [
          { name: "Single Bed", qty: 0 },
          { name: "Twin Bed", qty: 0 },
          { name: "Double Bed", qty: 0 },
          { name: "Queen Bed", qty: 0 },
          { name: "Queen XL Bed", qty: 0 },
          { name: "King Bed", qty: 0 },
          { name: "King XL Bed", qty: 0 },
          { name: "Sofa Bed", qty: 0 },
          { name: "Bunk Bed", qty: 0 },
          { name: "Lot (Baby Bed)", qty: 0 },
          { name: "Crib", qty: 0 },
          { name: "Infant Bed", qty: 0 },
          { name: "Toddler Bed", qty: 0 },
          { name: "Playpen", qty: 0 },
          { name: "Bath", qty: 0 },
        ],
      },
    ]

    const livingRooms = [
      {
        roomName: "Living Room 1",
        beds: [
          { name: "Single Bed", qty: 0 },
          { name: "Twin Bed", qty: 0 },
          { name: "Double Bed", qty: 0 },
          { name: "Queen Bed", qty: 0 },
          { name: "Queen XL Bed", qty: 0 },
          { name: "King Bed", qty: 0 },
          { name: "King XL Bed", qty: 0 },
          { name: "Sofa Bed", qty: 0 },
          { name: "Bunk Bed", qty: 0 },
          { name: "Lot (Baby Bed)", qty: 0 },
          { name: "Crib", qty: 0 },
          { name: "Infant Bed", qty: 0 },
          { name: "Toddler Bed", qty: 0 },
          { name: "Playpen", qty: 0 },
          { name: "Bath", qty: 0 },
        ],
      },
    ]
    const pricing: T_Unit_Price[] = [
      {
        baseRate: 2000,
        baseRateMaxCapacity: 5,
        maximumCapacity: 15,
        pricePerAdditionalPerson: 200,
        discountedWeeklyRate: 200,
        discountedMonthlyRate: 500,
        createdAt: String(Date.now()),
        updatedAt: null,
        deletedAt: null,
      },
      {
        baseRate: 2050,
        baseRateMaxCapacity: 6,
        maximumCapacity: 16,
        pricePerAdditionalPerson: 210,
        discountedWeeklyRate: 250,
        discountedMonthlyRate: 600,
        createdAt: String(Date.now()),
        updatedAt: null,
        deletedAt: null,
      },
      {
        baseRate: 2100,
        baseRateMaxCapacity: 7,
        maximumCapacity: 15,
        pricePerAdditionalPerson: 220,
        discountedWeeklyRate: 300,
        discountedMonthlyRate: 700,
        createdAt: String(Date.now()),
        updatedAt: null,
        deletedAt: null,
      },
      {
        baseRate: 2150,
        baseRateMaxCapacity: 5,
        maximumCapacity: 16,
        pricePerAdditionalPerson: 230,
        discountedWeeklyRate: 350,
        discountedMonthlyRate: 500,
        createdAt: String(Date.now()),
        updatedAt: null,
        deletedAt: null,
      },
      {
        baseRate: 2200,
        baseRateMaxCapacity: 6,
        maximumCapacity: 15,
        pricePerAdditionalPerson: 240,
        discountedWeeklyRate: 200,
        discountedMonthlyRate: 600,
        createdAt: String(Date.now()),
        updatedAt: null,
        deletedAt: null,
      },
      {
        baseRate: 2250,
        baseRateMaxCapacity: 7,
        maximumCapacity: 16,
        pricePerAdditionalPerson: 250,
        discountedWeeklyRate: 250,
        discountedMonthlyRate: 700,
        createdAt: String(Date.now()),
        updatedAt: null,
        deletedAt: null,
      },
      {
        baseRate: 2300,
        baseRateMaxCapacity: 5,
        maximumCapacity: 15,
        pricePerAdditionalPerson: 260,
        discountedWeeklyRate: 300,
        discountedMonthlyRate: 500,
        createdAt: String(Date.now()),
        updatedAt: null,
        deletedAt: null,
      },
      {
        baseRate: 2350,
        baseRateMaxCapacity: 6,
        maximumCapacity: 16,
        pricePerAdditionalPerson: 270,
        discountedWeeklyRate: 350,
        discountedMonthlyRate: 600,
        createdAt: String(Date.now()),
        updatedAt: null,
        deletedAt: null,
      },
      {
        baseRate: 2400,
        baseRateMaxCapacity: 7,
        maximumCapacity: 15,
        pricePerAdditionalPerson: 280,
        discountedWeeklyRate: 200,
        discountedMonthlyRate: 700,
        createdAt: String(Date.now()),
        updatedAt: null,
        deletedAt: null,
      },
      {
        baseRate: 2450,
        baseRateMaxCapacity: 5,
        maximumCapacity: 16,
        pricePerAdditionalPerson: 290,
        discountedWeeklyRate: 250,
        discountedMonthlyRate: 500,
        createdAt: String(Date.now()),
        updatedAt: null,
        deletedAt: null,
      },
      {
        baseRate: 2500,
        baseRateMaxCapacity: 6,
        maximumCapacity: 15,
        pricePerAdditionalPerson: 300,
        discountedWeeklyRate: 300,
        discountedMonthlyRate: 600,
        createdAt: String(Date.now()),
        updatedAt: null,
        deletedAt: null,
      },
      {
        baseRate: 2550,
        baseRateMaxCapacity: 7,
        maximumCapacity: 16,
        pricePerAdditionalPerson: 310,
        discountedWeeklyRate: 350,
        discountedMonthlyRate: 700,
        createdAt: String(Date.now()),
        updatedAt: null,
        deletedAt: null,
      },
      {
        baseRate: 2600,
        baseRateMaxCapacity: 5,
        maximumCapacity: 15,
        pricePerAdditionalPerson: 320,
        discountedWeeklyRate: 200,
        discountedMonthlyRate: 500,
        createdAt: String(Date.now()),
        updatedAt: null,
        deletedAt: null,
      },
      {
        baseRate: 2650,
        baseRateMaxCapacity: 6,
        maximumCapacity: 16,
        pricePerAdditionalPerson: 330,
        discountedWeeklyRate: 250,
        discountedMonthlyRate: 600,
        createdAt: String(Date.now()),
        updatedAt: null,
        deletedAt: null,
      },
      {
        baseRate: 2700,
        baseRateMaxCapacity: 7,
        maximumCapacity: 15,
        pricePerAdditionalPerson: 340,
        discountedWeeklyRate: 300,
        discountedMonthlyRate: 700,
        createdAt: String(Date.now()),
        updatedAt: null,
        deletedAt: null,
      },
    ]

    const getUsers = await dbUsers.find({})
    const getUserIds = getUsers.map((user) => user._id)
    const unitRates = await dbUnitPrices.insertMany(pricing)
    const newBookableUnits = bookableUnits.map((unit, i) => {
      if (unit.category === "Room") {
        return {
          ...unit,
          offerBy: getUserIds[0],
          bedRooms:
            unit.subtitle.toLowerCase() !== "studio" ? bedRooms : [...bedRooms],
        }
      } else if (unit.category === "Whole-Place") {
        return { ...unit, offerBy: getUserIds[0], livingRooms: livingRooms }
      } else if (unit.category === "Bed") {
        return { ...unit, offerBy: getUserIds[0] }
      }
    })

    const bookableUnitsType =
      await dbBookableUnitTypes.insertMany(newBookableUnits)
    bookableUnitsType.forEach(async (unit, i) => {
      await dbBookableUnitTypes.findByIdAndUpdate(unit._id, {
        $set: {
          unitPrice: unitRates[i]?._id,
        },
      })
      const amenities = await dbAmenities.insertMany(amenitiesItem)
      amenities.forEach(async (amenity) => {
        await dbBookableUnitTypes.updateOne(
          { _id: unit._id },
          {
            $push: { amenities: amenity._id },
          }
        )
      })
    })
    bookableUnitsType.forEach(async (unit) => {
      const photos = await dbPhotos.insertMany([
        {
          isMain: true,
          activityId: null,
          bookableUnitId: unit._id,
          propertyId: null,
          rentalId: null,
          createdAt: String(Date.now()),
          key: unit.title + "-1",
          thumbKey: unit.title + "-1",
          tags: "photo",
          description: unit.title + " description",
        },
        {
          isMain: true,
          activityId: null,
          bookableUnitId: unit._id,
          propertyId: null,
          rentalId: null,
          createdAt: String(Date.now()),
          key: unit.title + "-2",
          thumbKey: unit.title + "-2",
          tags: "photo",
          description: unit.title + " description",
        },
        {
          isMain: true,
          activityId: null,
          bookableUnitId: unit._id,
          propertyId: null,
          rentalId: null,
          createdAt: String(Date.now()),
          key: unit.title + "-3",
          thumbKey: unit.title + "-3",
          tags: "photo",
          description: unit.title + " description",
        },
        {
          isMain: true,
          activityId: null,
          bookableUnitId: unit._id,
          propertyId: null,
          rentalId: null,
          createdAt: String(Date.now()),
          key: unit.title + "-4",
          thumbKey: unit.title + "-4",
          tags: "photo",
          description: unit.title + " description",
        },
        {
          isMain: true,
          activityId: null,
          bookableUnitId: unit._id,
          propertyId: null,
          rentalId: null,
          createdAt: String(Date.now()),
          key: unit.title + "-5",
          thumbKey: unit.title + "-5",
          tags: "photo",
          description: unit.title + " description",
        },
      ])
      photos.forEach(async (photo) => {
        await dbBookableUnitTypes.updateOne(
          { _id: unit._id },
          {
            $push: { photos: photo._id },
          }
        )
      })
      for (let i = 0; i < Number(unit?.qty); i++) {
        await dbBookableUnitTypes.updateOne(
          { _id: unit._id },
          {
            $push: {
              qtyIds: {
                name: `${String(unit?.title ?? unit?.subtitle) + " " + (i + 1)}`,
              },
            },
          }
        )
      }
    })
    const getBookableUnits = await dbBookableUnitTypes.find({})
    const getBookableUnitsIds = getBookableUnits.map((unit) => unit._id)

    const newProperties = properties.map((property, index) => ({
      ...property,
      offerBy: getUserIds[0],
      bookableUnits: getBookableUnitsIds[index],
    }))

    await dbProperties.insertMany(newProperties)
    const getProperties = await dbProperties.find({})
    getProperties.forEach(async (item) => {
      const facilities = await dbFacilities.insertMany(facilitiesItem)
      facilities.forEach(async (facility) => {
        await dbProperties.updateOne(
          { _id: item._id },
          {
            $push: { facilities: facility._id },
          }
        )
      })
    })
    getProperties.forEach(async (property) => {
      const photos = await dbPhotos.insertMany([
        {
          isMain: true,
          activityId: null,
          bookableUnitId: null,
          propertyId: property._id,
          rentalId: null,
          createdAt: String(Date.now()),
          key: property.title + "-1",
          thumbKey: property.title + "-1",
          tags: "photo",
          description: property.title + " description",
        },
        {
          isMain: true,
          activityId: null,
          bookableUnitId: null,
          propertyId: property._id,
          rentalId: null,
          createdAt: String(Date.now()),
          key: property.title + "-2",
          thumbKey: property.title + "-2",
          tags: "photo",
          description: property.title + " description",
        },
        {
          isMain: true,
          activityId: null,
          bookableUnitId: null,
          propertyId: property._id,
          rentalId: null,
          createdAt: String(Date.now()),
          key: property.title + "-3",
          thumbKey: property.title + "-3",
          tags: "photo",
          description: property.title + " description",
        },
        {
          isMain: true,
          activityId: null,
          bookableUnitId: null,
          propertyId: property._id,
          rentalId: null,
          createdAt: String(Date.now()),
          key: property.title + "-4",
          thumbKey: property.title + "-4",
          tags: "photo",
          description: property.title + " description",
        },
        {
          isMain: true,
          activityId: null,
          bookableUnitId: null,
          propertyId: property._id,
          rentalId: null,
          createdAt: String(Date.now()),
          key: property.title + "-5",
          thumbKey: property.title + "-5",
          tags: "photo",
          description: property.title + " description",
        },
      ])
      photos.forEach(async (photo) => {
        await dbProperties.updateOne(
          { _id: property._id },
          {
            $push: { photos: photo._id },
          }
        )
      })
    })

    getProperties.forEach(async (property) => {
      const newPolicies = await dbPolicies.insertMany(policiesItem)
      newPolicies.forEach(async (policy) => {
        await dbProperties.updateOne(
          { _id: property._id },
          {
            $push: { policies: policy._id },
          }
        )
      })
    })
    console.log("Properties seeded successfully!")
  } catch (error) {
    console.error("Error seeding properties:", error)
  }
}

export default seedProperties
