import { T_Location } from "@repo/contract-2/address-location"
import {
  E_Rental_Category,
  E_Rental_Vehicle_Fuel,
  E_Rental_Vehicle_Transmission,
  T_Rental,
  T_Rental_AddOns,
  T_Rental_Details,
  T_Rental_Price,
  Z_Rental,
} from "@repo/contract-2/rentals"
import {
  dbLocations,
  dbPhotos,
  dbRentalAddOns,
  dbRentalDetails,
  dbRentalRates,
  dbRentals,
  dbUsers,
} from "@repo/database"
import mongoose from "mongoose"

const locations: T_Location[] = [
  {
    city: "Pilar",
    streetAddress: "Lagoon View Drive",
    barangay: "Barangay 9",
    longitude: 126.145699,
    latitude: 9.768868,
    howToGetThere: "Take a boat to Socorro and explore the lagoon trail.",
    createdAt: "2024-11-27T02:34:07.098352",
    updatedAt: null,
    deletedAt: null,
  },
  {
    city: "Santa Monica",
    streetAddress: "Beachside Avenue",
    barangay: "Barangay 10",
    longitude: 126.324115,
    latitude: 9.972537,
    howToGetThere: "Travel by tricycle and stop at Santa Monica's main beach.",
    createdAt: "2024-11-27T02:34:07.098379",
    updatedAt: null,
    deletedAt: null,
  },
  {
    city: "Del Carmen",
    streetAddress: "Mangrove Trail",
    barangay: "Barangay 11",
    longitude: 126.131578,
    latitude: 9.885924,
    howToGetThere: "Explore the Del Carmen mangrove forest by boat.",
    createdAt: "2024-11-27T02:34:07.098394",
    updatedAt: null,
    deletedAt: null,
  },
  {
    city: "General Luna",
    streetAddress: "Surfer's Paradise Lane",
    barangay: "Barangay 12",
    longitude: 126.37088,
    latitude: 9.730856,
    howToGetThere: "Head to General Luna for the famous Cloud 9 surf spot.",
    createdAt: "2024-11-27T02:34:07.098406",
    updatedAt: null,
    deletedAt: null,
  },
  {
    city: "Burgos",
    streetAddress: "Cliffside Road",
    barangay: "Barangay 13",
    longitude: 126.051503,
    latitude: 9.870095,
    howToGetThere: "Drive along Burgos' main road to reach the cliffs.",
    createdAt: "2024-11-27T02:34:07.098418",
    updatedAt: null,
    deletedAt: null,
  },
  {
    city: "Pilar",
    streetAddress: "Hidden Cove Drive",
    barangay: "Barangay 14",
    longitude: 126.250678,
    latitude: 9.842321,
    howToGetThere: "Follow the signs to Pilar's secret coves.",
    createdAt: "2024-11-27T02:34:07.098429",
    updatedAt: null,
    deletedAt: null,
  },
  {
    city: "Dapa",
    streetAddress: "Fisherman's Lane",
    barangay: "Barangay 15",
    longitude: 126.312789,
    latitude: 9.914567,
    howToGetThere: "Take a boat from General Luna to Dapa port.",
    createdAt: "2024-11-27T02:34:07.098440",
    updatedAt: null,
    deletedAt: null,
  },
  {
    city: "San Isidro",
    streetAddress: "Hilltop Road",
    barangay: "Barangay 16",
    longitude: 126.191234,
    latitude: 9.785123,
    howToGetThere: "Hike through San Isidro's scenic hilltop trails.",
    createdAt: "2024-11-27T02:34:07.098451",
    updatedAt: null,
    deletedAt: null,
  },
  {
    city: "San Isidro",
    streetAddress: "Hilltop Road",
    barangay: "Barangay 16",
    longitude: 126.191234,
    latitude: 9.785123,
    howToGetThere: "Hike through San Isidro's scenic hilltop trails.",
    createdAt: "2024-11-27T02:34:07.098451",
    updatedAt: null,
    deletedAt: null,
  },
  {
    city: "San Isidro",
    streetAddress: "Hilltop Road",
    barangay: "Barangay 16",
    longitude: 126.191234,
    latitude: 9.785123,
    howToGetThere: "Hike through San Isidro's scenic hilltop trails.",
    createdAt: "2024-11-27T02:34:07.098451",
    updatedAt: null,
    deletedAt: null,
  },
  {
    city: "San Isidro",
    streetAddress: "Hilltop Road",
    barangay: "Barangay 16",
    longitude: 126.191234,
    latitude: 9.785123,
    howToGetThere: "Hike through San Isidro's scenic hilltop trails.",
    createdAt: "2024-11-27T02:34:07.098451",
    updatedAt: null,
    deletedAt: null,
  },
  {
    city: "San Isidro",
    streetAddress: "Hilltop Road",
    barangay: "Barangay 16",
    longitude: 126.191234,
    latitude: 9.785123,
    howToGetThere: "Hike through San Isidro's scenic hilltop trails.",
    createdAt: "2024-11-27T02:34:07.098451",
    updatedAt: null,
    deletedAt: null,
  },
  {
    city: "San Isidro",
    streetAddress: "Hilltop Road",
    barangay: "Barangay 16",
    longitude: 126.191234,
    latitude: 9.785123,
    howToGetThere: "Hike through San Isidro's scenic hilltop trails.",
    createdAt: "2024-11-27T02:34:07.098451",
    updatedAt: null,
    deletedAt: null,
  },
  {
    city: "San Isidro",
    streetAddress: "Hilltop Road",
    barangay: "Barangay 16",
    longitude: 126.191234,
    latitude: 9.785123,
    howToGetThere: "Hike through San Isidro's scenic hilltop trails.",
    createdAt: "2024-11-27T02:34:07.098451",
    updatedAt: null,
    deletedAt: null,
  },
  {
    city: "San Isidro",
    streetAddress: "Hilltop Road",
    barangay: "Barangay 16",
    longitude: 126.191234,
    latitude: 9.785123,
    howToGetThere: "Hike through San Isidro's scenic hilltop trails.",
    createdAt: "2024-11-27T02:34:07.098451",
    updatedAt: null,
    deletedAt: null,
  },
]
const rentalDetailsItem: T_Rental_Details[] = [
  {
    engineCapacityLiter: 4.5,
    engineCapacityCc: 4500,
    condition: "Excellent",
    exteriorColor: "White",
    interiorColor: "Beige",
    seatingCapacity: 8,
    weightCapacityKg: 1000,
    isRegistered: "Yes",
    createdAt: String(Date.now()),
    updatedAt: null,
    deletedAt: null,
  },
  {
    engineCapacityLiter: 2.0,
    engineCapacityCc: 2000,
    condition: "Excellent",
    exteriorColor: "Black",
    interiorColor: "Gray",
    seatingCapacity: 5,
    weightCapacityKg: 400,
    isRegistered: "Yes",
    createdAt: String(Date.now()),
    updatedAt: null,
    deletedAt: null,
  },
  {
    engineCapacityLiter: 2.2,
    engineCapacityCc: 2200,
    condition: "Excellent",
    exteriorColor: "White",
    interiorColor: "Black",
    seatingCapacity: 12,
    weightCapacityKg: 1200,
    isRegistered: "Yes",
    createdAt: String(Date.now()),
    updatedAt: null,
    deletedAt: null,
  },
  {
    engineCapacityLiter: 5.7,
    engineCapacityCc: 5700,
    condition: "Good",
    exteriorColor: "Blue",
    interiorColor: "Black",
    seatingCapacity: 5,
    weightCapacityKg: 1500,
    isRegistered: "Yes",
    createdAt: "2022-05-15T00:00:00.000Z",
    updatedAt: "2024-11-10T06:50:00.000Z",
    deletedAt: null,
  },
  {
    engineCapacityLiter: 0.15,
    engineCapacityCc: 150,
    condition: "Excellent",
    exteriorColor: "Blue",
    interiorColor: "Green",
    seatingCapacity: 2,
    weightCapacityKg: 150,
    isRegistered: "Yes",
    createdAt: String(Date.now()),
    updatedAt: null,
    deletedAt: null,
  },
  {
    engineCapacityLiter: 2.8,
    engineCapacityCc: 2800,
    condition: "Good",
    exteriorColor: "Red",
    interiorColor: null,
    seatingCapacity: 2,
    weightCapacityKg: 300,
    isRegistered: "Yes",
    createdAt: String(Date.now()),
    updatedAt: null,
    deletedAt: null,
  },
  {
    engineCapacityLiter: 2.0,
    engineCapacityCc: 2000,
    condition: "Excellent",
    exteriorColor: "White",
    interiorColor: null,
    seatingCapacity: 2,
    weightCapacityKg: 300,
    isRegistered: "Yes",
    createdAt: String(Date.now()),
    updatedAt: null,
    deletedAt: null,
  },
  {
    engineCapacityLiter: 2.1,
    engineCapacityCc: 2100,
    condition: "Excellent",
    exteriorColor: "Black",
    interiorColor: null,
    seatingCapacity: 2,
    weightCapacityKg: 200,
    isRegistered: "Yes",
    createdAt: String(Date.now()),
    updatedAt: null,
    deletedAt: null,
  },
  {
    engineCapacityLiter: 0.883,
    engineCapacityCc: 883,
    condition: "Excellent",
    exteriorColor: "Black",
    interiorColor: null,
    seatingCapacity: 2,
    weightCapacityKg: 200,
    isRegistered: "Yes",
    createdAt: String(Date.now()),
    updatedAt: null,
    deletedAt: null,
  },
  {
    engineCapacityLiter: 3.2,
    engineCapacityCc: 3200,
    condition: "Excellent",
    exteriorColor: "Silver",
    interiorColor: null,
    seatingCapacity: 7,
    weightCapacityKg: 200,
    isRegistered: "Yes",
    createdAt: String(Date.now()),
    updatedAt: null,
    deletedAt: null,
  },
  {
    engineCapacityLiter: null,
    engineCapacityCc: 400,
    condition: "Excellent",
    exteriorColor: "",
    interiorColor: "",
    seatingCapacity: null,
    weightCapacityKg: null,
    isRegistered: "No",
    createdAt: String(Date.now()),
    updatedAt: null,
    deletedAt: null,
  },
  {
    engineCapacityLiter: null,
    engineCapacityCc: null,
    condition: "Excellent",
    exteriorColor: "",
    interiorColor: "",
    seatingCapacity: null,
    weightCapacityKg: null,
    isRegistered: "No",
    createdAt: String(Date.now()),
    updatedAt: null,
    deletedAt: null,
  },
  {
    engineCapacityLiter: null,
    engineCapacityCc: null,
    condition: "Excellent",
    exteriorColor: "",
    interiorColor: "",
    seatingCapacity: null,
    weightCapacityKg: null,
    isRegistered: "No",
    createdAt: String(Date.now()),
    updatedAt: null,
    deletedAt: null,
  },
  {
    engineCapacityLiter: null,
    engineCapacityCc: null,
    condition: "Excellent",
    exteriorColor: "",
    interiorColor: "",
    seatingCapacity: null,
    weightCapacityKg: null,
    isRegistered: "No",
    createdAt: String(Date.now()),
    updatedAt: null,
    deletedAt: null,
  },
  {
    engineCapacityLiter: null,
    engineCapacityCc: null,
    condition: "Excellent",
    exteriorColor: "",
    interiorColor: "",
    seatingCapacity: null,
    weightCapacityKg: null,
    isRegistered: "No",
    createdAt: String(Date.now()),
    updatedAt: null,
    deletedAt: null,
  },
]

const rentalPriceItem: T_Rental_Price[] = [
  {
    dayRate: 3920,
    requiredDeposit: 980,
    adminBookingCharge: 980,
    createdAt: String(Date.now()),
    updatedAt: null,
    deletedAt: null,
  },
  {
    dayRate: 3500,
    requiredDeposit: 875,
    adminBookingCharge: 875,
    createdAt: String(Date.now()),
    updatedAt: null,
    deletedAt: null,
  },
  {
    dayRate: 4500,
    requiredDeposit: 1125,
    adminBookingCharge: 1125,
    createdAt: String(Date.now()),
    updatedAt: null,
    deletedAt: null,
  },
  {
    dayRate: 5000,
    requiredDeposit: 1250,
    adminBookingCharge: 1250,
    createdAt: String(Date.now()),
    updatedAt: null,
    deletedAt: null,
  },
  {
    dayRate: 1500,
    requiredDeposit: 375,
    adminBookingCharge: 375,
    createdAt: String(Date.now()),
    updatedAt: null,
    deletedAt: null,
  },
  {
    dayRate: 4200,
    requiredDeposit: 1050,
    adminBookingCharge: 1050,
    createdAt: String(Date.now()),
    updatedAt: null,
    deletedAt: null,
  },
  {
    dayRate: 3920,
    requiredDeposit: 980,
    adminBookingCharge: 980,
    createdAt: String(Date.now()),
    updatedAt: null,
    deletedAt: null,
  },
  {
    dayRate: 4500,
    requiredDeposit: 1125,
    adminBookingCharge: 1125,
    createdAt: String(Date.now()),
    updatedAt: null,
    deletedAt: null,
  },
  {
    dayRate: 5000,
    requiredDeposit: 1250,
    adminBookingCharge: 1250,
    createdAt: String(Date.now()),
    updatedAt: null,
    deletedAt: null,
  },
  {
    dayRate: 3500,
    requiredDeposit: 875,
    adminBookingCharge: 875,
    createdAt: String(Date.now()),
    updatedAt: null,
    deletedAt: null,
  },
  {
    dayRate: 4200,
    requiredDeposit: 1050,
    adminBookingCharge: 1050,
    createdAt: String(Date.now()),
    updatedAt: null,
    deletedAt: null,
  },
  {
    dayRate: 4800,
    requiredDeposit: 1200,
    adminBookingCharge: 1200,
    createdAt: String(Date.now()),
    updatedAt: null,
    deletedAt: null,
  },
  {
    dayRate: 5500,
    requiredDeposit: 1375,
    adminBookingCharge: 1375,
    createdAt: String(Date.now()),
    updatedAt: null,
    deletedAt: null,
  },
  {
    dayRate: 4200,
    requiredDeposit: 1050,
    adminBookingCharge: 1050,
    createdAt: String(Date.now()),
    updatedAt: null,
    deletedAt: null,
  },
  {
    dayRate: 4500,
    requiredDeposit: 1125,
    adminBookingCharge: 1125,
    createdAt: String(Date.now()),
    updatedAt: null,
    deletedAt: null,
  },
]

const addOns: T_Rental_AddOns[] = [
  {
    roofRack: true,
    boardRack: true,
    babySeat: false,
    dashCam: true,
    includesHelmet: false,
    others: "",
  },
  {
    roofRack: true,
    boardRack: true,
    babySeat: false,
    dashCam: true,
    includesHelmet: false,
    others: "",
  },
  {
    roofRack: true,
    boardRack: true,
    babySeat: false,
    dashCam: true,
    includesHelmet: false,
    others: "",
  },
  {
    roofRack: true,
    boardRack: true,
    babySeat: false,
    dashCam: true,
    includesHelmet: false,
    others: "",
  },
  {
    roofRack: true,
    boardRack: true,
    babySeat: false,
    dashCam: true,
    includesHelmet: false,
    others: "",
  },
  {
    roofRack: false,
    boardRack: false,
    babySeat: false,
    dashCam: false,
    includesHelmet: true,
    others: "",
  },
  {
    roofRack: false,
    boardRack: false,
    babySeat: false,
    dashCam: false,
    includesHelmet: true,
    others: "",
  },
  {
    roofRack: false,
    boardRack: false,
    babySeat: false,
    dashCam: false,
    includesHelmet: true,
    others: "",
  },
  {
    roofRack: false,
    boardRack: false,
    babySeat: false,
    dashCam: false,
    includesHelmet: true,
    others: "",
  },
  {
    roofRack: false,
    boardRack: false,
    babySeat: false,
    dashCam: false,
    includesHelmet: true,
    others: "",
  },
  {
    roofRack: false,
    boardRack: false,
    babySeat: false,
    dashCam: false,
    includesHelmet: true,
    others: "Water",
  },
  {
    roofRack: false,
    boardRack: false,
    babySeat: false,
    dashCam: false,
    includesHelmet: true,
    others: "Water",
  },
  {
    roofRack: false,
    boardRack: false,
    babySeat: false,
    dashCam: false,
    includesHelmet: true,
    others: "Water",
  },
  {
    roofRack: false,
    boardRack: false,
    babySeat: false,
    dashCam: false,
    includesHelmet: true,
    others: "Water",
  },
  {
    roofRack: false,
    boardRack: false,
    babySeat: false,
    dashCam: false,
    includesHelmet: true,
    others: "Water",
  },
]

const seedRentals = async () => {
  try {
    console.log("Seeding rentals...")

    const rentalsData: T_Rental[] = [
      {
        details: null,
        pricing: null,
        host: null,
        category: E_Rental_Category.Car,
        make: "Toyota",
        modelBadge: "Land Cruiser",
        bodyType: "SUV",
        fuel: E_Rental_Vehicle_Fuel.Petrol,
        transmission: E_Rental_Vehicle_Transmission.Manual,
        year: "2020",
        rentalNote: "Ideal for off-road adventures.",
        qty: 3,
        addOns: null,
        photos: [],
        location: null,
        status: "Live",
        finishedSections: [
          "basicInfo",
          "details",
          "addOns",
          "photos",
          "pricing",
          "location",
        ],
        pricePerDates: [],
        reviews: [],
        updatedAt: "2024-11-20T08:45:00.000Z",
        qtyIds: [],
        daysCanCancel: 5,
      },
      {
        details: null,
        pricing: null,
        host: null,
        category: E_Rental_Category.Car,
        make: "Honda",
        modelBadge: "Accord",
        bodyType: "Pickup",
        fuel: E_Rental_Vehicle_Fuel.Petrol,
        transmission: null,
        year: "2021",
        rentalNote: "Perfect for city commutes with excellent fuel efficiency.",
        qty: 4,
        addOns: null,
        photos: [],
        location: null,
        status: "Live",
        finishedSections: [
          "basicInfo",
          "details",
          "addOns",
          "photos",
          "pricing",
          "location",
        ],
        pricePerDates: [],
        reviews: [],
        updatedAt: "2024-11-18T09:00:00.000Z",
        qtyIds: [],
        daysCanCancel: 3,
      },
      {
        details: null,
        pricing: null,
        host: null,
        category: E_Rental_Category.Car,
        make: "Ford",
        modelBadge: "Transit",
        bodyType: "Sedan",
        fuel: E_Rental_Vehicle_Fuel.Diesel,
        transmission: null,
        year: "2023",
        rentalNote:
          "Spacious and comfortable for large groups or family trips.",
        qty: 2,
        addOns: null,
        photos: [],
        location: null,
        status: "Live",
        finishedSections: [
          "basicInfo",
          "details",
          "addOns",
          "photos",
          "pricing",
          "location",
        ],
        reviews: [],
        updatedAt: "2024-10-25T07:30:00.000Z",
        qtyIds: [],
        pricePerDates: [],
        daysCanCancel: 2,
      },
      {
        details: null,
        pricing: null,
        host: null,
        category: E_Rental_Category.Car,
        make: "Ram",
        modelBadge: "1500",
        bodyType: "Sedan",
        fuel: null,
        transmission: null,
        year: "2022",
        rentalNote: "A powerful pickup for hauling and towing.",
        qty: 3,
        addOns: null,
        photos: [],
        location: null,
        status: "Live",
        finishedSections: [
          "basicInfo",
          "details",
          "addOns",
          "photos",
          "pricing",
          "location",
        ],
        pricePerDates: [],
        reviews: [],
        updatedAt: "2024-11-10T06:50:00.000Z",
        qtyIds: [],
        daysCanCancel: 6,
      },
      {
        details: null,
        pricing: null,
        host: null,
        category: E_Rental_Category.Car,
        make: "Yamaha",
        modelBadge: "FZ",
        bodyType: "SUV",
        fuel: null,
        transmission: E_Rental_Vehicle_Transmission.Manual,
        year: "2023",
        rentalNote: "Compact and perfect for navigating through traffic.",
        qty: 6,
        addOns: null,
        photos: [],
        location: null,
        status: "Live",
        finishedSections: [
          "basicInfo",
          "details",
          "addOns",
          "photos",
          "pricing",
          "location",
        ],
        pricePerDates: [],
        reviews: [],
        updatedAt: "2024-10-20T08:20:00.000Z",
        qtyIds: [],
        daysCanCancel: 3,
      },
      {
        details: null,
        pricing: null,
        host: null,
        category: E_Rental_Category.Motorbike,
        make: "Chevrolet",
        modelBadge: "Trailblazer",
        bodyType: null,
        fuel: E_Rental_Vehicle_Fuel.Diesel,
        transmission: null,
        year: "2021",
        rentalNote: "Explore the outdoors with comfort and power.",
        qty: 2,
        addOns: null,
        photos: [],
        location: null,
        status: "Live",
        finishedSections: [
          "basicInfo",
          "details",
          "addOns",
          "photos",
          "pricing",
          "location",
        ],
        pricePerDates: [],
        reviews: [],
        updatedAt: "2024-09-15T07:00:00.000Z",
        qtyIds: [],
        daysCanCancel: 5,
      },
      {
        details: null,
        pricing: null,
        host: null,
        category: E_Rental_Category.Motorbike,
        make: "BMW",
        modelBadge: "5 Series",
        bodyType: null,
        fuel: E_Rental_Vehicle_Fuel.Petrol,
        transmission: null,
        year: "2022",
        rentalNote: "Luxury and performance in a sleek sedan.",
        qty: 4,
        addOns: null,
        photos: [],
        location: null,
        status: "Live",
        finishedSections: [
          "basicInfo",
          "details",
          "addOns",
          "photos",
          "pricing",
          "location",
        ],
        pricePerDates: [],
        reviews: [],
        updatedAt: "2024-11-21T12:30:00.000Z",
        qtyIds: [],
        daysCanCancel: 2,
      },
      {
        details: null,
        pricing: null,
        host: null,
        category: E_Rental_Category.Motorbike,
        make: "Mercedes",
        modelBadge: "V-Class",
        bodyType: null,
        fuel: E_Rental_Vehicle_Fuel.Diesel,
        transmission: null,
        year: "2022",
        rentalNote: "Elegant and spacious for high-end family trips.",
        qty: 3,
        addOns: null,
        photos: [],
        location: null,
        status: "Live",
        finishedSections: [
          "basicInfo",
          "details",
          "addOns",
          "photos",
          "pricing",
          "location",
        ],
        pricePerDates: [],
        reviews: [],
        updatedAt: "2024-11-19T10:45:00.000Z",
        qtyIds: [],
        daysCanCancel: 2,
      },
      {
        details: null,
        pricing: null,
        host: null,
        category: E_Rental_Category.Motorbike,
        make: "Harley-Davidson",
        modelBadge: "Iron 883",
        bodyType: null,
        fuel: null,
        transmission: E_Rental_Vehicle_Transmission.Manual,
        year: "2021",
        rentalNote: "Experience the freedom of the open road.",
        qty: 2,
        addOns: null,
        photos: [],
        location: null,
        status: "Live",
        finishedSections: [
          "basicInfo",
          "details",
          "addOns",
          "photos",
          "pricing",
          "location",
        ],
        pricePerDates: [],
        reviews: [],
        updatedAt: "2024-11-01T11:15:00.000Z",
        qtyIds: [],
        daysCanCancel: 4,
      },
      {
        details: null,
        pricing: null,
        host: null,
        category: E_Rental_Category.Motorbike,
        make: "Mitsubishi",
        modelBadge: "Pajero",
        bodyType: null,
        fuel: E_Rental_Vehicle_Fuel.Diesel,
        transmission: E_Rental_Vehicle_Transmission.Automatic,
        year: "2020",
        rentalNote:
          "Rugged and reliable for both city and off-road adventures.",
        qty: 5,
        addOns: null,
        photos: [],
        location: null,
        status: "Live",
        finishedSections: [
          "basicInfo",
          "details",
          "addOns",
          "photos",
          "pricing",
          "location",
        ],
        pricePerDates: [],
        reviews: [],
        updatedAt: "2024-11-14T10:30:00.000Z",
        qtyIds: [],
        daysCanCancel: 7,
      },
      {
        details: null,
        pricing: null,
        host: null,
        category: E_Rental_Category.Bicycle,
        make: "BMX",
        modelBadge: null,
        bodyType: null,
        fuel: null,
        transmission: null,
        year: null,
        rentalNote: "High-performance bike for thrill seekers.",
        qty: 3,
        addOns: null,
        photos: [],
        location: null,
        status: "Live",
        finishedSections: [
          "basicInfo",
          "details",
          "addOns",
          "photos",
          "pricing",
          "location",
        ],
        pricePerDates: [],
        reviews: [],
        updatedAt: "2024-10-30T12:40:00.000Z",
        qtyIds: [],
        daysCanCancel: 3,
      },
      {
        details: null,
        pricing: null,
        host: null,
        category: E_Rental_Category.Bicycle,
        make: "Tesla",
        modelBadge: null,
        bodyType: null,
        fuel: null,
        transmission: null,
        year: null,
        rentalNote: "",
        qty: 2,
        addOns: null,
        photos: [],
        location: null,
        status: "Live",
        finishedSections: [
          "basicInfo",
          "details",
          "addOns",
          "photos",
          "pricing",
          "location",
        ],
        pricePerDates: [],
        reviews: [],
        updatedAt: "2024-09-25T10:30:00.000Z",
        qtyIds: [],
        daysCanCancel: 5,
      },
      {
        details: null,
        pricing: null,
        host: null,
        category: E_Rental_Category.Bicycle,
        make: "Suzuki",
        modelBadge: null,
        bodyType: null,
        fuel: null,
        transmission: null,
        year: null,
        rentalNote: "",
        qty: 1,
        addOns: null,
        photos: [],
        location: null,
        status: "Live",
        finishedSections: [
          "basicInfo",
          "details",
          "addOns",
          "photos",
          "pricing",
          "location",
        ],
        pricePerDates: [],
        reviews: [],
        updatedAt: "2024-11-22T14:15:00.000Z",
        qtyIds: [],
        daysCanCancel: 3,
      },
      {
        details: null,
        pricing: null,
        host: null,
        category: E_Rental_Category.Bicycle,
        make: "Subaru",
        modelBadge: null,
        bodyType: null,
        fuel: null,
        transmission: null,
        year: null,
        rentalNote: "",
        qty: 4,
        addOns: null,
        photos: [],
        location: null,
        status: "Live",
        finishedSections: [
          "basicInfo",
          "details",
          "addOns",
          "photos",
          "pricing",
          "location",
        ],
        pricePerDates: [],
        reviews: [],
        updatedAt: "2024-11-20T16:20:00.000Z",
        qtyIds: [],
        daysCanCancel: 4,
      },
      {
        details: null,
        pricing: null,
        host: null,
        category: E_Rental_Category.Bicycle,
        make: "Jeep",
        modelBadge: null,
        bodyType: null,
        fuel: null,
        transmission: null,
        year: null,
        rentalNote: "",
        qty: 3,
        addOns: null,
        photos: [],
        location: null,
        status: "Live",
        finishedSections: [
          "basicInfo",
          "details",
          "addOns",
          "photos",
          "pricing",
          "location",
        ],
        pricePerDates: [],
        reviews: [],
        updatedAt: "2024-11-15T13:00:00.000Z",
        qtyIds: [],
        daysCanCancel: 5,
      },
    ]

    const rentalDetails = await dbRentalDetails.insertMany(rentalDetailsItem)
    const locationData = await dbLocations.insertMany(locations)
    const rentalAddOns = await dbRentalAddOns.insertMany(addOns)
    const rentalPrice = await dbRentalRates.insertMany(rentalPriceItem)
    const getUser = await dbUsers.find({})
    const userIds = getUser.flatMap((user) => user._id)
    const newRentalData = rentalsData.map((item) => {
      const transShort = item.transmission === "Manual" ? "MT" : "AT"
      const nameBase =
        item.category !== E_Rental_Category.Bicycle
          ? `${item.year} ${item.make} ${item.modelBadge} ${transShort}`
          : `${item.make}`
      let qtyIds = []
      for (let i = 0; i < item.qty; i++) {
        qtyIds.push({
          _id: new mongoose.Types.ObjectId(),
          name: `${nameBase} ${i + 1}`,
        })
      }

      return {
        ...item,
        host: userIds[0],
        qtyIds: qtyIds,
      }
    })

    const rentals = await dbRentals.insertMany(newRentalData)

    rentals.forEach(async (rental, i) => {
      await dbRentals.findByIdAndUpdate(rental._id, {
        $set: {
          pricing: rentalPrice[i]?._id,
          details: rentalDetails[i]?._id,
          addOns: rentalAddOns[i]?._id,
          location: locationData[i]?._id,
        },
      })
      const photos = await dbPhotos.insertMany([
        {
          isMain: true,
          activityId: null,
          bookableUnitId: null,
          propertyId: null,
          rentalId: rental._id,
          createdAt: String(Date.now()),
          key: rental.make + " " + rental.year + "-1" || rental.make + "-1",
          thumbKey:
            rental.make + " " + rental.year + "-1" || rental.make + "-1",
          tags: "photo",
          description:
            (rental.make + " " + rental.year + "-1" || rental.make + "-1") +
            " description",
        },
        {
          isMain: false,
          activityId: null,
          bookableUnitId: null,
          propertyId: null,
          rentalId: rental._id,
          createdAt: String(Date.now()),
          key: rental.make + " " + rental.year + "-2" || rental.make + "-2",
          thumbKey:
            rental.make + " " + rental.year + "-2" || rental.make + "-2",
          tags: "photo",
          description:
            (rental.make + " " + rental.year + "-2" || rental.make + "-2") +
            " description",
        },
        {
          isMain: false,
          activityId: null,
          bookableUnitId: null,
          propertyId: null,
          rentalId: rental._id,
          createdAt: String(Date.now()),
          key: rental.make + " " + rental.year + "-3" || rental.make + "-3",
          thumbKey:
            rental.make + " " + rental.year + "-3" || rental.make + "-3",
          tags: "photo",
          description:
            (rental.make + " " + rental.year + "-3" || rental.make + "-3") +
            " description",
        },
        {
          isMain: false,
          activityId: null,
          bookableUnitId: null,
          propertyId: null,
          rentalId: rental._id,
          createdAt: String(Date.now()),
          key: rental.make + " " + rental.year + "-4" || rental.make + "-4",
          thumbKey:
            rental.make + " " + rental.year + "-4" || rental.make + "-4",
          tags: "photo",
          description:
            (rental.make + " " + rental.year + "-4" || rental.make + "-4") +
            " description",
        },
        {
          isMain: false,
          activityId: null,
          bookableUnitId: null,
          propertyId: null,
          rentalId: rental._id,
          createdAt: String(Date.now()),
          key: rental.make + " " + rental.year + "-5" || rental.make + "-5",
          thumbKey:
            rental.make + " " + rental.year + "-5" || rental.make + "-5",
          tags: "photo",
          description:
            (rental.make + " " + rental.year + "-5" || rental.make + "-5") +
            " description",
        },
      ])
      photos.forEach(async (photo) => {
        await dbRentals.updateOne(
          { _id: rental._id },
          {
            $push: { photos: photo._id },
          }
        )
      })
    })

    console.log("Rentals seeded successfully!")
  } catch (error) {
    console.error("Error seeding rentals:", error)
  }
}

export default seedRentals
