import { HOST } from "@/common/constants"
import { APP_NAME } from "@repo/constants"
import { Metadata } from "next"
import AuthGuard from "@/common/components/AuthGuard"
import Policies from "@/module/Admin/Listings/ForReview/Property/Policies"

export const metadata: Metadata = {
  title: `${HOST} - ${APP_NAME}`,
  description: `Generated by ${APP_NAME}`,
}

const ListingPoliciesPage = () => {
  return (
    <AuthGuard>
      <Policies pageType="edit" />
    </AuthGuard>
  )
}

export default ListingPoliciesPage
