import { HOST } from "@/common/constants"
import { APP_NAME } from "@repo/constants"
import { Metadata } from "next"
import AuthGuard from "@/common/components/AuthGuard"
import MotorReservationCalendar from "@/module/Hosting/Reservations/calendar/rental/motor-rental"

export const metadata: Metadata = {
  title: `${HOST} - ${APP_NAME}`,
  description: `Generated by ${APP_NAME}`,
}

const ReservationCalendarPage = () => {
  return (
    <AuthGuard>
      <MotorReservationCalendar />
    </AuthGuard>
  )
}

export default ReservationCalendarPage
