export const PROPERTY_FACILITIES = [
  {
    category: "Most Popular",
    facilities: [
      "Bar",
      "Sauna",
      "Garden",
      "Terrace",
      "Hot tub/Jacuzzi",
      "Heating",
      "Free WiFi",
      "Air conditioning",
      "Swimming pool",
      "Beach",
    ],
  },
  {
    category: "Outdoors",
    facilities: [
      "Beachfront",
      "Outdoor furniture",
      "Sun terrace",
      "Private beach area",
      "BBQ facilities",
      "Parking",
      "Shared kitchen",
      "Smoking area",
      "Garden",
      "Common area",
    ],
  },
  {
    category: "Activities",
    facilities: [
      "Bicycle rental (additional charge)",
      "Happy hour",
      "Beach",
      "Snorkelling (additional charge)",
      "Diving (additional charge)",
      "Cycling",
      "Hiking (additional charge)",
      "Billiards",
      "Children's playground",
      "Nearby golf course (additional charge)",
      "Cooking class",
      "Tour or class about local culture",
      "Themed dinner nights",
      "Bike tours",
      "Walking tours",
      "Movie nights",
      "Beach sports",
      "Badminton equipment",
      "Water sport facilities on site",
      "Snorkelling",
      "Games room",
      "Fishing (additional charge)",
      "Table tennis",
    ],
  },
  {
    category: "Food & Drink",
    facilities: [
      "Snack bar",
      "Bar",
      "Restaurant",
      "Happy hour",
      "Free breakfast included",
      "Breakfast (additional charge)",
      "Special diet menus (on request)",
      "Special diet menus (additional charge)",
    ],
  },
  {
    category: "Internet",
    facilities: [
      "Free WiFi",
      "WiFi (additional charge)",
      "Starlink",
      "Co-working space",
    ],
  },
  {
    category: "Parking",
    facilities: [
      "Private parking",
      "Street parking",
      "Motorbike parking",
      "Car park",
      "Parking garage",
      "Accessible parking",
    ],
  },
  {
    category: "Services",
    facilities: [
      "Shuttle service (Additional charge)",
      "Luggage storage",
      "Tour desk",
      "Car hire (additional charge)",
      "Packed lunches (additional charge)",
      "Babysitting/child services (additional charge)",
      "Airport shuttle (additional charge)",
      "Free airport shuttle",
      "Room service",
      "Room service (additional charge)",
    ],
  },
  {
    category: "Reception services",
    facilities: [
      "Invoice provided",
      "Lockers",
      "Private check-in/check-out",
      "Concierge service",
      "Luggage storage",
      "Express check-in/check-out",
      "24/7 check-in",
    ],
  },
  {
    category: "Safety & security",
    facilities: [
      "24/7 security guard",
      "Security guard at night",
      "Fire extinguishers",
      "CCTV outside property",
      "CCTV in common areas",
      "Safety deposit box",
    ],
  },
  {
    category: "General",
    facilities: [
      "Designated smoking area",
      "Air conditioning",
      "Soundproof rooms",
      "Family rooms",
      "Non-smoking rooms",
      "Outdoor swimming pool",
      "Indoor swimming pool",
      "Plunge pool",
      "Spa",
      "Open all year",
      "Free pool/beach towels",
      "Pool/beach towels (additional charge)",
      "Sun loungers or beach chairs",
      "Swim up bar",
      "Pool Bar",
      "Sun umbrellas",
      "Hot tub/Jacuzzi",
      "Non-smoking throughout",
      "Wake up service",
      "All ages welcome",
      "Pool with view",
      "Swimming pool toys",
    ],
  },
  {
    category: "Wellness",
    facilities: [
      "Fitness area",
      "Yoga shala",
      "Fitness equipment",
      "Massage (additional charge)",
      "Massage",
      "Spa and wellness center (additional charge)",
      "Fitness locker rooms",
      "Yoga classes",
      "Fitness",
      "Couples massage (additional charge)",
      "Couples massage",
      "Spa/wellness packages (additional charge)",
      "Free spa facilities",
      "Free beauty Services",
      "Beauty Services (additional charge)",
      "Public Bath",
      "Public shower",
      "Open-air bath",
      "Massage",
      "Spa and wellness centre",
      "Fitness centre",
      "Gym",
    ],
  },
  {
    category: "Cleaning services",
    facilities: [
      "Daily housekeeping",
      "Ironing service",
      "Ironing service (additional charge)",
      "Laundry",
      "Laundry (additional charge)",
    ],
  },
  {
    category: "Business facilities",
    facilities: [
      "Fax/photocopying (additional charge)",
      "Fax/photocopying",
      "Meeting/banquet facilities",
    ],
  },
  {
    category: "Entertainment and family services",
    facilities: [
      "Kids' outdoor play equipment",
      "Indoor play area",
      "Board games/puzzles",
      "Board games/puzzles",
      "Babysitting/child services",
      "Babysitting/child services (additional charge)",
    ],
  },
  {
    category: "Onsite payment methods",
    facilities: [
      "Cash",
      "Gcash",
      "Visa",
      "Mastercard",
      "American Express",
      "UnionPay",
    ],
  },
  {
    category: "Languages spoken",
    facilities: [
      "English",
      "Filipino",
      "Spanish",
      "French",
      "Chinese",
      "Hebrew",
      "German",
    ],
  },
]

export const UNIT_AMENITIES = [
  {
    category: "Most popular",
    amenities: [
      "Air Conditioning",
      "Flatscreen TV",
      "Free WiFi",
      "Kitchen",
      "Desk/Workstation",
      "Refrigerator",
      "Socket near the bed",
      "Safety deposit box",
      "Ocean view",
      "Smoking allowed",
      "Non-smoking",
    ],
  },
  {
    category: "Bathroom",
    amenities: [
      "Free toiletries",
      "Bidet",
      "Toilet",
      "Bath or shower",
      "Towels",
      "Linen",
      "Tile/marble floor",
      "Bathrobe",
      "Toilet paper",
      "Hairdryer",
      "Hand sanitiser",
      "Spa bath",
    ],
  },
  {
    category: "Kitchen",
    amenities: [
      "Tea/Coffee maker",
      "Microwave",
      "Kitchenware",
      "Hot/cold water dispenser",
      "Electric kettle",
      "Stovetop",
      "Dining area",
      "Dining table",
      "Coffee machine",
      "Minibar",
      "Kitchenette",
    ],
  },
  {
    category: "Living area",
    amenities: [
      "Seating Area",
      "Sofa bed",
      "Hardwood or parquet floors",
      "Wardrobe or closet",
      "Clothes rack",
      "iPod dock",
      "Dressing room",
      "Board games/puzzles",
      "Books, DVDs, or music for children",
      "Balcony",
      "Terrace",
      "View",
      "Garden view",
      "Pool view",
    ],
  },
  {
    category: "General",
    amenities: [
      "Private entrance",
      "Wake-up service",
      "Slippers",
      "Ironing facilities",
      "Wake up service/Alarm clock",
      "Laptop safe",
      "Tumble dryer",
      "iPad",
      "Drying rack for clothing",
      "Towels/sheets (extra fee)",
      "Free extra towels/sheets",
      "Telephone",
      "Children's high chair",
      "Cleaning products",
      "Fan",
      "iPod dock",
      "Board games/puzzles",
    ],
  },
  {
    category: "Outdoors",
    amenities: [
      "Outdoor furniture",
      "Outdoor dining area",
      "Balcony",
      "Terrace",
      "View",
      "Garden view",
      "Pool view",
    ],
  },
]
