import type { Metadata } from "next"

import "@/app/globals.css"
import { Toaster } from "react-hot-toast"
import React from "react"
import { LOGO_SINGLE_IMAGE } from "@/common/constants/index"
import { APP_NAME } from "@repo/constants"
import Header from "@/common/components/AdminLayout/ListingHeader"
import Sidebar from "@/common/components/AdminLayout/ListingSidebar"
import GlobalWrappers from "@/common/components/Wrappers/GlobalWrappers"

export const metadata: Metadata = {
  title: APP_NAME,
  description: `Generated by ${APP_NAME}`,
}

export default async function HostListingLayout({
  children,
}: {
  readonly children: React.ReactNode
}) {
  return (
    <html lang="en">
      <link rel="icon" type="image/x-icon" href={LOGO_SINGLE_IMAGE} />
      <body>
        <Toaster />
        <GlobalWrappers>
          <Header />
          <Sidebar>{children}</Sidebar>
        </GlobalWrappers>
      </body>
    </html>
  )
}
