export const ACTIVITIES_DATA = [
  {
    id: 2,
    hostId: 3,
    Host: {
      id: 3,
      firstName: "John Patrick",
      lastName: "Madrigal",
    },
    status: "Pending",
    finishedSections: "[]",
    name: "Land Tour",
    description: "House in the top of the mountain",
    currency: "PHP",
    primaryLanguage: "Tagalog",
    Photos: [
      {
        id: 1,
        thumbKey: "1.jpg",
        key: "1.jpg",
        description: "Outside view",
        tag: "#develop",
      },
      {
        id: 2,
        thumbKey: "3.jpg",
        key: "4.jpg",
        description: "Interior view",
        tag: "#develop",
      },
    ],
    phone: "09492622242",
    email: "supermario@gmail.com",
    Location: {
      street: "Looban",
      barangay: "Cabooan",
      city: "Santa Maria",
      latitude: 200.25,
      longitude: 108.59,
      howToGetThere: "",
    },
    checkInTime: "2024-03-14 03:09:52.697",
    checkOutTime: "2024-03-17 03:09:52.697",
    lateCheckOutAllowed: true,
    lateCheckOutType: "Type C",
    lateCheckoutValue: 25.5,
    termsAndConditions: "No payment no check in",
    taxId: 20032024,
    taxId2: 21032024,
    companyLegalName: "Mario Bros real estate",
    type: "Hostel",
    Facilities: [
      {
        id: 3,
        index: 47,
        category: "Food & Drink",
        facility: "Free breakfast included",
        propertyId: 2,
        isSelected: true,
      },
      {
        id: 4,
        index: 43,
        category: "Food & Drink",
        facility: "Snack bar",
        propertyId: 2,
        isSelected: true,
      },
      {
        id: 31,
        index: 0,
        category: "Most Popular",
        facility: "Bar",
        propertyId: 2,
        isSelected: true,
      },
      {
        id: 32,
        index: 3,
        category: "Most Popular",
        facility: "Sauna",
        propertyId: 2,
        isSelected: true,
      },
    ],
    Policies: [
      {
        id: 1,
        index: 0,
        category: "Things To Know",
        policy: "No pets allowed",
        reason: null,
        propertyId: 2,
        isSelected: true,
      },
      {
        id: 2,
        index: 2,
        category: "Things To Know",
        policy: "No parties or events",
        reason: null,
        propertyId: 2,
        isSelected: true,
      },
      {
        id: 3,
        index: 23,
        category: "Additional Rules",
        policy: "Custom rule 1",
        reason: null,
        propertyId: 2,
        isSelected: true,
      },
      {
        id: 5,
        index: 9,
        category: "Safety Consideration",
        policy: "Not suitable for children",
        reason:
          "Certain activities or environments may be too complex or challenging for children",
        propertyId: 2,
        isSelected: true,
      },
      {
        id: 6,
        index: 10,
        category: "Safety Consideration",
        policy: "Near by ocean, river, other body of water",
        reason:
          "Some environments or activities may pose safety risks to children due to hazards such as sharp objects, high places, heavy machinery, or dangerous substances",
        propertyId: 2,
        isSelected: true,
      },
      {
        id: 7,
        index: 11,
        category: "Safety Devices",
        policy: "Carbon Monoxide installed",
        reason: null,
        propertyId: 2,
        isSelected: true,
      },
      {
        id: 8,
        index: 12,
        category: "Safety Devices",
        policy: "No carbon monoxide alarm",
        reason: null,
        propertyId: 2,
        isSelected: true,
      },
      {
        id: 9,
        index: 20,
        category: "Property Info",
        policy: "No parking on property",
        reason:
          "Information about fire safety measures in the property, including the location of fire exits, fire extinguishers, smoke detectors, and emergency evacuation procedures.",
        propertyId: 2,
        isSelected: true,
      },
      {
        id: 10,
        index: 21,
        category: "Property Info",
        policy: "No wheelchair access",
        reason:
          "Details about security features in the property, such as locks on doors and windows, security cameras, alarm systems, and any neighborhood watch programs.",
        propertyId: 2,
        isSelected: true,
      },
    ],
    BookableUnit: [
      {
        id: 8,
        propertyId: 2,
        BookableUnitType: {
          id: 8,
          qty: 4,
          category: "Room",
          name: "Room 1",
          description: "2 Beds with CR",
          unitPrice: {
            id: 8,
            baseRate: 3000,
            baseRateMaxcapacity: 2,
            maximumCapacity: 4,
            pricePerAdditionalPerson: 1000,
            discountedWeeklyRate: 10,
            discountMonthlyRate: 30,
          },
          Photo: {
            id: 16,
            thumbKey: "4.jpg",
            key: "4.jpg",
            description: "Room",
            tag: "#develop",
          },
          isPrivate: true,
          maxGuest: 5,
          adultsIncluded: 2,
          childrenIncluded: 1,
          isMultiRoomUnit: false,
        },
      },
      {
        id: 9,
        propertyId: 2,
        BookableUnitType: {
          id: 9,
          category: "Room",
          name: "Room 2",
          qty: 7,
          description: "2 Beds with aircon",
          unitPrice: {
            id: 9,
            baseRate: 3000,
            baseRateMaxcapacity: 2,
            maximumCapacity: 4,
            pricePerAdditionalPerson: 1000,
            discountedWeeklyRate: 10,
            discountMonthlyRate: 30,
          },
          Photo: {
            id: 17,
            thumbKey: "4.jpg",
            key: "4.jpg",
            description: "Room",
            tag: "#develop",
          },
          isPrivate: true,
          maxGuest: 8,
          adultsIncluded: 2,
          childrenIncluded: 4,
          isMultiRoomUnit: false,
        },
      },
      {
        id: 10,
        propertyId: 2,
        BookableUnitType: {
          id: 10,
          category: "Bed",
          name: "Bed-A",
          description: "King bed",
          isPrivate: true,
          maxGuest: 10,
          adultsIncluded: 5,
          qty: 4,
          childrenIncluded: 5,
          isMultiRoomUnit: false,
          unitPrice: {
            id: 10,
            baseRate: 1000,
            baseRateMaxcapacity: 2,
            maximumCapacity: 2,
            pricePerAdditionalPerson: 500,
            discountedWeeklyRate: 10,
            discountMonthlyRate: 20,
          },
        },
      },
      {
        id: 11,
        propertyId: 2,
        BookableUnitType: {
          id: 11,
          category: "Bed",
          name: "Bed-B",
          qty: 4,
          description: "Queen Bed",
          photo: {
            id: 18,
            thumbKey: "3.jpg",
            key: "3.jpg",
            description: "Bed",
            tag: "#develop",
          },
          unitPrice: {
            id: 11,
            baseRate: 3000,
            baseRateMaxcapacity: 2,
            maximumCapacity: 4,
            pricePerAdditionalPerson: 1000,
            discountedWeeklyRate: 10,
            discountMonthlyRate: 30,
          },
          isPrivate: true,
          maxGuest: 5,
          adultsIncluded: 1,
          childrenIncluded: 1,
          isMultiRoomUnit: false,
        },
      },
    ],
    reservation: [
      {
        id: 1,
        mainGuestId: 4,
        status: "confirmed",
        startDate: "2024-03-14 03:09:52.697",
        endDate: "2024-03-15 03:09:52.697",
      },
      {
        id: 2,
        mainGuestId: 4,
        status: "not_confirmed",
        startDate: "2024-03-16 03:09:52.697",
        endDate: "2024-03-17 03:09:52.697",
      },
    ],
  },
  {
    id: 3,
    hostId: 3,
    Host: {
      id: 3,
      firstName: "John Patrick",
      lastName: "Madrigal",
    },
    status: "Pending",
    finishedSections: "[]",
    name: "Island Hopping",
    description: "Resort in far far away",
    currency: "PHP",
    primaryLanguage: "Tagalog",
    Photos: [
      {
        id: 1,
        thumbKey: "1.jpg",
        key: "2.jpg",
        description: "Outside view",
        tag: "#develop",
      },
      {
        id: 2,
        thumbKey: "3.jpg",
        key: "4.jpg",
        description: "Interior view",
        tag: "#develop",
      },
    ],
    phone: "09092558726",
    email: "luigi@gmail.com",
    Location: {
      street: "JP. Rizal",
      barangay: "San Jose",
      city: "Pangil",
      latitude: 205.25,
      longitude: 105.59,
      howToGetThere: "",
    },
    checkInTime: "2024-03-14 03:09:52.697",
    checkOutTime: "2024-03-17 03:09:52.697",
    lateCheckOutAllowed: true,
    lateCheckOutType: "Type C",
    lateCheckoutValue: 25.5,
    termsAndConditions: "No payment no check in",
    taxId: 20032024,
    taxId2: 21032024,
    companyLegalName: "Mario Bros real estate",
    type: "Villa",
    Facilities: [
      {
        id: 3,
        index: 47,
        category: "Food & Drink",
        facility: "Free breakfast included",
        propertyId: 3,
        isSelected: true,
      },
      {
        id: 4,
        index: 43,
        category: "Food & Drink",
        facility: "Snack bar",
        propertyId: 3,
        isSelected: true,
      },
      {
        id: 31,
        index: 0,
        category: "Most Popular",
        facility: "Bar",
        propertyId: 3,
        isSelected: true,
      },
      {
        id: 32,
        index: 3,
        category: "Most Popular",
        facility: "Sauna",
        propertyId: 3,
        isSelected: true,
      },
    ],
    Policies: [
      {
        id: 1,
        index: 0,
        category: "Things To Know",
        policy: "No pets allowed",
        reason: null,
        propertyId: 3,
        isSelected: true,
      },
      {
        id: 2,
        index: 2,
        category: "Things To Know",
        policy: "No parties or events",
        reason: null,
        propertyId: 3,
        isSelected: true,
      },
      {
        id: 3,
        index: 23,
        category: "Additional Rules",
        policy: "Custom rule 1",
        reason: null,
        propertyId: 3,
        isSelected: true,
      },
      {
        id: 5,
        index: 9,
        category: "Safety Consideration",
        policy: "Not suitable for children",
        reason:
          "Certain activities or environments may be too complex or challenging for children",
        propertyId: 3,
        isSelected: true,
      },
      {
        id: 6,
        index: 10,
        category: "Safety Consideration",
        policy: "Near by ocean, river, other body of water",
        reason:
          "Some environments or activities may pose safety risks to children due to hazards such as sharp objects, high places, heavy machinery, or dangerous substances",
        propertyId: 3,
        isSelected: true,
      },
      {
        id: 7,
        index: 11,
        category: "Safety Devices",
        policy: "Carbon Monoxide installed",
        reason: null,
        propertyId: 3,
        isSelected: true,
      },
      {
        id: 8,
        index: 12,
        category: "Safety Devices",
        policy: "No carbon monoxide alarm",
        reason: null,
        propertyId: 3,
        isSelected: true,
      },
      {
        id: 9,
        index: 20,
        category: "Property Info",
        policy: "No parking on property",
        reason:
          "Information about fire safety measures in the property, including the location of fire exits, fire extinguishers, smoke detectors, and emergency evacuation procedures.",
        propertyId: 3,
        isSelected: true,
      },
      {
        id: 10,
        index: 21,
        category: "Property Info",
        policy: "No wheelchair access",
        reason:
          "Details about security features in the property, such as locks on doors and windows, security cameras, alarm systems, and any neighborhood watch programs.",
        propertyId: 3,
        isSelected: true,
      },
    ],
    BookableUnit: [
      {
        id: 12,
        propertyId: 3,
        BookableUnitType: {
          id: 12,
          category: "Bed",
          name: "Bed in Bed",
          description: "bed in bed",
          photo: {
            id: 19,
            thumbKey: "2.jpg",
            key: "2.jpg",
            caption: "Bed",
          },
          unitPrice: {
            id: 12,
            baseRate: 3000,
            baseRateMaxcapacity: 2,
            maximumCapacity: 4,
            pricePerAdditionalPerson: 1000,
            discountedWeeklyRate: 10,
            discountMonthlyRate: 30,
          },
          isPrivate: true,
          maxGuest: 5,
          adultsIncluded: 2,
          childrenIncluded: 1,
          isMultiRoomUnit: false,
        },
      },
      {
        id: 13,
        propertyId: 3,
        BookableUnitType: {
          id: 13,
          category: "Bed",
          name: "Bed 1",
          description: "amazing bed",
          photo: {
            id: 19,
            thumbKey: "1.jpg",
            key: "1.jpg",
            caption: "Bed",
          },
          unitPrice: {
            id: 13,
            baseRate: 3000,
            baseRateMaxcapacity: 2,
            maximumCapacity: 4,
            pricePerAdditionalPerson: 1000,
            discountedWeeklyRate: 10,
            discountMonthlyRate: 30,
          },
          isPrivate: true,
          maxGuest: 5,
          adultsIncluded: 2,
          childrenIncluded: 1,
          isMultiRoomUnit: false,
        },
      },
      {
        id: 14,
        BookableUnitType: {
          id: 14,
          category: "Bed",
          name: "Bed 2",
          description: "Bed cold",
          photo: {
            id: 20,
            thumbKey: "1.jpg",
            key: "1.jpg",
            caption: "Bed",
          },
          unitPrice: {
            id: 14,
            baseRate: 3000,
            baseRateMaxcapacity: 2,
            maximumCapacity: 4,
            pricePerAdditionalPerson: 1000,
            discountedWeeklyRate: 10,
            discountMonthlyRate: 30,
          },
          isPrivate: true,
          maxGuest: 5,
          adultsIncluded: 2,
          childrenIncluded: 1,
          isMultiRoomUnit: false,
        },
      },
      {
        id: 15,
        BookableUnitType: {
          id: 15,
          category: "Room",
          name: "Room 2",
          description: "Bid room",
          photo: {
            id: 21,
            thumbKey: "3.jpg",
            key: "3.jpg",
            caption: "Bed",
          },
          unitPrice: {
            id: 15,
            baseRate: 3000,
            baseRateMaxcapacity: 2,
            maximumCapacity: 4,
            pricePerAdditionalPerson: 1000,
            discountedWeeklyRate: 10,
            discountMonthlyRate: 30,
          },
          isPrivate: true,
          maxGuest: 8,
          adultsIncluded: 2,
          childrenIncluded: 4,
          isMultiRoomUnit: false,
        },
      },
      {
        id: 16,
        propertyId: 3,
        BookableUnitType: {
          id: 16,
          category: "Bed",
          name: "bed 3",
          description: "Double Bed",
          photo: {
            id: 22,
            thumbKey: "5.jpg",
            key: "3.jpg",
            caption: "Bed",
          },
          unitPrice: {
            id: 16,
            baseRate: 3000,
            baseRateMaxcapacity: 2,
            maximumCapacity: 4,
            pricePerAdditionalPerson: 1000,
            discountedWeeklyRate: 10,
            discountMonthlyRate: 30,
          },
          isPrivate: true,
          maxGuest: 10,
          adultsIncluded: 5,
          childrenIncluded: 5,
          isMultiRoomUnit: false,
        },
      },
      {
        id: 17,
        propertyId: 3,
        BookableUnitType: {
          id: 17,
          category: "Bed",
          name: "bed 4",
          description: "Bed long",
          photo: {
            id: 22,
            thumbKey: "5.jpg",
            key: "5.jpg",
            caption: "Bed",
          },
          unitPrice: {
            id: 17,
            baseRate: 3000,
            baseRateMaxcapacity: 2,
            maximumCapacity: 4,
            pricePerAdditionalPerson: 1000,
            discountedWeeklyRate: 10,
            discountMonthlyRate: 30,
          },
          isPrivate: true,
          maxGuest: 5,
          adultsIncluded: 1,
          childrenIncluded: 1,
          isMultiRoomUnit: false,
        },
      },
    ],
    reservation: [
      {
        id: 1,
        mainGuestId: 4,
        status: "confirmed",
        startDate: "2024-03-14 03:09:52.697",
        endDate: "2024-03-15 03:09:52.697",
      },
      {
        id: 2,
        mainGuestId: 4,
        status: "not_confirmed",
        startDate: "2024-03-16 03:09:52.697",
        endDate: "2024-03-17 03:09:52.697",
      },
    ],
  },
]
