import { HOST } from "@/common/constants"
import { APP_NAME } from "@repo/constants"
import { Metadata } from "next"
import HostingReservations from "@/module/Hosting/Reservations/Upcoming"
import AuthGuard from "@/common/components/AuthGuard"

export const metadata: Metadata = {
  title: `${HOST} - ${APP_NAME}`,
  description: `Generated by ${APP_NAME}`,
}

const HostingReservationsPage = () => {
  return (
    <AuthGuard>
      <HostingReservations />
    </AuthGuard>
  )
}

export default HostingReservationsPage
