import { string, z } from "zod"
import { E_RegistrationType, E_UserRole } from "./enum"

export const Z_Guest = z.object({
  _id: z.string().optional(),
  firstName: z.string(),
  middleName: z.string().optional(),
  lastName: z.string(),
  language: z.string().optional(),
  currency: z.string().optional(),
  gender: z.string().optional(),
  phone: z.string().optional(),
  cellPhone: z.string().optional(),
  governmentId: z.array(z.string()).optional(),
  country: z.string().optional(),
  address: z.string().optional(),
  emergencyContacts: z.array(z.string()).optional(),
  birthDate: z.string().optional(),
  documentType: z.string().optional(),
  documentNumber: z.string().optional(),
  documentIssueDate: z.string().optional(),
  documentIssuingCountry: z.string().optional(),
  documentExpirationDate: z.string().optional(),
  companyTaxId: z.number().optional(),
  companyName: z.string().optional(),
  confirm: z.string().optional(),
  profile: z.string().optional(),
  createdAt: z.string().optional(),
  updatedAt: z.string().optional(),
  deletedAt: z.string().optional(),
})
