import type { Metadata } from "next"

import "@/app/globals.css"
import { Toaster } from "react-hot-toast"
import React from "react"
import { LOGO_SINGLE_IMAGE } from "@/common/constants/index"
import { APP_NAME } from "@repo/constants"
import Header from "@/common/components/Header"
import GlobalWrappers from "@/common/components/Wrappers/GlobalWrappers"

export const metadata: Metadata = {
  title: APP_NAME,
  description: `Generated by ${APP_NAME}`,
}

export default async function ConversationLayout({
  children,
}: {
  readonly children: React.ReactNode
}) {
  return (
    <html lang="en">
      <link rel="icon" type="image/x-icon" href={LOGO_SINGLE_IMAGE} />
      <body className={`overflow-hidden h-screen bg-gray-50`}>
        <Toaster />

            <GlobalWrappers>
              <Header contentWidth="wide" isFixed={false} />
              {children}
            </GlobalWrappers>
      </body>
    </html>
  )
}
