import { HOST } from "@/common/constants"
import { APP_NAME } from "@repo/constants"
import { Metadata } from "next"
import AuthGuard from "@/common/components/AuthGuard"
import ActivitySummary from "@/module/Hosting/Listings/Activities/Activity/Summary"

export const metadata: Metadata = {
  title: `${HOST} - ${APP_NAME}`,
  description: `Generated by ${APP_NAME}`,
}

const ActivitySummaryPage = () => {
  return (
    <AuthGuard>
      <ActivitySummary />
    </AuthGuard>
  )
}

export default ActivitySummaryPage
