import { HOST } from "@/common/constants"
import { APP_NAME } from "@repo/constants"
import { Metadata } from "next"
import AuthGuard from "@/common/components/AuthGuard"
import AddVerification from "@/module/Hosting/settings/add-verification"

export const metadata: Metadata = {
  title: `${HOST} - ${APP_NAME}`,
  description: `Generated by ${APP_NAME}`,
}

const AddVerificationPage = () => {
  return (
    <AuthGuard>
      <AddVerification />
    </AuthGuard>
  )
}

export default AddVerificationPage
