import type { Metadata } from "next"

import "@/app/globals.css"
import { Toaster } from "react-hot-toast"
import React from "react"
import { LOGO_SINGLE_IMAGE } from "@/common/constants/index"
import { APP_NAME } from "@repo/constants"
import ListingHeader from "@/common/components/HostLayout/ListingHeader"
import ListingSidebar from "@/common/components/HostLayout/ListingSidebar"
import { E_Listing_Category } from "@repo/contract"
import { E_Listing_Status } from "@/common/types/global"
import GlobalWrappers from "@/common/components/Wrappers/GlobalWrappers"

export const metadata: Metadata = {
  title: APP_NAME,
  description: `Generated by ${APP_NAME}`,
}

export default async function HostListingPropertyLayout({
  children,
}: {
  readonly children: React.ReactNode
}) {
  return (
    <html lang="en">
      <link rel="icon" type="image/x-icon" href={LOGO_SINGLE_IMAGE} />
      <body>
        <Toaster />

        <GlobalWrappers>
          <ListingHeader
            listingStatus={E_Listing_Status.edit}
            category={E_Listing_Category.Property}
          />
          <ListingSidebar category={E_Listing_Category.Property}>
            {children}
          </ListingSidebar>
        </GlobalWrappers>
      </body>
    </html>
  )
}
