import AuthGuard from "@/common/components/AuthGuard"
import React from "react"
import { APP_NAME } from "@repo/constants"
import { Metadata } from "next"
import HostListing from "@/module/Hosting/Listings/Rentals"

export const metadata: Metadata = {
  title: `Earnings - ${APP_NAME}`,
  description: `Generated by ${APP_NAME}`,
}

const RentalsTableTab = () => {
  return (
    <AuthGuard>
      <HostListing />
    </AuthGuard>
  )
}

export default RentalsTableTab
