import type { Metadata } from "next"

import "@/app/globals.css"
import { Toaster } from "react-hot-toast"
import React from "react"
import { LOGO_SINGLE_IMAGE } from "@/common/constants/index"
import { APP_NAME } from "@repo/constants"
import BlogHeader from "@/common/components/Header/WithSearch"
import Footer from "@/common/components/Footer"
import YMarginWrapper from "@/common/components/Wrappers/YMarginWrapper"
import GlobalWrappers from "@/common/components/Wrappers/GlobalWrappers"

export const metadata: Metadata = {
  title: APP_NAME,
  description: `Generated by ${APP_NAME}`,
}

export default async function BlogGuideLayout({
  children,
}: {
  readonly children: React.ReactNode
}) {
  return (
    <html lang="en">
      <link rel="icon" type="image/x-icon" href={LOGO_SINGLE_IMAGE} />
      <body>
        <Toaster />

            <GlobalWrappers>
              <BlogHeader contentWidth="medium" />
              <YMarginWrapper>{children}</YMarginWrapper>
              <Footer contentWidth="medium" />
            </GlobalWrappers>
      </body>
    </html>
  )
}
