import type { Metadata } from "next"

import "@/app/globals.css"
import QueryClientWrapper from "@/common/components/QueryClientWrapper"
import GlobalModalWrapper from "@/common/components/GlobalModalWrapper"
import { Toaster } from "react-hot-toast"
import React from "react"
import { LOGO_SINGLE_IMAGE } from "@/common/constants/index"
import { APP_NAME } from "@repo/constants"
import AuthStateProvider from "@/common/components/AuthStateProvider"
import BlogHeader from "@/common/components/Header/v2"
import Footer from "@/common/components/Footer"
import SearchBar from "@/common/components/SearchBar/SearchBarByState"
import YMarginWrapper from "@/common/components/YMarginWrapper"

export const metadata: Metadata = {
  title: APP_NAME,
  description: `Generated by ${APP_NAME}`,
}

export default async function BlogGuideLayout({
  children,
}: {
  readonly children: React.ReactNode
}) {
  return (
    <html lang="en">
      <link rel="icon" type="image/x-icon" href={LOGO_SINGLE_IMAGE} />
      <body>
        <Toaster />
        <QueryClientWrapper>
          <AuthStateProvider>
            <GlobalModalWrapper>
              <BlogHeader contentWidth="medium" />
              <YMarginWrapper>{children}</YMarginWrapper>
              <Footer contentWidth="medium" />
            </GlobalModalWrapper>
          </AuthStateProvider>
        </QueryClientWrapper>
      </body>
    </html>
  )
}
