import { HOST } from "@/common/constants"
import { APP_NAME } from "@repo/constants"
import { Metadata } from "next"
import AuthGuard from "@/common/components/AuthGuard"
import Units from "@/module/Hosting/Listings/Properties/Property/Units"

export const metadata: Metadata = {
  title: `${HOST} - ${APP_NAME}`,
  description: `Generated by ${APP_NAME}`,
}

const BedsAndRoomsUnitPage = () => {
  return (
    <AuthGuard>
      <Units pageType="setup" />
    </AuthGuard>
  )
}

export default BedsAndRoomsUnitPage
