export const reviewPropertyComments = [
    "The property was spotless, and the host was very accommodating. Highly recommended!",
    "Amazing stay! The check-in process was seamless, and the amenities exceeded expectations.",
    "Good value for money. The location was perfect for exploring nearby attractions.",
    "The accuracy of the listing could be improved, but overall, it was a decent stay.",
    "The host went above and beyond to make our stay comfortable. Will definitely return!",
    "The check-in process was a bit confusing, but the property was lovely once we settled in.",
    "Fantastic experience! Everything was just as described in the listing.",
    "The property was well-maintained, but the communication with the host was lacking.",
    "Loved the cozy vibes of the place! Perfect for a weekend getaway.",
    "The property was great, but the cleanliness could have been better.",
    "Host was very responsive and provided excellent local recommendations.",
    "The location was ideal, but the amenities were not as described in the listing.",
    "A truly memorable experience! The view from the property was breathtaking.",
    "Decent stay overall, but the noise from the neighboring property was a bit of an issue.",
    "The photos didn’t do justice to how beautiful the property really is!",
    "Great for families! The host provided extra bedding and toys for the kids.",
    "Not as clean as we expected, but the host apologized and offered a discount for next time.",
    "Everything was perfect! From the warm welcome to the detailed instructions for check-out.",
    "The WiFi was a bit spotty, but otherwise, the stay was pleasant.",
    "We had an amazing time! The host was incredibly friendly and accommodating."
];

 export const rentalReviewComments = [
    "The rental was cozy and had everything we needed for a comfortable stay.",
    "Excellent value for the price! The location was ideal for exploring the city.",
    "The rental was clean and well-maintained, with a beautiful view from the balcony.",
    "We had an amazing stay! The host was very accommodating and responsive.",
    "The property exceeded our expectations! Highly recommended for families.",
    "The rental was exactly as described. The kitchen was fully equipped, which was a bonus!",
    "The location was perfect, but the property could use some minor upgrades.",
    "Loved the ambiance of the rental! Perfect for a relaxing vacation.",
    "The host was very helpful and provided great recommendations for local attractions.",
    "The rental was spacious and clean, but the WiFi was a bit slow.",
    "Fantastic stay! The property was close to restaurants, shops, and public transport.",
    "The rental was well-decorated and had a warm, homey feel to it.",
    "The host went above and beyond to make our stay comfortable and enjoyable.",
    "Great experience! The rental was quiet and located in a safe neighborhood.",
    "The beds were comfortable, and the rental was stocked with all the essentials.",
    "Not as clean as expected, but the host quickly resolved the issue. Overall, a pleasant stay.",
    "The rental was stunning and exactly what we were looking for on our weekend getaway.",
    "The check-in process was smooth, and the host was very communicative throughout our stay.",
    "Perfect for a couple’s retreat! The rental had a romantic vibe and a lovely outdoor area.",
    "The location was a bit remote, but the tranquility made up for it. A great escape from the city."
];

export const activityReviewComments = [
    "This was an unforgettable experience! The guide was knowledgeable and friendly.",
    "Absolutely loved this activity! It was well-organized and fun from start to finish.",
    "The adventure exceeded my expectations. Perfect for thrill-seekers!",
    "Had a great time! The staff made sure everyone felt safe and comfortable.",
    "This was a unique and exciting activity. I’d definitely do it again!",
    "The activity was enjoyable, but it started a bit later than scheduled.",
    "A wonderful experience for the whole family. The kids had a blast!",
    "The guide was fantastic and kept the energy high throughout the activity.",
    "Beautiful scenery and an incredible experience overall. Highly recommended!",
    "It was fun but a bit too short for the price. Would love a longer session.",
    "The instructions were clear, and the staff made sure we had everything we needed.",
    "An exhilarating activity! Great for anyone looking for something out of the ordinary.",
    "The pace of the activity was just right, and everyone was able to keep up.",
    "The activity was well-planned, and the equipment was in great condition.",
    "This was the highlight of our trip! Can’t wait to come back and do it again.",
    "The group size was small, which made the experience more personal and enjoyable.",
    "It was a bit challenging at first, but the team made it so much fun!",
    "A great mix of relaxation and adventure. Perfect for all ages.",
    "I learned so much during this activity! The guides were passionate and engaging.",
    "The weather was perfect, and the activity was even better than we imagined!"
];