import { HOST } from "@/common/constants"
import { APP_NAME } from "@repo/constants"
import { Metadata } from "next"
import HostListing from "@/module/Admin/Listings/ForReview"
import AuthGuard from "@/common/components/AuthGuard"

export const metadata: Metadata = {
  title: `${HOST} - ${APP_NAME}`,
  description: `Generated by ${APP_NAME}`,
}

const ListingPage = () => {
  return (
    <AuthGuard>
      <HostListing />
    </AuthGuard>
  )
}

export default ListingPage
