import { HOST } from "@/common/constants"
import { APP_NAME } from "@repo/constants"
import { Metadata } from "next"
import HostingTodayCurrently from "@/module/Hosting/Today/Currently"
import AuthGuard from "@/common/components/AuthGuard"

export const metadata: Metadata = {
  title: `${HOST} - ${APP_NAME}`,
  description: `Generated by ${APP_NAME}`,
}

const HostingTodayCurrentlyPage = () => {
  return (
    <AuthGuard>
      <HostingTodayCurrently />
    </AuthGuard>
  )
}

export default HostingTodayCurrentlyPage
