import { APP_NAME } from "@repo/constants"
import { BOOKINGS } from "@/common/constants"
import { Metadata } from "next"

export const metadata: Metadata = {
  title: `${BOOKINGS} - ${APP_NAME}`,
  description: `Generated by ${APP_NAME}`,
}

const BookingsPage = () => {
  return <div>TEST</div>
}

export default BookingsPage
