import { HOST } from "@/common/constants"
import { APP_NAME } from "@repo/constants"
import { Metadata } from "next"
import HostingCalendar from "@/module/Hosting/Calendar"
import AuthGuard from "@/common/components/AuthGuard"

export const metadata: Metadata = {
  title: `${HOST} - ${APP_NAME}`,
  description: `Generated by ${APP_NAME}`,
}

const HostingCalendarPage = () => {
  return (
    <AuthGuard>
      <HostingCalendar />
    </AuthGuard>
  )
}

export default HostingCalendarPage
