import { HOST } from "@/common/constants"
import { APP_NAME } from "@repo/constants"
import { Metadata } from "next"
import HostingReservationsCompleted from "@/module/Hosting/Reservations/Completed"
import AuthGuard from "@/common/components/AuthGuard"

export const metadata: Metadata = {
  title: `${HOST} - ${APP_NAME}`,
  description: `Generated by ${APP_NAME}`,
}

const HostingReservationsCompletedPage = () => {
  return (
    <AuthGuard>
      <HostingReservationsCompleted />
    </AuthGuard>
  )
}

export default HostingReservationsCompletedPage
