import { APP_NAME } from "@repo/constants"
import { BOOKINGS } from "@/common/constants"
import { Metadata } from "next"
import GroupBookings from "@/module/Bookings/group"

export const metadata: Metadata = {
  title: `${BOOKINGS} - ${APP_NAME}`,
  description: `Generated by ${APP_NAME}`,
}

const BookingsPage = () => {
  return <GroupBookings/>
}

export default BookingsPage
