import { HOST } from "@/common/constants"
import { APP_NAME } from "@repo/constants"
import { Metadata } from "next"
import HostingTodayUpcoming from "@/module/Hosting/Today/Upcoming"
import AuthGuard from "@/common/components/AuthGuard"

export const metadata: Metadata = {
  title: `${HOST} - ${APP_NAME}`,
  description: `Generated by ${APP_NAME}`,
}

const HostingTodayUpcomingPage = () => {
  return (
    <AuthGuard>
      <HostingTodayUpcoming />
    </AuthGuard>
  )
}

export default HostingTodayUpcomingPage
