import { HOST } from "@/common/constants"
import { APP_NAME } from "@repo/constants"
import { Metadata } from "next"
import Facilities from "@/module/Admin/Listings/ForReview/Property/Facilities"
import AuthGuard from "@/common/components/AuthGuard"

export const metadata: Metadata = {
  title: `${HOST} - ${APP_NAME}`,
  description: `Generated by ${APP_NAME}`,
}

const ListingFacilitiesPage = () => {
  return (
    <AuthGuard>
      <Facilities pageType="setup" />
    </AuthGuard>
  )
}

export default ListingFacilitiesPage
