import { HOST } from "@/common/constants"
import { APP_NAME } from "@repo/constants"
import { Metadata } from "next"
import HostingInsights from "@/module/Hosting/Insights"
import AuthGuard from "@/common/components/AuthGuard"

export const metadata: Metadata = {
  title: `${HOST} - ${APP_NAME}`,
  description: `Generated by ${APP_NAME}`,
}

const HostingInsightsPage = () => {
  return (
    <AuthGuard>
      <HostingInsights />
    </AuthGuard>
  )
}

export default HostingInsightsPage
