import AuthGuard from "@/common/components/AuthGuard"
import React from "react"
import { APP_NAME } from "@repo/constants"
import { Metadata } from "next"
import AdminListing from "@/module/Admin/Listings/Live"

export const metadata: Metadata = {
  title: `Earnings - ${APP_NAME}`,
  description: `Generated by ${APP_NAME}`,
}

const ActivitiesTableTab = () => {
  return (
    <AuthGuard>
      <AdminListing />
    </AuthGuard>
  )
}

export default ActivitiesTableTab
