import { HOST } from "@/common/constants"
import { APP_NAME } from "@repo/constants"
import { Metadata } from "next"
import AuthGuard from "@/common/components/AuthGuard"
import RentalPhotos from "@/module/Hosting/Listings/Rentals/Rental/Photos"

export const metadata: Metadata = {
  title: `${HOST} - ${APP_NAME}`,
  description: `Generated by ${APP_NAME}`,
}

const RentalPhotosPage = () => {
  return (
    <AuthGuard>
      <RentalPhotos pageType="setup" />
    </AuthGuard>
  )
}

export default RentalPhotosPage
