import { HOST } from "@/common/constants"
import { APP_NAME } from "@repo/constants"
import { Metadata } from "next"
import AuthGuard from "@/common/components/AuthGuard"
import Pricing from "@/module/Hosting/Listings/Activities/Activity/Pricing"

export const metadata: Metadata = {
  title: `${HOST} - ${APP_NAME}`,
  description: `Generated by ${APP_NAME}`,
}

const ActivityAdditionalInfoPage = () => {
  return (
    <AuthGuard>
      <Pricing pageType="edit" />
    </AuthGuard>
  )
}

export default ActivityAdditionalInfoPage
