import { HOST } from "@/common/constants"
import { APP_NAME } from "@repo/constants"
import { Metadata } from "next"
import AuthGuard from "@/common/components/AuthGuard"
import Itinerary from "@/module/Admin/Listings/Live/Activity/Itinerary"

export const metadata: Metadata = {
  title: `${HOST} - ${APP_NAME}`,
  description: `Generated by ${APP_NAME}`,
}

const ActivityItineraryPage = () => {
  return (
    <AuthGuard>
      <Itinerary pageType="edit" />
    </AuthGuard>
  )
}

export default ActivityItineraryPage
